### ISSUE TITLE
Flutter-Desktop (MacOS) Support

### ISSUE THREAD

**Issue by JayPerfetto** [fluttercandies/flutter_wechat_assets_picker#10]
Are there any plans to enable support for Desktop? I have this successfully implemented on ios and android, but I am currently seeing the following error, despite having the permissions/capabilities in my entitlements folders:

flutter: [FilePicker] Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method ANY on channel miguelruivo.flutter.plugins.filepicker)
flutter: ****** EXCEPTION
flutter: No implementation found for method ANY on channel miguelruivo.flutter.plugins.filepicker

**Comment by AlexVincent525** [comment]
> Are there any plans to enable support for Desktop? 

I'll bring this to the author of `photo_manager`. Before any commitment about desktop support from us, you can still try to implement the plugin into the desktop platform.

> flutter: [FilePicker] Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method ANY on channel miguelruivo.flutter.plugins.filepicker)

Is this something you are currently working on? Seems nothing related with this package...

**Comment by AlexVincent525** [comment]
Back from @CaiJingLong , support for MacOS can be done, but other desktop platform such as Windows, Linux (which does not have a concept of gallery) will not support this. And it'll takes a while.

**Comment by AlexVincent525** [comment]
MacOS support has been added in `1.7.0-dev.1`, please try this version to see if it work.

**Comment by AlexVincent525** [comment]
Released with v1.7.0.
