### ISSUE TITLE
[BUG] Error with something

### ISSUE THREAD

**Issue by carl0804** [fluttercandies/flutter_wechat_assets_picker#105]
After import 'package:wechat_assets_picker/wechat_assets_picker.dart';
I got this error. How to solve?
```
cn/wechat_assets_picker-5.1.3/lib/src/widget/custom_checkbox.dart:595:31: Error: Type 'RenderToggleable' not found.
class _RenderCheckbox extends RenderToggleable {
                              ^^^^^^^^^^^^^^^^
```
**Device information (设备信息)**
 - Device: Pixel 3 XL emulator
 - OS: Android 10, API 29
 - Package Version: 5.1.3
 - Flutter Version: 2.3.0-1.0.pre.165

**Additional context (附加信息)**
Add any other context about the problem here. 在此提供更多的内容。

**Comment by AlexV525** [comment]
Duplicate with #93 .
