### ISSUE TITLE
[BUG] Failed to run `flutter packages pub run build_runner watch --delete-conflicting-outputs`

### ISSUE THREAD

**Issue by purgeyao** [fluttercandies/flutter_wechat_assets_picker#106]
**Describe the bug (描述)**
执行flutter packages pub run build_runner watch --delete-conflicting-outputs 出现异常

**How to reproduce (如何复现)**
Please **provide a minimum demo** rather than **a full project or a incomplete pages**. Otherwise we have rights to reject your request.

请提供一个**最小化的demo**用于复现，而不要提供**整个项目或者不完整的页面**，否则我们有权拒绝你的请求。

Steps to reproduce the behavior (描述复现步骤):

wechat_assets_picker: ^5.1.3
auto_route: ^0.6.9
auto_route_generator: ^0.6.9

如果去除wechat_assets_picker依赖 执行flutter packages pub run build_runner watch --delete-conflicting-outputs一切正常

如果存在wechat_assets_picker: ^5.1.3 

执行flutter packages pub run build_runner watch --delete-conflicting-outputs 出现下面异常

```
[INFO] Running build...
[INFO] 1.1s elapsed, 64/66 actions completed.
[INFO] 2.3s elapsed, 146/147 actions completed.
[INFO] 3.3s elapsed, 146/147 actions completed.
[INFO] 4.3s elapsed, 146/147 actions completed.
[SEVERE] auto_route_generator:autoRouteGenerator on test/widget_test.dart:

NoSuchMethodError: The getter 'flow' was called on null.
Receiver: null
Tried calling: flow
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      ResolverVisitor.startNullAwarePropertyAccess (package:analyzer/src/generated/resolver.dart:758:23)
#2      ResolverVisitor.visitPropertyAccess (package:analyzer/src/generated/resolver.dart:1730:5)
#3      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8398:49)
#4      BinaryExpressionResolver._resolveEqual (package:analyzer/src/dart/resolver/binary_expression_resolver.dart:111:10)
#5      BinaryExpressionResolver.resolve (package:analyzer/src/dart/resolver/binary_expression_resolver.dart:58:7)
#6      ResolverVisitor.visitBinaryExpression (package:analyzer/src/generated/resolver.dart:897:31)
#7      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:954:49)
#8      BinaryExpressionResolver._resolveLogicalOr (package:analyzer/src/dart/resolver/binary_expression_resolver.dart:224:11)
#9      BinaryExpressionResolver.resolve (package:analyzer/src/dart/resolver/binary_expression_resolver.dart:63:7)
#10     ResolverVisitor.visitBinaryExpression (package:analyzer/src/generated/resolver.dart:897:31)
#11     BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:954:49)
#12     ResolverVisitor.visitAssertInitializer (package:analyzer/src/generated/resolver.dart:856:21)
#13     AssertInitializerImpl.accept (package:analyzer/src/dart/ast/ast.dart:517:49)
#14     AstResolver.resolve (package:analyzer/src/summary2/ast_resolver.dart:85:10)
#15     ConstructorInitializerResolver._initializers (package:analyzer/src/summary2/constructor_initializer_resolver.dart:68:20)
#16     ConstructorInitializerResolver._constructor (package:analyzer/src/summary2/constructor_initializer_resolver.dart:54:5)
#17     ConstructorInitializerResolver.resolve (package:analyzer/src/summary2/constructor_initializer_resolver.dart:31:11)
#18     LibraryBuilder.resolveConstructors (package:analyzer/src/summary2/library_builder.dart:240:53)
#19     Linker._resolveConstructors (package:analyzer/src/summary2/link.dart:210:15)
#20     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:95:5)
#21     Linker.link (package:analyzer/src/summary2/link.dart:76:5)
#22     link (package:analyzer/src/summary2/link.dart:32:10)
#23     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:215:24)
#24     LibraryContext.load2.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:123:26)
#25     SetMixin.forEach (dart:collection/set.dart:142:30)
#26     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:122:32)
#27     LibraryContext.load2.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:123:26)
#28     SetMixin.forEach (dart:collection/set.dart:142:30)
#29     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:122:32)
#30     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:262:17)
#31     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#32     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:260:12)
#33     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:77:5)
#34     AnalysisDriver._createLibraryContext.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1538:27)
#35     _rootRun (dart:async/zone.dart:1354:13)
#36     _CustomZone.run (dart:async/zone.dart:1258:19)
#37     _runZoned (dart:async/zone.dart:1788:10)
#38     runZoned (dart:async/zone.dart:1710:10)
#39     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#40     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1536:33)
#41     AnalysisDriver._computeUnitElement.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1464:28)
#42     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#43     AnalysisDriver._computeUnitElement (package:analyzer/src/dart/analysis/driver.dart:1462:20)
#44     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1020:34)
#45     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2013:24)
<asynchronous suspension>


[WARNING] No actions completed for 16.8s, waiting on:
  - auto_route_generator:autoRouteGenerator on lib/router/route_map.dart

[INFO] 19.4s elapsed, 146/147 actions completed.
[INFO] 20.4s elapsed, 146/147 actions completed.
[INFO] 21.5s elapsed, 146/147 actions completed.
[INFO] 22.5s elapsed, 146/147 actions completed.
[INFO] 23.6s elapsed, 146/147 actions completed.
[INFO] 24.6s elapsed, 146/147 actions completed.
[INFO] 25.6s elapsed, 146/147 actions completed.
[INFO] 26.6s elapsed, 146/147 actions completed.
[INFO] 27.7s elapsed, 146/147 actions completed.
[INFO] 28.8s elapsed, 146/147 actions completed.
[INFO] 29.9s elapsed, 146/147 actions completed.
[INFO] 30.9s elapsed, 146/147 actions completed.

```
**Expected behavior (期望行为)**

**Screenshots (If contains) (是否有截图可以提供)**

**Device information (设备信息)**
 - Package Version: [e.g. 22]
 - Flutter Version: [e.g. v1.17.1]

**Additional context (附加信息)**
Add any other context about the problem here. 在此提供更多的内容。

**Comment by AlexV525** [comment]
Run `flutter pub global activate dartdoc 0.40.0`.

**Comment by purgeyao** [comment]
The above error will still occur

**Comment by AlexV525** [comment]
It has a related issue before in https://github.com/dart-lang/dartdoc/issues/2577 , if the error is still occur, I believe it's still a dartdoc's issue.

**Comment by AlexV525** [comment]
I've checked the latest version of `auto_route` (2.0.1) and your version (0.6.9) seems too old for the current SDK. Please upgrade them and try again.

**Comment by AlexV525** [comment]
The version `5.1.3` is not supported on 1.17.x, the minimum constraint is 2.0.0.

**Comment by MuhammadUsmanVenD** [comment]
I am facing same issue on 

Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (3 weeks ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

Here is my Pubspec.yaml file 

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  google_sign_in: ^5.0.2
  flutter_facebook_login: ^3.0.0
  flutter_spinkit: ^5.0.0
  http: ^0.13.2
  google_maps_flutter: ^2.0.3
  flutter_bloc: ^7.0.0
  sign_in_with_apple: ^3.0.0
  sqflite: ^1.3.0
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  firebase_core: ^1.2.1
  firebase_messaging: ^10.0.1
  flutter_local_notifications: ^5.0.0
  device_info_plus: ^1.0.1
  image_picker: ^0.7.5+2
  file_picker: ^3.0.1
  chewie: ^1.2.2
  video_player: ^2.1.6
  flutter_speed_dial: ^3.0.5
  wechat_assets_picker: any
  carousel_slider: ^3.0.0
  flutter_image_compress: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  build_runner: ^1.0.0


here is flutter doctor verbose

[✓] Flutter (Channel stable, 2.2.1, on macOS 11.1 20C69 darwin-x64, locale
    en-PK)
    • Flutter version 2.2.1 at /Users/vend/Documents/FlutterSpace/SDK/flutter
    • Framework revision 02c026b03c (3 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/vend/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 12 mini (mobile) • 6CC66ABE-D7EC-4C2F-8B9E-9CF45849AE90 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)            • chrome                               •
      web-javascript • Google Chrome 91.0.4472.101

• No issues found!
<img width="1343" alt="Screenshot 2021-06-16 at 11 38 47 AM" src="https://user-images.githubusercontent.com/83270472/122169956-76982c80-ce97-11eb-81b5-84331e05ff73.png">

**Comment by AlexV525** [comment]
Upgrade all your dependencies to the latest version and try again. From your pubspec, you're using at least 6 packages which is outdated.

**Comment by MuhammadUsmanVenD** [comment]
That because we are not using null safety for now

**Comment by AlexV525** [comment]
That's nothing related to null-safety. You can use the latest version of packages even if your project is not migrated. Please upgrade them and try again.

I have multiple projects includes this package and none of them occurred this issue with the latest packages.
