### ISSUE TITLE
可以增加一个属性,用来控制第一个表格是拍照功能吗?

### ISSUE THREAD

**Issue by layou1989** [fluttercandies/flutter_wechat_assets_picker#11]
可以增加一个属性,用来控制第一个表格是拍照功能吗? 还有最好也能把theme参数提供出来，可能有的需要的是浅色主题

**Comment by AlexVincent525** [comment]
该组件的目标是还原微信选择器，微信中是否有第一个为拍照的情况？

另，主题问题请另开issue进行记录。

**Comment by AlexVincent525** [comment]
Closing with no further information provided.
