### ISSUE TITLE
[BUG] Ability to choose both video and image in SpecialPickerType.wechatMoment

### ISSUE THREAD

**Issue by yanivshaked** [fluttercandies/flutter_wechat_assets_picker#110]
**Bug description**
When using SpecialPickerType.wechatMoment, I am able to select both image and video files.
I made sure that this bug is NOT related to the noPreview changes.

**How to reproduce**
- Run the example
- Click Single Asset picker page
- Click WeChat moment
- Click on an image to get its preview
- Select it using the "Select" button at the bottom bar
- Swipe right till you get a video asset
- Select it using the "Select" button at the bottom bar
- Click done

**Expected behavior**
Should not allow selection of video if image is already selected (and vice versa).

**Screenshots (If contains)**
If needed, I can upload a video.

**Device information**
 - Device: Android OnePlus 8T
 - OS: Android 10
 - Package Version: 5.1.3 or 5.2.0 (reproduced on both)
 - Flutter Version: 2.0.5

**Additional context**
Let me know what are your thoughts on solving this, I can submit a PR.

**Comment by AlexV525** [comment]
We should filtered selected assets with only images in WeChat Moment mode when `pushToViewer` is called.

**Comment by AlexV525** [comment]
And make the previewing video the only one in the preview list.

**Comment by AlexV525** [comment]
Nvm, I'll apply a quick fix to this.

**Comment by AlexV525** [comment]
@all-contributors Add @yanivshaked for bug.
