### ISSUE TITLE
[BUG] Ability to choose more assets than allowed to (maxAssets)

### ISSUE THREAD

**Issue by yanivshaked** [fluttercandies/flutter_wechat_assets_picker#115]
**Bug description**
Ability to choose more items than the picker was allowed to (`maxAssets`).

**How to reproduce**
- Run the example
- Click Single Asset picker page
- Click WeChat moment (or any other option that is NOT no preview)
- Click on an image to get its preview
- Select it using the "Select" button at the bottom bar
- Swipe right to get to the next image
- Select it
- Keep doing so until you select 10 images
- Click the back button
- You have 10 images selected (when 9 is the maximal number)

**Expected behavior**
Should not allow selection of more than maxAssets

**Screenshots**
For example, I selected 12 assets:
<img src="https://user-images.githubusercontent.com/13107481/116804267-1c7d1b00-ab26-11eb-9c51-a35d481dfc5a.png" alt="Screenshot" width="40%" height="40%">

**Device information**
- Device: Android OnePlus 8T
- OS: Android 10
- Package Version: 5.2.1
- Flutter Version: 2.0.5

**Additional context**
Let me know what are your thoughts on solving this, I can submit a PR.

**Comment by AlexV525** [comment]
Is this reproducible in other methods?

**Comment by yanivshaked** [comment]
Reproducible whenever the preview is displayed. Select 9 assets, preview an asset which was not selected and select it => You have 10 assets selected.

**Comment by AlexV525** [comment]
Then we should add a count check at here maybe.
https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/cacb7b906ed0b9b598e829aa7888588a03f1bd6c/lib/src/delegates/asset_picker_viewer_builder_delegate.dart#L123

**Comment by yanivshaked** [comment]
This also requires transferring `maxAssets` to `AssetPickerViewer.pushToViewer`, agree?

**Comment by yanivshaked** [comment]
Another option, is to use the `selectorProvider` for selection (so the validation is done in one place), but it is not always transferred to the `AssetPickerViewerBuilderDelegate`.

**Comment by AlexV525** [comment]
> This also requires transferring `maxAssets` to `AssetPickerViewer.pushToViewer`, agree?

This sounds more reasonable.

**Comment by yanivshaked** [comment]
Merge is done, I'm closing this issue
