### ISSUE TITLE
更新 Flutter 1.17.0 后无法编译

### ISSUE THREAD

**Issue by hidetag** [fluttercandies/flutter_wechat_assets_picker#12]
经查：
是 extended_image_slide_page_route.dart 中下图方法缺少参数：
<img width="449" alt="image" src="https://user-images.githubusercontent.com/15097928/81377262-b12d8280-9137-11ea-8e44-ea1601c56133.png">

下图是 Flutter 1.17.0 的代码
<img width="473" alt="image" src="https://user-images.githubusercontent.com/15097928/81377317-cf937e00-9137-11ea-8113-e4f61690e4b3.png">

希望作者尽快升级 extended_image 至最新版

PS：另外打开相册确实非常卡，，非常非常卡。。。不知可有什么优化没，iOS&Andorid

**Comment by AlexVincent525** [comment]
正在思考怎么处理版本兼容问题...

另外，打开相册也不应会卡顿，顶多是加载时间较长，在1.4.x已经做了分页，是否有尝试？

**Comment by hidetag** [comment]
稍后我录个屏看看

**Comment by AlexVincent525** [comment]
性能问题请开一个新的issue进行记录。版本冲突问题已进行调整。
