### ISSUE TITLE
[photo_manager] Support for limited access: ask for extra images

### ISSUE THREAD

**Issue by yanivshaked** [fluttercandies/flutter_wechat_assets_picker#125]
**Version information**
 - Device: iPhone 12 Pro
 - OS: iOS 14.4.2
 - Package Version: v5.4.0+1
 - Flutter Version: v2.0.5

**Is your feature request related to a problem?**
Yes. On iOS 14, a new model of permission was introduced. The user can select only several pictures from the device's gallery and those pictures are available to the picker.
If the user opens the gallery again, he is NOT asked to give more pictures if he wants.
(See how WhatsApp have solved this issue).

**Describe the solution you'd like**
It should be possible for the user to bring up the native popup asking for more pictures to be added to the selection.
(This is done using the iOS `PHPhotoLibrary.shared().presentLimitedLibraryPicker` method)

**Additional context**
This issue is related to `photo_manager` and the solution should be joint.
I'm attaching a video that shows the problem:

https://user-images.githubusercontent.com/13107481/117576434-aa40a380-b0ee-11eb-8056-475d557f8d69.mp4

This is how WhatsApp solved this issue (we need something similar):

https://user-images.githubusercontent.com/13107481/117576596-32bf4400-b0ef-11eb-9ba3-80a8f1878657.mp4

**Comment by AlexV525** [comment]
https://github.com/CaiJingLong/flutter_photo_manager/issues/385

**Comment by yanivshaked** [comment]
I think you are too quick closing it; Beside the photo_manager support required, there should be also code supporting it in this plugin.

**Comment by AlexV525** [comment]
It shouldn't, at least for now.

**Comment by blackchineykh** [comment]
What should we be doing to handle this situation? I have this issue and i'm not sure what approach to take to resolve it as I have a case where the user has given limited access but there is no way for me to have them change this or go back to selecting other photos

**Comment by AlexV525** [comment]
> What should we be doing to handle this situation? I have this issue and i'm not sure what approach to take to resolve it as I have a case where the user has given limited access but there is no way for me to have them change this or go back to selecting other photos

Please subscribe CaiJingLong/flutter_photo_manager#385 for further implementations.

**Comment by yanivshaked** [comment]
@blackchineykh In general, the `photo_manager` should support the following:
- Return a new value indicating the user has used limited photo access.
- Allow asking the user to select more images using `PHPhotoLibrary.shared().presentLimitedLibraryPicker` with a new method.
- Adding the required support for that in this plugin.

**Comment by mishatron** [comment]
Why this issue is closed? As described photo_manager 1.2.0 implemented ios 14 limited access. So,  please, add ability to open this picker if we have limited access

**Comment by AlexV525** [comment]
This requires to sync with the latest WeChat version (8.x). They will be handled together.

**Comment by AlexV525** [comment]
This has been implemented by multiple commits, and will be released along with the 6.0.0 version.
  * 6f20c77
  * 0cbd815
  * f870524
