### ISSUE TITLE
[BUG] 更新android studio 4.2后，flutter build apk时候photo_manager-1.1.6出错

### ISSUE THREAD

**Issue by Etermally** [fluttercandies/flutter_wechat_assets_picker#126]
**Describe the bug (描述)**

[BUG] 当我更新android studio 4.2后，flutter build apk时候photo_manager-1.1.6出错，说是：(When I update android studio 4.2, the photo_manager-1.1.6 error occurs when flutter build apk, saying:)
e: /Users/d/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-1.1.6/android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerDeleteManager.kt: (116, 36): Unresolved reference: R
e: /Users/d/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-1.1.6/android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerDeleteManager.kt: (119, 36): Unresolved reference: createTrashRequest
e: /Users/d/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-1.1.6/android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerPlugin.kt: (356, 73): Unresolved reference: R
e: /Users/d/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-1.1.6/android/src/main/kotlin/top/kikt/imagescanner/core/utils/Android30DbUtils.kt: (35, 34): Unresolved reference: R
e: /Users/d/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-1.1.6/android/src/main/kotlin/top/kikt/imagescanner/core/utils/IDBUtils.kt: (28, 67): Unresolved reference: R

截图是：
![Uploading 截屏2021-05-10 下午4.01.35.png…]()

能修复一下吗？大神~(Can you fix it? Great God~)

**Comment by Etermally** [comment]
特别急~~~大佬，或者指导一下怎么修复也可以，麻烦了  谢谢

**Comment by AlexV525** [comment]
flutter clean?
