### ISSUE TITLE
[Optimize scrolling] Scrolling of grid shows black/empty items

### ISSUE THREAD

**Issue by yanivshaked** [fluttercandies/flutter_wechat_assets_picker#127]
Problem description:
When scrolling the grid, it happens very often that all the grid items become black, and then they are repopulated. It's a very bad experience for the user. It happens even when using very low resolution for the grid items.

Optimization suggestion:
Consider replacing the `GridView.builder` with `SliverGrid` with `SliverChildBuilderDelegate` that has `findChildIndexCallback`.
It is most likely that it will improve performance of scrolling.

If that direction sounds ok to you, I will be happy to try it and submit a PR.
If you have other thought, please share.

Thanks,
Yaniv

**Comment by AlexV525** [comment]
If it does help, I'd hapoy to see you fix this.

**Comment by yanivshaked** [comment]
Following branch has the relevant changes, but issue is not solved:
https://github.com/12Tech12/flutter_wechat_assets_picker/tree/20210510_Fix_Grid_Scrolling

1. There are multiple calls to `provider.loadMoreAssets` for the same page. I have fixed it using a critical section flag (dart is single threaded).
2. Instead of replacing the entire `_currentAssets` list, I'm adding more assets to that list.

I have replaced `GridView.builder` with `SliverGrid` that has `findChildIndexCallback` - and that routine is called everytime the list is enlarged, but the paging issue is still there, entire grid is refreshed.

I'm still working on it, but please share your thoughts :-)

**Comment by AlexV525** [comment]
I do found a new way to solve this, will file a PR soon.
