### ISSUE TITLE
Button is Chinese text not en format

### ISSUE THREAD

**Issue by ashishkj93** [fluttercandies/flutter_wechat_assets_picker#137]
**Describe the bug (描述)**
A clear and concise description of what the bug is. 请用精炼的语句准确描述你遇到的BUG。

**How to reproduce (如何复现)**
Please **provide a minimum demo** rather than **a full project or a incomplete pages**. Otherwise we have rights to reject your request.

请提供一个**最小化的demo**用于复现，而不要提供**整个项目或者不完整的页面**，否则我们有权拒绝你的请求。

Steps to reproduce the behavior (描述复现步骤):

**Expected behavior (期望行为)**

**Screenshots (If contains) (是否有截图可以提供)**

**Device information (设备信息)**
 - Package Version: [e.g. 22]
 - Flutter Version: [e.g. v1.17.1]

**Additional context (附加信息)**
Add any other context about the problem here. 在此提供更多的内容。

**Comment by AlexV525** [comment]
#28

**Comment by xiyulangzi** [comment]
@ashishkj93 , see solution in comments of #143

**Comment by ashishkj93** [comment]
I have added this package then after all ui is show chainees text. It is not compatible with other language

**Comment by yanivshaked** [comment]
@ashishkj93 You can use your own delegate to add support for any language you want.
