### ISSUE TITLE
Web support.

### ISSUE THREAD

**Issue by Simouche** [fluttercandies/flutter_wechat_assets_picker#140]
**Version information (版本信息)**
 - Web.

**Is your feature request related to a problem?  (功能是否与已有问题关联)**
no.

**Describe the solution you'd like (描述你期望的解决方案)**
Web support for this plugin.

**Describe alternatives you've considered (其他解决方案或疑虑)**
other plugins.

**Additional context (附加内容)**
i tried using this plugin in the flutter web, but i didn't work. i'd be nice to have this working on the web.

**Comment by AlexV525** [comment]
#28
