### ISSUE TITLE
3 Key Buttons' text show Chinese even when Phone system language setting is English

### ISSUE THREAD

**Issue by xiyulangzi** [fluttercandies/flutter_wechat_assets_picker#143]
**Describe the bug (描述)**
A clear and concise description of what the bug is. 请用精炼的语句准确描述你遇到的BUG。

=> the 3 key buttons in the UI are not translated in English, always show Chinese even the phone system language is English 

**How to reproduce (如何复现)**
Please **provide a minimum demo** rather than **a full project or a incomplete pages**. Otherwise we have rights to reject your request.

=> Steps:
- Change Phone system language to English
- run app utilise this plugin
- check the 3 key buttons (confirm, selected, preview), they should show in English,
- but those 3 buttons show Chinese.

请提供一个**最小化的demo**用于复现，而不要提供**整个项目或者不完整的页面**，否则我们有权拒绝你的请求。

//put a button's onPressed: to below function

`
  void pickImageFromGallery() async {
    final List<AssetEntity>? assets =
        await AssetPicker.pickAssets(context, requestType: RequestType.image);

    if (assets == null) return;

    for (int i = 0; i < assets.length; i++) {
      File? file = await assets[i].originFile;
      debugPrint(file!.path);
    }
  }
`

Steps to reproduce the behavior (描述复现步骤):
1.  change phone system language to English
2. open the test app which triggered from the onPressed function mentioned above
3. check the UI text,
4. See error as buttons always show Chinese

**Expected behavior (期望行为)**

=> If phone system language is  English(or NON-Chinese, the buttons text should show in English)

**Screenshots (If contains) (是否有截图可以提供)**

**Device information (设备信息)**
 - Device: [e.g. iPhone6] -> Xiaomi 10, 
 - OS: [e.g. iOS8.1]  ->Android 10
 - Package Version: [e.g. 22]  -> 5.5.3+1 
 - Flutter Version: [e.g. v1.17.1] -> 2.2.0

**Additional context (附加信息)**
Add any other context about the problem here. 在此提供更多的内容。

=> The Plug is a good one, if support English, then it can be used more widely ;-)
Hope you can fix this to have more people use the plugin

**Comment by xiyulangzi** [comment]
![picker1](https://user-images.githubusercontent.com/595102/119237704-103d1a00-bb36-11eb-8189-df818e2dfdfd.jpg)
![picker2](https://user-images.githubusercontent.com/595102/119237708-10d5b080-bb36-11eb-9324-ebaa21bb59f3.jpg)

I marked the button where they show Chinese when phone system language is English

**Comment by AlexV525** [comment]
We don't following system's language by default. Please check the implementation about the text delegate which requires a passthrough.

**Comment by xiyulangzi** [comment]
To help other guys who like use other languages. I put my working code for your reference:
you can find from the code that there are a few other languages in additional to Chinese and English the plugin support if you need them.

FYI: @AlexV525 

`
  /*
  * pickup multiple images from gallery for upload
  * https://pub.dev/packages/wechat_assets_picker
  */
  void pickImageFromGallery() async {
    String? locale = await Devicelocale.currentLocale; //en_GB
    if (locale != null) {
      debugPrint(
          "Locale:" + locale + " =>" + locale.substring(0, 2).toString());
      locale = locale.substring(0, 2).toString().toLowerCase();
    } else {
      locale = 'en';
    }
    var assetPickerTextDelegate;
    switch (locale) {
      case "en":
        assetPickerTextDelegate = EnglishTextDelegate();
        break;
      case "zh":
        assetPickerTextDelegate = DefaultAssetsPickerTextDelegate();
        break;
      default:
        assetPickerTextDelegate = DefaultAssetsPickerTextDelegate();
        break;
    }

    final List<AssetEntity>? assets = await AssetPicker.pickAssets(context,
        requestType: RequestType.image, textDelegate: assetPickerTextDelegate);

    imageCounts = 0;
    imagesPaths.clear();

    if (assets == null) return;

    for (int i = 0; i < assets.length; i++) {
      File? file = await assets[i].originFile;
      imageCounts += 1;
      imagesPaths.add(file!.path);
    }

  }
`
