### ISSUE TITLE
[Feature] Deactivate preview to allow user to click on the whole image to select it

### ISSUE THREAD

**Issue by ishomam** [fluttercandies/flutter_wechat_assets_picker#145]
**Describe the solution you'd like (描述你期望的解决方案)**
It would be nice to have the option to deactivate the preview so the picker user can click on the whole image to select it instead of having to click on the tiny circle in the corner of the image.

**Comment by yanivshaked** [comment]
This feature is already implemented. Use `specialPickerType: SpecialPickerType.noPreview`, or look at the example called `noPreview`.

**Comment by ishomam** [comment]
Oh great! thank you so much. Sorry, I wasn't aware of this.
