### ISSUE TITLE
[BUG] Console warning when opening the picker for the 1st time - W/Glide   (25328): Failed to find GeneratedAppGlideModule.

### ISSUE THREAD

**Issue by hyouuu** [fluttercandies/flutter_wechat_assets_picker#147]
**Describe the bug (描述)**
Console warning when opening the picker for the 1st time - W/Glide   (25328): Failed to find GeneratedAppGlideModule.  You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored

**How to reproduce (如何复现)**
Just call AssetPicker.pickAssets and monitor the console output

**Expected behavior (期望行为)**
No warnings about the Glide module

**Screenshots (If contains) (是否有截图可以提供)**
<img width="972" alt="Screen Shot 2021-06-01 at 11 27 27 AM" src="https://user-images.githubusercontent.com/5061867/120372698-59c2fd00-c2cc-11eb-9092-226bb6370013.png">

**Device information (设备信息)**
 - Device: Huawei LYA L29
 - OS: Android 10, EMUI 10.0.0
 - Package Version: 1.5.0
 - Flutter Version: v2.2.1

**Additional context (附加信息)**
Seems need to add annotation about the Glide lib. e.g. https://stackoverflow.com/a/56675218/1032900

**Comment by AlexV525** [comment]
Don't you guys ever read the README?
