### ISSUE TITLE
[Feature] Request a feature with something

### ISSUE THREAD

**Issue by wangyan-png** [fluttercandies/flutter_wechat_assets_picker#148]
**Version information (版本信息)**
 - Device: *e.g. iPhoneXR*
 - OS: **
 - Package Version: *4.2.2*
 - Flutter Version: *Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git*

**Is your feature request related to a problem?  (功能是否与已有问题关联)**否
A clear and concise description it it's related to a exist problem. (如果与已有问题有关，请准确描述)

**Describe the solution you'd like (描述你期望的解决方案)**
 requestType: RequestType.common,  方式时 选择视频后可否不允许其再选择图片
**Describe alternatives you've considered (其他解决方案或疑虑)**

**Additional context (附加内容)**
感谢

**Comment by yanivshaked** [comment]
RTM

**Comment by AlexV525** [comment]
#28
