### ISSUE TITLE
sometime aspect ratio is not correct.

### ISSUE THREAD

**Issue by rakesh4577** [fluttercandies/flutter_wechat_assets_picker#156]
first of all, this is really a great package thanks for that.
I am having some issues with the aspect ratio for videos, if `orientation` is not equal to 0 then the aspect ratio values aren't correct, I know it's not an issue with the package but I am unable to get the correct aspect ratio to display videos.

as a temp fix, I am using this but if orientation is not 0 and 270 then I am getting strange values

`
double getAspectRatio( assetEntity) {
  if (assetEntity.orientation == 270) {
    return Size(assetEntity.height.toDouble(), assetEntity.width.toDouble()).aspectRatio;
  }
  return assetEntity.size.aspectRatio;
}
`

**Comment by AlexV525** [comment]
File issues with the issue template. #28
