### ISSUE TITLE
Camera option not found when device doesn't have any image

### ISSUE THREAD

**Issue by HareshGediya** [fluttercandies/flutter_wechat_assets_picker#159]
- Device: Pixel 3A
 - OS: Android 11
 - Package Version: v5.5.6
 - Flutter Version: v2.2.2
 
Camera picker option not found in the grid list when a device doesn't have any images. Only showing **Nothing here**.

Run project in the device that doesn't have any images, and click Pick from camera. It is an open empty grid with Nothing here.

![Screenshot_1624598990](https://user-images.githubusercontent.com/23559753/123376559-4b54c200-d5a8-11eb-976e-a133efcd0dd1.png)

**Comment by AlexV525** [comment]
I do remember I've fixed something like this before, which is recorded at https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/master/CHANGELOG.md#500 . Let me take a quick glance.

**Comment by AlexV525** [comment]
Oh I missed to `allowSpecialItemWhenEmpty` argument, so you need to pass this argument as `true` when calling the `pickAssets` method.

```dart
AssetPicker.pickAssets(context, allowSpecialItemWhenEmpty: true);
```

Closing since it's not an issue actually. But thanks for the feedback.
