### ISSUE TITLE
[Feature] Update text delegates with the latest fields

### ISSUE THREAD

**Issue by AlexV525** [fluttercandies/flutter_wechat_assets_picker#161]
Since #160 , text delegates should be updated according to those new fields.
Please help us update them by *submit PRs that target to the 6.0 branch and make a ref to here.*
Appreciate for your previous contributions too.

/cc @yanivshaked @Letalus @greymag @KosukeSaigusa 

* [x] Hebrew #163 
* [x] German #168 
* [x] Russian df151678, #166
* [x] Japanese #185

If you're able to use WeChat, grant limited access to the WeChat and you'll see an overlay like this:

![image](https://user-images.githubusercontent.com/15884415/123506233-bb8d4180-d695-11eb-93cc-2d36890690b6.png)

**Comment by AlexV525** [comment]
Please be aware that if the rest delegates haven't got an update until the 6.0 version released, they will be temporary commented out to keep the functionality.

**Comment by Letalus** [comment]
sorry for being late, I was in my vacation. Will send a pull request within the next hours

**Comment by Letalus** [comment]
I'm not entirely sure how to merge my branch into the 6.0 branch. Here is the link with the latest german translation: https://github.com/Letalus/flutter_wechat_assets_picker/tree/german_translation

**Comment by AlexV525** [comment]
Friendly ping @KosukeSaigusa .

**Comment by AlexV525** [comment]
If we didn't received further updates from @KosukeSaigusa within this week, we will temporarily remove (comment out) the `JapaneseTextDelegate` until it gets update properly.
