### ISSUE TITLE
[Feature] Select Multiple Image From Camera

### ISSUE THREAD

**Issue by jayeshindianic** [fluttercandies/flutter_wechat_assets_picker#165]
**Version information (版本信息)**
 - Device: Android/Ios
 - OS: all
 - Package Version: 5.5.6
 - Flutter Version: 2.0.2

**Is your feature request related to a problem?  (功能是否与已有问题关联)**
i want to add one feature, i dont know this feature is alredy available, i read documentation but i not found, 
if any user want to select multiple image then click on button to select image currenly showen all gallery image but i want to user can also click image from camera also.

**Describe alternatives you've considered (其他解决方案或疑虑)**
i have achieve using this package: https://pub.dev/packages/multi_image_picker
but currently this package no more available.
```
try {
      resultList = await MultiImagePicker.pickImages(
        maxImages: 300,
        enableCamera: true,
        selectedAssets: images,
        cupertinoOptions: CupertinoOptions(takePhotoIcon: "chat"),
        materialOptions: MaterialOptions(
          actionBarColor: "#abcdef",
          actionBarTitle: "Example App",
          allViewTitle: "All Photos",
          useDetailsView: false,
          selectCircleStrokeColor: "#000000",
        ),
      );
    } on Exception catch (e) {
      error = e.toString();
    }
    ```
    you can see above code there have option to enable camera for pick image.

**Additional context (附加内容)**
Please Give me some hint to achive this, Thank you

**Comment by AlexV525** [comment]
Camera picking is supported by the `wechat_camera_picker` and there's a method for it in the example. Please run the example to check if it's something you want.

**Comment by jayeshindianic** [comment]
@AlexV525 i have tested but one of issues is when i select image from camera after that i need to select again from gallery to select more image, camera captured image by default not show in list of image screen, like multi+image_picker.

**Comment by jayeshindianic** [comment]
i want show captured image in selected image list

**Comment by AlexV525** [comment]
Override your own delegate to refresh the entities list after you've captured something from the camera picker.

**Comment by jayeshindianic** [comment]
```
TextButton(
                onPressed: () {
                  AssetPicker.pickAssets(context,
                          selectedAssets: selectedAssets,
                          textDelegate: EnglishTextDelegate(),
                          specialItemPosition: SpecialItemPosition.prepend,
                          requestType: RequestType.image,
                    specialItemBuilder: (BuildContext context) {
                      return GestureDetector(
                        behavior: HitTestBehavior.opaque,
                        onTap: () async {
                          final AssetEntity? result = await CameraPicker.pickFromCamera(
                            context,
                          );
                          if (result != null) {
                            setState(() {
                              selectedAssets!.add(result);
                            });
                            //handleResult(context, result);
                          }
                        },
                        child: const Center(
                          child: Icon(Icons.camera_enhance, size: 42.0),
                        ),
                      );
                    },)
                      .then((List<AssetEntity>? value) {
                    print(value!.length);
                  });
                },
                child: Text('Pick Image'))
                ```

**Comment by AlexV525** [comment]
```dart
PickMethod.camera(
  maxAssetsCount: maxAssetsCount,
  handleResult: (BuildContext context, AssetEntity result) async {
    final AssetPicker<AssetEntity, AssetPathEntity>? picker = context.findAncestorWidgetOfExactType();
     if (picker != null) {
      final DefaultAssetPickerProvider p = picker.builder.provider as DefaultAssetPickerProvider;
      await p.currentPathEntity!.refreshPathProperties();
      await p.switchPath(p.currentPathEntity!);
      p.selectAsset(result);
    }
  },
)
```

**Comment by jayeshindianic** [comment]
https://user-images.githubusercontent.com/79701614/123634534-2fffe600-d838-11eb-927b-e7fabb325a34.mov

first i have select image from gallery and then i selected from camera, but when i done i get only 1 image, my captured image is not default selected in list, like multi_image_picker.

**Comment by AlexV525** [comment]
And the example has updated now, added a new method called `cameraAndStay`.

**Comment by jayeshindianic** [comment]
Thank you @AlexV525

**Comment by jayeshindianic** [comment]
i have test your example, when i capture image from camera and come back with stay method, you can see in my attached screenshot image are show in list, but its not tick-mark (selected) but image counts are show 2 image is selected.

![Screenshot_1632295001](https://user-images.githubusercontent.com/79701614/134300410-63d672b3-a7b1-44ea-9d14-9bfe08c11c53.png)
