### ISSUE TITLE
selectedAssets(List<AssetEntity>?	) 使用asset的id或者其他的标识来判断

### ISSUE THREAD

**Issue by weisttl** [fluttercandies/flutter_wechat_assets_picker#170]
**Version information (版本信息)**
 - Device: *e.g. iPhone6*
 - OS: *e.g. iOS 13.4*
 - Package Version: *e.g. v2.1.0*
 - Flutter Version: *e.g. v1.17.1*

**Describe the solution you'd like (描述你期望的解决方案)**
使用AssetEntity对象来判断是否已选择在某些场景时（如重新编辑包含已选择的图片的草稿），希望改成文件id或者其他有唯一性的字符串

**Comment by AlexV525** [comment]
该类星系应由宿主自行维护。请按照 issue 模板提问 #28 。
