### ISSUE TITLE
能否本地图片和网络图片混合显示

### ISSUE THREAD

**Issue by gyyxiaogao** [fluttercandies/flutter_wechat_assets_picker#176]
**Version information (版本信息)**
 - Device: *e.g. iPhone6*
 - OS: *e.g. iOS 13.4*
 - Package Version: *e.g. v2.1.0*
 - Flutter Version: *e.g. v1.17.1*

**Is your feature request related to a problem?  (功能是否与已有问题关联)**
没有

**Describe the solution you'd like (描述你期望的解决方案)**
我们要对提交后的照片进行修改,也就是下次进来显示网络图片,但可以编辑添加本地图片

**Describe alternatives you've considered (其他解决方案或疑虑)**

**Additional context (附加内容)**

**Comment by AlexV525** [comment]
显示与否与 picker 无关，不属于设备的网络图片不可能显示在 picker 中，其他展示方式可以自行组织判断方法。
