### ISSUE TITLE
[BUG] 特殊图片名称导致返回AssetEntity的width,height为0

### ISSUE THREAD

**Issue by 1203556555** [fluttercandies/flutter_wechat_assets_picker#178]
**Describe the bug (描述)**
A clear and concise description of what the bug is. 请用精炼的语句准确描述你遇到的BUG。
图片名字导致获取不到width，height

**How to reproduce (如何复现)**
Please **provide a minimum demo** rather than **a full project or a incomplete pages**. Otherwise we have rights to reject your request.
当图片名字是F5b0988e595225.cdn.sohucs.com%2Fimages%2F20170913%2F3788a2c806574b469c862685f5e6b5c8.jpeg&refer=http%3A%2F%2F5b0988e595225.cdn.sohucs.jpg，AssetEntity的width和height为0

请提供一个**最小化的demo**用于复现，而不要提供**整个项目或者不完整的页面**，否则我们有权拒绝你的请求。

Steps to reproduce the behavior (描述复现步骤):
1.选择一张图片，返回的AssetEntity的width，height是640,1126
2.修改图片名字F5b0988e595225.cdn.sohucs.com%2Fimages%2F20170913%2F3788a2c806574b469c862685f5e6b5c8.jpeg&refer=http%3A%2F%2F5b0988e595225.cdn.sohucs.jpg
3.选择图片
4.返回的AssetEntity的width，height都是0

**Expected behavior (期望行为)**
正常返回width，height

**Screenshots (If contains) (是否有截图可以提供)**
![image](https://user-images.githubusercontent.com/18067025/126029068-a1272680-ce81-46c6-b6f5-2b82216e7566.png)
![image](https://user-images.githubusercontent.com/18067025/126029126-312e53fa-4bde-44c6-a449-a52ff6304d33.png)

**Device information (设备信息)**
 - Device: [e.g. 红米k40]
 - OS: [e.g. Android11]
 - Package Version: [e.g. 5.5.3+1]
 - Flutter Version: [e.g. v2.2.2]

**Additional context (附加信息)**
Add any other context about the problem here. 在此提供更多的内容。

**Comment by AlexV525** [comment]
说明中提供的文件名，与你截图中的文件名不符，且使用说明中的文件名测试后，未复现问题。

![image](https://user-images.githubusercontent.com/15884415/126098373-778d37e1-5e99-46d8-8f38-afd9a6becd2b.png)

**Comment by AlexV525** [comment]
* 如果原文件是 jpeg，但修改为 jpg 却无法读取信息，请在设置时保留原有的后缀名称再进行测试；
* 如果原文件和新文件均为同样的后缀，请提供原图并核对你提供的信息。

**Comment by AlexV525** [comment]
再下次验证前，执行 `flutter pub upgrade` 将所有依赖升级到最新，特别确认 `photo_manager` 升级到 `1.2.6+1`。
