### ISSUE TITLE
[BUG] filterOption with createTimeCond is ignored

### ISSUE THREAD

**Issue by ekeydar** [fluttercandies/flutter_wechat_assets_picker#180]
**Describe the bug (描述)**
A clear and concise description of what the bug is. 请用精炼的语句准确描述你遇到的BUG。

I am adding condition for the pickAssets with createTimeCond, this condition is ignored.
```
await AssetPicker.pickAssets(
          context,
          maxAssets: 9,
          textDelegate: HebrewTextDelegate(),
          //selectedAssets: assets,
          filterOptions: FilterOptionGroup(createTimeCond: DateTimeCond(
            min: DateTime.now().subtract(Duration(days: 1)),
            max: DateTime.now()
          )),
          requestType: RequestType.image,
);
```

**How to reproduce (如何复现)**
Please **provide a minimum demo** rather than **a full project or a incomplete pages**. Otherwise we have rights to reject your request.

请提供一个**最小化的demo**用于复现，而不要提供**整个项目或者不完整的页面**，否则我们有权拒绝你的请求。

Steps to reproduce the behavior (描述复现步骤):

Just run the pickAssets example, and see that you see all photos in the gallery instead of last 24 hours
```
await AssetPicker.pickAssets(
          context,
          maxAssets: 9,
          textDelegate: HebrewTextDelegate(),
          //selectedAssets: assets,
          filterOptions: FilterOptionGroup(createTimeCond: DateTimeCond(
            min: DateTime.now().subtract(Duration(days: 1)),
            max: DateTime.now()
          )),
          requestType: RequestType.image,
);
```

**Expected behavior (期望行为)**

**Screenshots (If contains) (是否有截图可以提供)**

**Device information (设备信息)**
 - Device: Samsung A71
 - OS: Android 11
 - Package Version: 5.5.8
 - Flutter Version: 2.2.3

**Additional context (附加信息)**
Add any other context about the problem here. 在此提供更多的内容。

Looking at the code, it seems the the source of the problem is in https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/469ff71fbd79f1972a5f76e38a98754ce1e83560/lib/src/provider/asset_picker_provider.dart#L299
The merge merges only the options for the image, video, audio, but does not take into account the time conditions.
It seems that after the merge, you need to update the other conditions, if applicable.
Thanks

**Comment by AlexV525** [comment]
Run `flutter pub upgrade` to upgrade the `photo_manager` to at least `1.2.7` version.
