### ISSUE TITLE
[BUG] Error while picking image, Another permission request is still ongoing.

### ISSUE THREAD

**Issue by deva666** [fluttercandies/flutter_wechat_assets_picker#181]
**Describe the bug (描述)**
Exception while picking an Asset. Stack trace
```
E/flutter (13533): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(PERMISSION_REQUESTING, Another permission request is still ongoing. Please request after the existing one is done., null, null)
E/flutter (13533): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:597
E/flutter (13533): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:156
E/flutter (13533): <asynchronous suspension>
E/flutter (13533): #2      Plugin.getAllGalleryList
package:photo_manager/src/plugin.dart:26
E/flutter (13533): <asynchronous suspension>
E/flutter (13533): #3      DefaultAssetPickerProvider.getAssetPathList
package:wechat_assets_picker/…/provider/asset_picker_provider.dart:302
E/flutter (13533): <asynchronous suspension>
E/flutter (13533): #4      new DefaultAssetPickerProvider.<anonymous closure>
package:wechat_assets_picker/…/provider/asset_picker_provider.dart:260
E/flutter (13533): <asynchronous suspension>
```

**How to reproduce (如何复现)**
- Run the example project.
- Click Image picker (Only pick image from device)
- Permission dialog pops up
- Allow permission
- Crash happens

请提供一个**最小化的demo**用于复现，而不要提供**整个项目或者不完整的页面**，否则我们有权拒绝你的请求。

Steps to reproduce the behavior (描述复现步骤):
- Run the example project.
- Click Image picker (Only pick image from device)
- Permission dialog pops up
- Allow permission
- Crash happens

**Expected behavior (期望行为)**
A crash should not happen

**Screenshots (If contains) (是否有截图可以提供)**
-

**Device information (设备信息)**
 - Device: OnePlus 7 PRO
 - OS: Android 11
 - Package Version: 
 - Flutter Version: Flutter (Channel master, 2.4.0-5.0.pre.85)

**Additional context (附加信息)**

**Comment by AlexV525** [comment]
See https://github.com/CaiJingLong/flutter_photo_manager/issues/563 .
