### ISSUE TITLE
请问怎么在选择窗口的第一格加入wechat_camera_picker的格子

### ISSUE THREAD

**Issue by superwei629** [fluttercandies/flutter_wechat_assets_picker#182]
**Version information (版本信息)**
 - Device: *e.g. iPhone6*
 - OS: *e.g. iOS 13.4*
 - Package Version: *e.g. v2.1.0*
 - Flutter Version: *e.g. v1.17.1*

**Is your feature request related to a problem?  (功能是否与已有问题关联)**
无

**Describe the solution you'd like (描述你期望的解决方案)**
给出一个例子

**Describe alternatives you've considered (其他解决方案或疑虑)**
无

**Additional context (附加内容)**
感谢您的制作和耐心解答

**Comment by AlexV525** [comment]
#28
