### ISSUE TITLE
[Feature] Filter out corrupted images

### ISSUE THREAD

**Issue by ishomam** [fluttercandies/flutter_wechat_assets_picker#186]
It would be nice if we have the option to filter out corrupted images like these (hide them for the user). They're causing crashes when one is not aware of them.
![image](https://user-images.githubusercontent.com/39214874/127534442-90802470-e860-4075-b99c-a3665d3df404.png)

In my case, I was getting "Path not found exception" for these two images.

**Comment by AlexV525** [comment]
We can't be aware of a broken asset until it gets loaded.
