### ISSUE TITLE
[BUG] Usage of assets_picker with CupertinoTabScaffold

### ISSUE THREAD

**Issue by SchnMar** [fluttercandies/flutter_wechat_assets_picker#19]
**Describe the bug (描述)**
I'm trying to use the asset picker with a CupertinoTabScaffold. When displaying the asset picker the CupertinoTabBar is still displayed on top the asset picker and the buttons are not reachable. 

**How to reproduce (如何复现)** 
I can provide example code if needed, please let me know.

**Expected behavior (期望行为)**

That the assetPicker is a fullscreen dialogue and displayed above the CupertinoTabBar.

A way to pass an argument on what type of dialogue should be displayed or that the asset picker is displayed on top of Cupertino Tab Bar.

**Screenshots (If contains) (是否有截图可以提供)**

<a href="https://ibb.co/SXvMSJV"><img src="https://i.ibb.co/4ZNXkJ4/Simulator-Screen-Shot-i-Phone-11-Pro-2020-05-25-at-21-55-03.png" alt="Simulator-Screen-Shot-i-Phone-11-Pro-2020-05-25-at-21-55-03" border="0"></a>

**Device information (设备信息)**
 - Device: Simulator iPhone 11 pro
 - OS: iOS 13.5
 - Package Version: 2.0.1
 - Flutter Version: 1.17.1

Thank you very much for your help!

**Comment by SchnMar** [comment]
I fixed it locally by adding a parameter to pickAssets. I copied the method, maybe you can consider adding this to the core:

`static Future<List<AssetEntity>> pickAssets(
    BuildContext context, {
    Key key,
    int maxAssets = 9,
    int pageSize = 320,
    int pathThumbSize = 200,
    int gridCount = 4,
    bool rootNaviagtor = false,
    RequestType requestType = RequestType.image,
    List<AssetEntity> selectedAssets,
    Color themeColor = C.themeColor,
    ThemeData pickerTheme,
    TextDelegate textDelegate,
    Curve routeCurve = Curves.easeIn,
    Duration routeDuration = const Duration(milliseconds: 300),
  }) async {
    if (maxAssets == null || maxAssets < 1) {
      throw ArgumentError('maxAssets must be greater than 1.');
    }
    if (pageSize != null && pageSize % gridCount != 0) {
      throw ArgumentError('pageSize must be a multiple of gridCount.');
    }
    if (pickerTheme != null && themeColor != null) {
      throw ArgumentError(
          'Theme and theme color cannot be set at the same time.');
    }
    try {
      final bool isPermissionGranted = await PhotoManager.requestPermission();
      if (isPermissionGranted) {
        final AssetPickerProvider provider = AssetPickerProvider(
          maxAssets: maxAssets,
          pageSize: pageSize,
          pathThumbSize: pathThumbSize,
          selectedAssets: selectedAssets,
          requestType: requestType,
          routeDuration: routeDuration,
        );
        final Widget picker = AssetPicker(
          key: key,
          provider: provider,
          gridCount: gridCount,
          textDelegate: textDelegate,
          themeColor: themeColor,
          pickerTheme: pickerTheme,
        );
        final List<AssetEntity> result =
            await Navigator.of(context, rootNavigator: rootNaviagtor).push<List<AssetEntity>>(

          SlidePageTransitionBuilder<List<AssetEntity>>(
            builder: picker,
            transitionCurve: routeCurve,
            transitionDuration: routeDuration,
          ),
        );
        return result;
      } else {
        return null;
      }
    } catch (e) {
      realDebugPrint('Error when calling assets picker: $e');
      return null;
    }
  }`

**Comment by AlexVincent525** [comment]
> I can provide example code if needed, please let me know.

Please share your demo because I'm not able to figure out what kind of effect that you want to achieve.

> If you like this solution let me know and I will try another pull request ;)

And what's the difference after this change? Can you add a screenshot about it? Thanks.

**Comment by AlexVincent525** [comment]
Done with investigation. Because `CupertinoTabView` has its own navigator, so push in it won't take effect on the TabBar outside (as its parent). I prefer something like this:
![image](https://user-images.githubusercontent.com/15884415/82852685-253c9880-9f36-11ea-8fb6-77fc59dd705f.png)
I'll wait for your pull request. @SchnMar

**Comment by SchnMar** [comment]
Hey Alex,

thank you for your quick response.

I research the topic of rootNavigator and couldn't find a reason for not setting it to true globally. Working on the pull requeust now. 

Thank you!

**Comment by AlexVincent525** [comment]
> I research the topic of rootNavigator and couldn't find a reason for not setting it to true globally. Working on the pull requeust now.

Also provide the demo or a unit test to verify this works.

**Comment by SchnMar** [comment]
Didn't really understand how you wanted me to provide the demo. So please find some demo code here:
```
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Hello',
      home: CupertinoTabScaffold(
        tabBar: CupertinoTabBar(
          items: <BottomNavigationBarItem>[
            BottomNavigationBarItem(
              icon: Icon(Icons.home),
              title: Text('Home'),
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.person),
              title: Text('Account'),
            ),
          ],
        ),
        tabBuilder: (BuildContext context, int index) {
          return CupertinoTabView(
            builder: (BuildContext context) {
              return CupertinoPageScaffold(
                navigationBar: CupertinoNavigationBar(
                  middle: Text('Page 1 of tab $index'),
                ),
                child: Center(
                  child: CupertinoButton(
                      child: Text('display asset picker'),
                      onPressed: () async {
                        final List<AssetEntity> assets =
                            await AssetPicker.pickAssets(context);
                      }),
                ),
              );
            },
          );
        },
      ),
    );
  }
}

```

**Comment by AlexVincent525** [comment]
This would be hold off for a few days because there's another issue pending for fixes.
