### ISSUE TITLE
Change OK Button Text

### ISSUE THREAD

**Issue by didiosn** [fluttercandies/flutter_wechat_assets_picker#191]
Hi, Big thanks for this package. 

I've read the document, i've read the "read before create". 

How can I just change the OK button when you've selected images ? only that.

Thank You

![image](https://user-images.githubusercontent.com/15895051/129558966-9c46cfbb-e3bd-4457-a406-cc14e123d79e.png)

**Comment by didiosn** [comment]
Found. How its done : 

You have to create a new class extends from AssetsPickerTextDelegate like this (french example) : 

`
class FrenchTextDelegate extends AssetsPickerTextDelegate {
  @override
  String get confirm => 'OK';

  @override
  String get cancel => 'Annuler';

  @override
  String get edit => 'Modifier';

  @override
  String get gifIndicator => 'GIF';

  @override
  String get heicNotSupported => 'Type de fichier non supporté';

  @override
  String get loadFailed => 'Echec du chargement';

  @override
  String get original => 'Original';

  @override
  String get preview => 'Aperçu';

  @override
  String get select => 'Choisir';

  @override
  String get unSupportedAssetType => 'Type de fichier non supporté.';

  @override
  String get unableToAccessAll => "Impossible d'accéder au fichier de l'appareil"';

  @override
  String get viewingLimitedAssetsTip =>
      'Only view assets and albums accessible to app.';

  @override
  String get changeAccessibleLimitedAssets =>
      'Update limited access assets list';

  @override
  String get accessAllTip => 'App can only access some assets on the device. '
      'Go to system settings and allow app to access all assets on the device.';

  @override
  String get goToSystemSettings => 'Go to system settings';

  @override
  String get accessLimitedAssets => 'Continue with limited access';

  @override
  String get accessiblePathName => 'Accessible assets';
}
`

Et pour l'utiliser : 

`
final List<AssetEntity> assets = await AssetPicker.pickAssets(
      context,
      ...
      textDelegate: FrenchTextDelegate(),
  );
`

**Comment by AlexV525** [comment]
Glad that you found your solution. I was about to update the example for how to use a text delegate. Do you in any interest to submit this delegate into the package?

**Comment by didiosn** [comment]
Why not ? let me finish the translation and submit in comment.

**Comment by didiosn** [comment]
FrenchTextDelegate : 

```
class FrenchTextDelegate extends AssetsPickerTextDelegate {
  @override
  String get confirm => 'OK';

  @override
  String get cancel => 'Annuler';

  @override
  String get edit => 'Modifier';

  @override
  String get gifIndicator => 'GIF';

  @override
  String get heicNotSupported => 'Type de fichier non supporté';

  @override
  String get loadFailed => 'Echec du chargement';

  @override
  String get original => 'Original';

  @override
  String get preview => 'Aperçu';

  @override
  String get select => 'Choisir';

  @override
  String get unSupportedAssetType => 'Type de fichier non supporté';

  @override
  String get unableToAccessAll =>
      "Impossible d'accéder aux médias de votre appareil";

  @override
  String get viewingLimitedAssetsTip =>
      'Affichage des médias et albums limité ';

  @override
  String get changeAccessibleLimitedAssets =>
      "Modifier l'accès limité aux médias";

  @override
  String get accessAllTip =>
      "L'application ne peut accéder qu'à certains medias. Allez dans les paramètres système et autoriser l'application à accéder à tous les medias sur l'appareil";

  @override
  String get goToSystemSettings => 'Allez dans les paramètres système';

  @override
  String get accessLimitedAssets => 'Continuer avec un accès limité';

  @override
  String get accessiblePathName => 'Medias accessible';
}
```

**Comment by AlexV525** [comment]
Thanks for the delegate. We also have [another PR](#190) that will introduce a new field, can you add that field too?

**Comment by didiosn** [comment]
Comment updated !

**Comment by AlexV525** [comment]
I'll put it into the next release. Thanks again!

**Comment by AlexV525** [comment]
@all-contributors Add @didiosn for translations.
