### ISSUE TITLE
[BUG] Error with something[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'version' was called on null.

### ISSUE THREAD

**Issue by wangyan-png** [fluttercandies/flutter_wechat_assets_picker#194]
**Describe the bug (描述)**
A clear and concise description of what the bug is. 请用精炼的语句准确描述你遇到的BUG。
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'version' was called on null.
**How to reproduce (如何复现)**
Please **provide a minimum demo** rather than **a full project or a incomplete pages**. Otherwise we have rights to reject your request.
  wechat_assets_picker: ^4.2.2
  wechat_camera_picker: ^2.0.0-dev.1
点击拍照图标拍照完成后点击确认不返回上一页，控制台报标题错误

请提供一个**最小化的demo**用于复现，而不要提供**整个项目或者不完整的页面**，否则我们有权拒绝你的请求。

Steps to reproduce the behavior (描述复现步骤):

**Expected behavior (期望行为)**
返回上一页拿到拍照照片
**Screenshots (If contains) (是否有截图可以提供)**
![image](https://user-images.githubusercontent.com/57902728/130547090-db79cdb6-c1c9-437b-bea5-0ee454f4bfbd.png)

**Device information (设备信息)**
 - Device: [e.g. iPhone6]  android 11
 - Package Version: [e.g. 22]  wechat_assets_picker: ^4.2.2
  wechat_camera_picker: ^2.0.0-dev.1
 - Flutter Version: [e.g. v1.17.1]  Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git

**Additional context (附加信息)**
Add any other context about the problem here. 在此提供更多的内容。

**Comment by AlexV525** [comment]
旧版本无法维护，请使用最新版本。
