### ISSUE TITLE
[BUG] 可访问资源无法刷新（Accessible resources cannot be refreshed）

### ISSUE THREAD

**Issue by persilee** [fluttercandies/flutter_wechat_assets_picker#198]
**Describe the bug (描述)**
On iOS 14.5 (iPhone 12 Pro), when using the ‘Selected Photos’ access permission;
For the video, I selected 3 pictures, but there is still 1 picture in the list of ‘accessible resources’, and the number (1) behind ‘accessible resources’ has not changed.

在iOS 14.5（iPhone 12 Pro）上，使用 ‘Selected Photos’ 访问权限时；
如视频，我选择了3张图片，但是 ‘可访问的资源’ 列表里还是1张图片，而且  ‘可访问的资源’ 后面的（1）数字也没有改变。

**How to reproduce (如何复现)**
dome is the example you provided

dome 就是你们提供的 example

Steps to reproduce the behavior (描述复现步骤):

1. Click ‘Common picker’
2. Select ‘Continue to access some resources’
3. Click "Accessible Resources" -> "Set Accessible Resources"
4. Add the required picture, click ‘Done’

1. 点击 ‘Common picker’ 
2. 选择 ’继续访问部分资源‘
3. 点击 ’可访问的资源‘ -> ’设置可访问的资源‘ 
4. 添加需要的图片，点击 ’Done‘

**Expected behavior (期望行为)**
The previous picture is still displayed, the newly added picture will not be displayed

还是显示之前的图片，新增图片并不会显示

**Screenshots (If contains) (是否有截图可以提供)**

https://user-images.githubusercontent.com/18243510/132619780-af8e9eba-6841-408d-aee9-9d8d83e7bcf2.mp4

**Device information (设备信息)**
 - Device: [iPhone 12 Pro]
 - OS: [iOS 14.5]
 - Package Version: [6.1.1]
 - Flutter Version: [2.2.0]

**Comment by AlexV525** [comment]
This also requires an update from the `photo_manager`.

**Comment by persilee** [comment]
> This also requires an update from the `photo_manager`.

Thank you for your answer. I see that you are also one of the Contributors of photo_manager. When will photo_manager be updated, because our APP needs to fix this problem urgently.

**Comment by AlexV525** [comment]
I've labeled that this issue should be solved *today*, so it would be solved today, within the schedule.

**Comment by AlexV525** [comment]
Published with [6.1.2](https://github.com/fluttercandies/flutter_wechat_assets_picker/releases/tag/v6.1.2) .

**Comment by persilee** [comment]
Thank you very much. Star has been given to you

> Published with [6.1.2](https://github.com/fluttercandies/flutter_wechat_assets_picker/releases/tag/v6.1.2) .
