### ISSUE TITLE
添加与微信朋友圈完全相同的模式

### ISSUE THREAD

**Issue by tangdehao** [fluttercandies/flutter_wechat_assets_picker#2]
现在照片和视频可以混合显示，但是有时候会有一个需求选择了图片就不能选择视频，选择视频就不能选择图片，类似微信发朋友圈的时候选择照片 视频就灰掉了无法选择那样

**Comment by AlexVincent525** [comment]
我调研了一下微信的朋友圈选择资源，一共有两种情况：
* 选择视频后，无法再进行选择
* 选择图片后，不出现视频
完整实现第一种，目前暂时还无法达成，因为对于所有资源来说都可以多选，后面可以加一个完全匹配微信的模式，但是选择视频确认后不能再选图片是由你自己控制的，屏蔽入口即可。
完整实现第二种是可以的，当你已经选择了图片后，下一次请求参数为图片即可。

如果有补充，欢迎继续讨论。

**Comment by zhangruiyu** [comment]
同希望加这个功能  爱了 爱了,现在就去接入我自己项目上

**Comment by zhangruiyu** [comment]
希望老哥 Audio asset support能优先级高点  0-0 目前视频上都没啥好用的 全指望大哥你了

**Comment by AlexVincent525** [comment]
> 希望老哥 Audio asset support能优先级高点 0-0 目前视频上都没啥好用的 全指望大哥你了

视频已经支持了，音频因为没有对照品，需要考虑下怎么设计，目前这周还有别的事，会暂时往后放放。

**Comment by 237713070** [comment]
我就是来看看，点个赞，嘿嘿

**Comment by AlexVincent525** [comment]
已在2.0.0中支持。
