### ISSUE TITLE
[BUG] 警告: 无法找到类型 'EnsuresNonNull' 的注释方法 'value()'

### ISSUE THREAD

**Issue by birdidi** [fluttercandies/flutter_wechat_assets_picker#200]
**Describe the bug**
`\jetified-exoplayer-common-2.14.1-api.jar(com/google/android/exoplayer2/util/Util.class): 警告: 无法找到类型 'EnsuresNonNull' 的注释方法 'value()': 找不到org.checkerframework.chec
ker.nullness.qual.EnsuresNonNull的类文件
\jetified-exoplayer-common-2.14.1-api.jar(com/google/android/exoplayer2/util/Util.class): 警告: 无法找到类型 'EnsuresNonNull' 的注释方法 'value()'
错误: 发现警告, 但指定了 -Werror
1 个错误
2 个警告`

**Comment by AlexV525** [comment]
#28 .
