### ISSUE TITLE
How we can change language in simple usage ?

### ISSUE THREAD

**Issue by TouseefAQ** [fluttercandies/flutter_wechat_assets_picker#201]
I have integrated simple wechat multiple image picker and also set my local in my material app but the plugin show chinese lan but i am unable to change it. Any lead would be appriciated.

**Comment by hdeyana** [comment]
Change the textDelegate or make one,


Here if you want to change to english

` 
final List<AssetEntity>? assets = await AssetPicker.pickAssets(
          context,
          maxAssets: 1,
          textDelegate: EnglishTextDelegate(),
        );
`

**Comment by TouseefAQ** [comment]
Thank You !!
