### ISSUE TITLE
[Feature] Determine when to revert the assets grid

### ISSUE THREAD

**Issue by jayeshindianic** [fluttercandies/flutter_wechat_assets_picker#202]
**Version information**
 - Device: iPhone 12 Pro max
 - OS:  iOS 14.4
 - Package Version: wechat_assets_picker: ^6.1.2 ,  wechat_camera_picker: ^2.4.2
 - Flutter Version: v2.5.0

**Is your feature request related to a problem?**
i want to set icon of capture image from camera in first item or row.
you can see i have attached one screen shot, camera icon is show in last item.

**Additional context**
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-09-22 at 11 45 46](https://user-images.githubusercontent.com/79701614/134292656-2abcb3af-e63d-4a24-a822-0148442ae71e.png)

**Comment by jayeshindianic** [comment]
```
final List<AssetEntity> resultList = await AssetPicker.pickAssets(
        context,
        textDelegate: EnglishTextDelegate(),
        specialItemPosition: SpecialItemPosition.prepend,
        requestType: RequestType.image,
        specialItemBuilder: (BuildContext context) {
          return GestureDetector(
            behavior: HitTestBehavior.opaque,
            onTap: () async {
              final AssetEntity result = await CameraPicker.pickFromCamera(
                context,
                textDelegate: EnglishCameraPickerTextDelegate(),
              );
              if (result != null) {
                final AssetPicker<AssetEntity, AssetPathEntity> picker =
                    context.findAncestorWidgetOfExactType();
                if (picker != null) {
                  final DefaultAssetPickerProvider p =
                      picker.builder.provider as DefaultAssetPickerProvider;
                  await p.currentPathEntity.refreshPathProperties();
                  p.switchPath(p.currentPathEntity);
                  p.selectAsset(result);
                }
              }
            },
            child: const Center(
              child: Icon(Icons.camera_enhance, size: 42.0),
            ),
          );
        },
      );
```

**Comment by AlexV525** [comment]
This is by design, since the assets grid is reversed in the iOS Gallery app and also in the WeChat.

**Comment by jayeshindianic** [comment]
@AlexV525  any other options to make camera option in first item for ios

**Comment by AlexV525** [comment]
> @AlexV525 any other options to make camera option in first item for ios

We do have other way to make reverse it back, which is extended the `DefaultAssetPickerBuilderDelegate`, and treat the grid same as Android.

https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/19e6058fb700747204d2cc11174133e34b2acc41/lib/src/delegates/asset_picker_builder_delegate.dart#L939

**Comment by AlexV525** [comment]
You can use `shouldRevertGrid` when picking after you upgraded to v6.2.0 .
