### ISSUE TITLE
[BUG] Error with Capture image from camera

### ISSUE THREAD

**Issue by jayeshindianic** [fluttercandies/flutter_wechat_assets_picker#203]
**Version information**

Device: iPhone 12 Pro max or any android device also
OS: iOS 14.4 and android os
Package Version: wechat_assets_picker: ^6.1.2 , wechat_camera_picker: ^2.4.2
Flutter Version: v2.5.0

**How to reproduce**
i have test your example, when i capture image from camera and come back with stay method, you can see in my attached screenshot image are show in list, but its not tick-mark (selected) but image counts are show 2 image is selected.

just run your example select cameraAndStay , when you capture image from camera image will show in list also count is increment but image tickmark is nothing show any selection.

**Screenshots (If contains)**
![134300410-63d672b3-a7b1-44ea-9d14-9bfe08c11c53](https://user-images.githubusercontent.com/79701614/134455368-267e2f28-ec06-412c-accd-fd99f89829ac.png)

**Comment by AlexV525** [comment]
Run `flutter pub upgrade` and make sure the `photo_manager` is resolved as `1.3.3` then try again.

**Comment by jayeshindianic** [comment]
Thank you @AlexV525,
now its working fine.
