### ISSUE TITLE
[Feature] Default light theme

### ISSUE THREAD

**Issue by Fnalsk** [fluttercandies/flutter_wechat_assets_picker#206]
**Version information**
 - Device: n/a
 - OS: n/a
 - Package Version: v6.2.1
 - Flutter Version: v2.5.1

**Is your feature request related to a problem?**

The default theme for this package follows the wechat dark theme. It would be nice if there was also an option to use the default light theme for use with light theme apps.

**Describe the solution you'd like**

Add a default light theme to the package, where light/dark themes can be toggled using an argument to `AssetPicker.themeData()`. The visuals should look the same as wechat when used in light mode.

**Comment by AlexV525** [comment]
WeChat does not use the light theme when picking even if you use light theme of WeChat. If we create it from zero, it might be a little bit of weird.
