### ISSUE TITLE
Flutter2.2.3运行报错

### ISSUE THREAD

**Issue by 891806797** [fluttercandies/flutter_wechat_assets_picker#208]
../../../flutter223/.pub-cache/hosted/pub.flutter-io.cn/extended_image-5.1.0/lib/src/gesture_detector/gesture_detector.dart:302:9: Error: Type 'GestureLongPressDownCallback' not found.
      final GestureLongPressDownCallback? onLongPressDown;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ../../../flutter223/.pub-cache/hosted/pub.flutter-io.cn/extended_image-5.1.0/lib/src/gesture_detector/gesture_detector.dart:318:9: Error: Type 'GestureLongPressCancelCallback' not found.
      final GestureLongPressCancelCallback? onLongPressCancel;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ../../../flutter223/.pub-cache/hosted/pub.flutter-io.cn/extended_image-5.1.0/lib/src/gesture_detector/gesture_detector.dart:409:9: Error: Type 'GestureLongPressDownCallback' not found.
      final GestureLongPressDownCallback? onSecondaryLongPressDown;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ../../../flutter223/.pub-cache/hosted/pub.flutter-io.cn/extended_image-5.1.0/lib/src/gesture_detector/gesture_detector.dart:425:9: Error: Type 'GestureLongPressCancelCallback' not found.
      final GestureLongPressCancelCallback? onSecondaryLongPressCancel;

**Comment by AlexV525** [comment]
FYI @zmtzawqlp
