### ISSUE TITLE
[BUG] ios icloud

### ISSUE THREAD

**Issue by qq326646683** [fluttercandies/flutter_wechat_assets_picker#21]
**Describe the bug (描述)**
ios icloud视频无法播放，图片显示慢

**How to reproduce (如何复现)**
手机里有大量图片，有未下载的icloud视频

**Expected behavior (期望行为)**
正常显示

**Device information (设备信息)**
 - Device: [ iPhone xs max]
 - OS: [e.g. iOS13.4.1]
 - Package Version: [lasted]
 - Flutter Version: [ v1.17.1]

**Comment by AlexV525** [comment]
Closing with won't fix from the contributor.
