### ISSUE TITLE
[Accessibility] Inconvenience when toggling accessibility features with this package

### ISSUE THREAD

**Issue by luomo-pro** [fluttercandies/flutter_wechat_assets_picker#217]
I am a blind developer.
I found that there are a lot of accessibility problems in the image selection interface, which greatly affects the use of the disabled.
Talk back can be opened on Android phones. For details, see:
https://medium.com/flutter-community/a-deep-dive-into-flutters-accessibility-widgets-eb0ef9455bc
Because I can't speak English, I use translation, so the description may not be very accurate. If you have any questions later, please feel free to ask me.
The accessibility of pictures selected by wechat itself is very good. You can compare it.
Now I find the following problems:
1. Select the picture interface, touch the return button, and there is no label "return".
2. Each asset item has no label.
When selecting pictures in wechat, the label of each picture is "picture X, Y", "X" is the serial number of the picture, and "Y" is the modification time of the picture.
If it is a video, the label is "video X, Z, Y", in which there is an additional "Z", which is the duration of the video.
3. The selection check box of each asset item has no label and selected status.
4. The picture preview interface, the picture in the middle and the return button in the upper left corner have no labels.
5. In the picture preview interface, the text of the check box and the specific check box are the two focuses, and they should be merged.
You can open talk back to use these questions.
You can compare it with wechat's own, and you can find many of your accessibility problems.
About how to add labels and set the selected status, you can see:
https://flutter.dev/docs/development/accessibility-and-localization/accessibility
I hope these problems can be repaired as soon as possible. It is very important for blind users. Thank you very much!
The version I use is:
  wechat_assets_picker: ^6.2.0

**Comment by AlexV525** [comment]
Good to hear from you about accessibility requirements and sorry for the inconvenience that this package has brought. That's something that I didn't consider before.

However, I'm lacking time until December since I'm preparing some other stuff that makes me have less time to maintain this package. Once I got more time I'll enrich the accessibility as soon as possible.

Thank you for your feedback and I guarantee you this should be and will be resolved.

cc @yanivshaked if you're interested in this feature.

**Comment by luomo-pro** [comment]
@AlexV525
thank you very much!
I know a lot about accessibility.
You can contact me if you encounter any problems when you do accessibility
My email address is:
lmdbk@qq.com
Thank you again!

**Comment by AlexV525** [comment]
> My email address is: [lmdbk@qq.com](mailto:lmdbk@qq.com)

I found that maybe you're a Chinese developer too, so if that's true, please add me through QQ: 505646850, and we can discuss this.

**Comment by AlexV525** [comment]
The full semantics support has been landed. Special thanks to @luomo-pro!
