### ISSUE TITLE
[Feature] Request a feature with something

### ISSUE THREAD

**Issue by wangyan-png** [fluttercandies/flutter_wechat_assets_picker#219]
**Version information**
 - Device: *e.g. iPhone X* 
 - OS: *e.g. iOS15.0
 - Package Version: *e.g. v6.1.2*
 - Flutter Version: *e.g. v2.3.0*

**Is your feature request related to a problem?**

当直接从相册分享图片来到APP时  assets 无法回显
**Describe the solution you'd like**

希望提供接收从其他入口传过来的图片并回显，谢谢（若此包已提供该功能望告知如何使用）
**Describe alternatives you've considered**

**Additional context**

**Comment by AlexV525** [comment]
#28
