### ISSUE TITLE
[BUG] Error: The argument type 'File/*1*/' can't be assigned to the parameter type 'File/*2*/'.

### ISSUE THREAD

**Issue by perdonare** [fluttercandies/flutter_wechat_assets_picker#227]
**Describe the bug**
running error in web mode without any code change

` 
This application is not configured to build on the web.
To add web support to a project, run  flutter create . .
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
lib/customs/pickers/directory_file_asset_picker.dart:215:23: Error: The argument type 'File/*1*/' can't be assigned to the parameter type 'File/*2*/'.
 - 'File/*1*/' is from 'package:extended_image_library/src/_platform_web.dart' ('../../../../../soft/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.0/lib/src/_platform_web.dart').
 - 'File/*2*/' is from 'dart:io'.
    return Image.file(asset, fit: BoxFit.cover);
                      ^
lib/customs/pickers/directory_file_asset_picker.dart:324:49: Error: A value of type 'List<File>' can't be assigned to a variable of type 'List<FileSystemEntity>'.
 - 'List' is from 'dart:core'.
 - 'File' is from 'package:extended_image_library/src/_platform_web.dart' ('../../../../../soft/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.0/lib/src/_platform_web.dart').
 - 'FileSystemEntity' is from 'dart:io'.
        pathEntity.listSync().whereType<File>().toList();
                                                ^
lib/customs/pickers/directory_file_asset_picker.dart:329:27: Error: The argument type 'FileSystemEntity' can't be assigned to the parameter type 'File'.
 - 'FileSystemEntity' is from 'dart:io'.
 - 'File' is from 'package:extended_image_library/src/_platform_web.dart' ('../../../../../soft/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.0/lib/src/_platform_web.dart').
        currentAssets.add(entity);
                          ^
lib/customs/pickers/directory_file_asset_picker.dart:339:49: Error: A value of type 'List<File>' can't be assigned to a variable of type 'List<FileSystemEntity>'.
 - 'List' is from 'dart:core'.
 - 'File' is from 'package:extended_image_library/src/_platform_web.dart' ('../../../../../soft/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.0/lib/src/_platform_web.dart').
 - 'FileSystemEntity' is from 'dart:io'.
        pathEntity.listSync().whereType<File>().toList();
                                                ^
lib/customs/pickers/directory_file_asset_picker.dart:344:45: Error: The method 'readAsBytes' isn't defined for the class 'FileSystemEntity'.
 - 'FileSystemEntity' is from 'dart:io'.
Try correcting the name to the name of an existing method, or defining a method named 'readAsBytes'.
        final Uint8List data = await entity.readAsBytes();
                                            ^^^^^^^^^^^
lib/customs/pickers/directory_file_asset_picker.dart:10:1: Error: 'FileImage' is imported from both 'package:extended_image_library/src/_platform_web.dart' and 'package:flutter/src/painting/image_provider.dart'.
import 'package:flutter/material.dart';
^^^^^^^^^
lib/customs/pickers/directory_file_asset_picker.dart:747:37: Error: 'FileImage' is imported from both 'package:extended_image_library/src/_platform_web.dart' and 'package:flutter/src/painting/image_provider.dart'.
    final FileImage imageProvider = FileImage(asset);
                                    ^^^^^^^^^
Failed to compile application. 
`

**How to reproduce**
dart version:2.15.1
flutter version: 2.8.1

just start this app for web chrome

**Version information**

- Device: [macOS]
- OS: [11.5.1]
- Package Version(dart): [2.15.1]
- Flutter Version: [2.8.1]

**Comment by AlexV525** [comment]
You're running this on the Web, which is unsupported by this package.

**Comment by perdonare** [comment]
> You're running this on the Web, which is unsupported by this package.

OK, Tks
