### ISSUE TITLE
[BUG] Error with something

### ISSUE THREAD

**Issue by DavidMGT** [fluttercandies/flutter_wechat_assets_picker#228]
**Describe the bug**

返回键不能隐藏对话框
**How to reproduce**

 1.打开选择图库
2.按返回键 。选择图库页面没有消失
4. Error occurred.

**Expected behavior**

希望返回键可以消失对话框
**Screenshots (If contains)**

**Version information**

- Device: [e.g. iPhone X]
- OS: [e.g. iOS 14.7.1]
- Package Version: [e.g. 2.4.1]
- Flutter Version: [e.g. v2.5.0]

**Additional context**

**Comment by AlexV525** [comment]
#28. RTFM.
