### ISSUE TITLE
返回键不能退出选择，必须点击顶部的关闭按钮

### ISSUE THREAD

**Issue by DavidMGT** [fluttercandies/flutter_wechat_assets_picker#230]
**Describe the bug**

 返回键不能退出选择，必须点击顶部的关闭按钮

- Device: [e.g. iPhone X] android
- OS: [e.g. iOS 14.7.1]
- Package Version: [e.g. 2.4.1] 
- Flutter Version: [e.g. v2.5.0] 6.0.0

**Additional context**

**Comment by AlexV525** [comment]
#28. If you keep posting content that's not following the instruction, you might get banned from the repo.

**Comment by chjsun** [comment]
@DavidMGT 请问你解决了么，怎么解决的？
