### ISSUE TITLE
[Feature] Update text delegates with semantics fields

### ISSUE THREAD

**Issue by AlexV525** [fluttercandies/flutter_wechat_assets_picker#239]
Since #232, we added the full support for semantics, which added a bunch of fields in text delegates. These fields will be used by the Talkback or the VoiceOver when they're reading grid elements, buttons, paths, etc.

In order to provide convenience when people are using accessibility kits, please help us to update text delegates when you (contributors for localizations) are available. Otherwise, the screen reader will read in Chinese since text delegates will fall back to the default one.

**Please verify updates using Talkback or VoiceOver if possible. Little differences can make a huge impact on people who depend on accessibilities.**

Supported languages with semantics:
- Talkback: https://support.google.com/accessibility/android/answer/11101402)
- VoiceOver: https://support.apple.com/en-us/HT206175

Languages:
- Hebrew @yanivshaked #242
- German @Letalus #243
- Russian @greymag #240 
- Japanese @KosukeSaigusa @paigupai #266
- Arabic @yanivshaked @maxzod #242
- French @didiosn #254

**Comment by yanivshaked** [comment]
PR #242 submitted.
@maxzod appreciate your review on Arabic translation,

**Comment by Letalus** [comment]
PR #243 submitted.
Hope I didnt miss anything important

**Comment by AlexV525** [comment]
If anyone else can help with Japanese and French, that would be great.

**Comment by AlexV525** [comment]
All delegates have been updated, thanks to everyone who contribute to these updates. 🎉
