### ISSUE TITLE
[Feature Request] Preselect Recent in pathEntityList or make it configurable

### ISSUE THREAD

**Issue by SchnMar** [fluttercandies/flutter_wechat_assets_picker#24]
Hey Alex,

this is more of a feature request than a bug. Currently the first item of pathEntityList is selected when the assets_picker is presented. In the simulator this makes sense, but in the real world, the first items are SloMo or Screenshots in my case. Most of the time people like to select recently taken pictures in such an asset picker, so from my point of view a preselection of Recent or a possibility to make it configurable would be great. What do you think? 

Thank you
Marcel

**Comment by AlexVincent525** [comment]
Paths are returned from the system, as the first `AssetPathEntity` will be selected.

https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/e8432b3c373803ebe4af668c01b7dc4d95ef7be1/lib/src/provider/asset_picker_provider.dart#L207

It might be a feature with some platform side migration.

Also /cc @CaiJingLong

**Comment by AlexVincent525** [comment]
Which platform has this scenario?

**Comment by SchnMar** [comment]
This scenario is on iOS. 
I already added this feature on my fork, but the solution isn't perfect.

[https://github.com/SchnMar/flutter_wechat_assets_picker/commit/468747ff14bce16cb3a0c3b9e047cb89e6fdd758](Fork)

**Comment by AlexVincent525** [comment]
https://github.com/SchnMar/flutter_wechat_assets_picker/blob/468747ff14bce16cb3a0c3b9e047cb89e6fdd758/lib/src/provider/asset_picker_provider.dart#L164

This part could serve with another method rather than matching the name, I'll try to implement this tomorrow.

**Comment by AlexVincent525** [comment]
Try this with `2.2.0-dev.1` or ref with `f3313d6`.

**Comment by AlexVincent525** [comment]
There's some issue with the constructor, please add `sortPathDelegate: SortPathDelegate.common` to the static method when using this. I'll fix this in next rc.

**Comment by AlexVincent525** [comment]
Try this with `2.2.0-dev.2` or ref with bed13e9.

**Comment by SchnMar** [comment]
Works great for me! Thank you!
