### ISSUE TITLE
Control video file size？

### ISSUE THREAD

**Issue by DavidMGT** [fluttercandies/flutter_wechat_assets_picker#246]
**Version information**
 - Device: *e.g. iPhone X*
 - OS: *e.g. iOS 14.7.1*
 - Package Version: *e.g. v2.4.1*
 - Flutter Version: *e.g. v2.5.0*

**Is your feature request related to a problem?**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AlexV525** [comment]
#28
