### ISSUE TITLE
[BUG] Unresponsive UI on large screen of devices

### ISSUE THREAD

**Issue by Fnalsk** [fluttercandies/flutter_wechat_assets_picker#253]
**Describe the bug**

Really ugly UI on iPad

**How to reproduce**

1. Open the asset picker on an iPad

**Expected behavior**

The circle on the top right of every square should be smaller. It just looks ugly with the circle being that big.

**Screenshots (If contains)**

<img width="661" alt="Screen Shot 2022-02-15 at 1 46 43 AM" src="https://user-images.githubusercontent.com/76232988/154025515-fbee3354-f5cc-4d43-b847-27c1372bb1c8.png">

**Version information**

- Device: iPad Pro 12.9 inch 5th generation
- OS: iOS 15.2
- Package Version: 6.3.1
- Flutter Version: 2.8.1

**Additional context**

**Comment by AlexV525** [comment]
Wouldn't a larger `gridCount` help?

**Comment by Fnalsk** [comment]
It does, but I still think it shouldn't look that ugly on a gridcount of 3.

Also, with a gridcount of 5, it still looks a little weird - the green check circle is so much bigger than the "1" in the top left of the selected image.

<img width="653" alt="Screen Shot 2022-02-15 at 1 54 29 AM" src="https://user-images.githubusercontent.com/76232988/154026847-556037bc-b52c-4321-94c3-18626db1ea74.png">

**Comment by AlexV525** [comment]
I personally prefer a larger size of the number text in this case.

The root cause of this issue is: https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/3a11fe8300bf3a8691ac909a3a14dc58a99406cd/lib/src/delegates/asset_picker_builder_delegate.dart#L1947

**Comment by Fnalsk** [comment]
I do prefer a larger number as well for the gridcount=5 case, but maybe not so big as to match the check mark circle. I think for this particular case, it would look best if maybe the green circle was 20-25% smaller and the number was enlarged to match.

**Comment by AlexV525** [comment]
![image](https://user-images.githubusercontent.com/15884415/155930495-acac4ee3-623d-4f49-af44-5a0024c0a5d4.png)
![image](https://user-images.githubusercontent.com/15884415/155930530-79e4e6e6-3ef9-4c6a-bce9-8bbc592eb347.png)
