### ISSUE TITLE
[Feature] Allow selecting assets from multiple sources

### ISSUE THREAD

**Issue by Fnalsk** [fluttercandies/flutter_wechat_assets_picker#255]
**Version information**
 - Device: n/a
 - OS: n/a
 - Package Version: 6.3.1
 - Flutter Version: 2.10.1

**Is your feature request related to a problem?**

Currently you can only select assets from your local device. It would be nice if you could also select assets from cloud storage apps like dropbox or iCloud.

**Describe the solution you'd like**

Add ability to select files from any installed cloud storage apps on the device.

**Describe alternatives you've considered**

n/a

**Additional context**

This is probably a big change to be able to implement, so I don't expect to see it completed anytime soon. Just thought I'd create an issue for it because I didn't see one already, and it would be a pretty substantial improvement to the package.

**Comment by AlexV525** [comment]
Picking is not about any installed apps, but the services you've connected/authorized to, and a picker shouldn't carry so much content so far, you can implement your own delegate to integrate with services.

**Comment by Fnalsk** [comment]
Not sure I understand your comment?

**Comment by AlexV525** [comment]
Typically means we cannot pick from other apps.
