### ISSUE TITLE
[BUG] Elevation Parameter has no effect

### ISSUE THREAD

**Issue by SchnMar** [fluttercandies/flutter_wechat_assets_picker#26]
**Describe the bug (描述)**
I'm using the following code:

```
appBarTheme: const AppBarTheme(
                brightness: Brightness.light,
                elevation: 100.0,
)
```

on AssetPicker initialization.

But it doesn't seem to have an effect. There is still no effect displayed. Can you have a look into this? I couldn't really find a solution as you are using your own fixedAppBar implementation.

What I tried:

Changing the color of the Box Shadow: This works, but its not the elevation effect, but just an "overall" shadow on the AppBar:
<a href="https://ibb.co/ZT36sb2"><img src="https://i.ibb.co/kcpgnPm/Simulator-Screen-Shot-i-Phone-11-Pro-2020-05-31-at-17-46-25.png" alt="Simulator-Screen-Shot-i-Phone-11-Pro-2020-05-31-at-17-46-25" border="0"></a>

My expectation:

Having some parameters or the possibility to pass my own appbar to make it look like this:
<a href="https://ibb.co/Fs7LXks"><img src="https://i.ibb.co/ZHTpSRH/Ohne-Titel.png" alt="Ohne-Titel" border="0"></a>

Thank you Andrew, you are the best! Let me know if you need additional information.

Cheers,
Marcel

**Comment by AlexVincent525** [comment]
> Thank you Andrew, you are the best!

Really? 🤣 After these bugs and features you still take my name wrong lol.

**Comment by AlexVincent525** [comment]
Try this with `2.2.0-dev.4`.
