### ISSUE TITLE
[BUG] iOS selected gif pic，assetEntity.file.path is a jpg pic

### ISSUE THREAD

**Issue by laowangDemon** [fluttercandies/flutter_wechat_assets_picker#260]
**Describe the bug**
[BUG] 
I want upload a gif
iOS selected gif pic，assetEntity.file.path is a jpg pic
需求，iOS选择gif，上传到服务器
问题，当使用flutter_wechat_assets_picker，选择一个gif图片，返回的assetEntity.file.path是一个jpg图片，并不是gif

**How to reproduce**
I used flutter_wechat_assets_picker demo
<img width="942" alt="image" src="https://user-images.githubusercontent.com/35515568/155822648-73933a90-ca2a-440f-bb8b-0b0db3a4e203.png">

iOS selected gif pic，print assetEntity.file.path is a png pic

<img width="441" alt="image" src="https://user-images.githubusercontent.com/35515568/155822536-74bc3e4d-ff91-4e49-aeaf-b51828c47512.png">

**Expected behavior**
I want assetEntity.file.path is XXX.gif

**Version information**

- Device: [e.g. iPhone 11]
- OS: [e.g. iOS 15.3.1]
- Package Version: [e.g. 6.3.1]
- Flutter Version: [e.g. v2.8.0]

**Comment by AlexV525** [comment]
.originFile
