### ISSUE TITLE
Camera button always need.

### ISSUE THREAD

**Issue by happymario** [fluttercandies/flutter_wechat_assets_picker#261]
**Version information**
 - Device: *Android, iPhone*
 - OS: *Android 30, iOS 15 over*
 - Package Version: *v6.3.1*
 - Flutter Version: v2.8.1*

**Is your feature request related to a problem?**
I want to always show camera button on grid view.
But if there is no photos on gallery, there is no camera button too.

**Comment by AlexV525** [comment]
Did you read the document and ran the example already?

**Comment by happymario** [comment]
Yeah!
The camera button is showed, but it is only in 'recent' directory.
And in iOS, it is showed on bottom of grid, but not top of it.
But in Android,  it is only showed on top of grid view.

**Comment by happymario** [comment]
Very very bug and good function.

**Comment by AlexV525** [comment]
- A photo should only be taken with the whole album, not a specific album, so it's intended.
- iOS "Photos" and "WeChat" cheat photos grid as reversed, which means photos are aligned from the bottom, so it's by design, and we also have a predicate to control the behavior.

**Comment by happymario** [comment]
We cannot have camera button always?

**Comment by AlexV525** [comment]
Please submit a feature request with more detail.
