### ISSUE TITLE
[BUG] Project does not compile to web using 7+ version (worked fine before)

### ISSUE THREAD

**Issue by LeGoffMael** [fluttercandies/flutter_wechat_assets_picker#268]
**Describe the bug**

Project does not compile in web using 7.0.1.
It worked fine with <7 version. There is no problem on mobile.

It looks like it is related to live pictures and extended_image_library.

Tested and found in both `7.0.0` and `7.0.1`.

**How to reproduce**

1. Add this plugin (`wechat_assets_picker: ^7.0.1`) to `pubspec.yaml`
2. Start debugging to chrome.
3. `Failed to compile application.` error message in the log

**Expected behavior**

Even if this plugin does not support web, project should be able to compile for web env normally, like in previous version.

**Version information**

- Device: Chrome
- OS: Macbook pro (intel chip)
- Package Version: 7.0.1
- Flutter Version: 2.10.3

**Additional context**

```bash
Launching lib[/main.dart]() on Chrome in debug mode...
libmain.dart:1
: Error: A value of type 'File*1*?' can't be assigned to a variable of type 'File*2*?'.
..…builderimage_page_builder.dart:53
 - 'File/*1*/' is from 'dart:io'.
- 'File/*2*/' is from 'package:extended_image_library[/src/_platform_web.dart]()' ('.[./../../.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/_platform_web.dart]()').
package:extended_image_librarysrc_platform_web.dart:1
      file = await widget.asset.originFileWithSubtype;

             ^
: Error: A value of type 'File*1*?' can't be assigned to a variable of type 'File*2*?'.
..…builder/image_page_builder.dart:55
 - 'File/*1*/' is from 'dart:io'.
- 'File/*2*/' is from 'package:extended_image_library[/src/_platform_web.dart]()' ('.[./../../.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/_platform_web.dart]()').
package:extended_image_librarysrc_platform_web.dart:1
      file = await widget.asset.fileWithSubtype;
             ^

: Error: The argument type 'File*1*' can't be assigned to the parameter type 'File*2*'.
../…/builder/image_page_builder.dart:61
- 'File/*1*/' is from 'package:extended_image_library[/src/_platform_web.dart]()' ('.[./../../.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/_platform_web.dart]()').
package:extended_image_librarysrc_platform_web.dart:1

 - 'File/*2*/' is from 'dart:io'.
      file,
      ^

Failed to compile application.
Exited (sigterm)
```

**Comment by AlexV525** [comment]
You seem to build your app targeting the web. Duplicate with #227.

**Comment by LeGoffMael** [comment]
Yes you're right but they were no problem with previous version `6.3.1.

**Comment by AlexV525** [comment]
It's not about whether the path is working, but whether it's valid.

**Comment by LeGoffMael** [comment]
I see, in such case it sounds like a Breaking change isn't it, project configuration must be updated from 7+ version since compilation will failed in web. Which was not the case before.

I will check what i must change in my configuration. Thank you for the quick reply.

**Comment by AlexV525** [comment]
> in such case it sounds like a Breaking change isn't it

Not really. We've already been using the `extended_image` long ago, and according to #227, it's not related to v7.x, so it's not a breaking change.

**Comment by LeGoffMael** [comment]
After further investigation, you're absolutely right, this error occurs before v7, it is not a breaking change.

I need to found out how i've been able to compile to web since a month without a problem until the update 🤔.

Thank you again for your time.

**Comment by AlexV525** [comment]
You can file issues against the extended image library, that would be more reasonable.

**Comment by LeGoffMael** [comment]
If someone is facing the same issue, here is how i fixed it in my case:

### Avoid error

avoid:
``` dart
import 'package:wechat_assets_picker/wechat_assets_picker.dart';
```

try being the most accurate possible (i.e: `package:wechat_assets_picker/src/delegates/asset_picker_text_delegate.dart`) or use `package:photo_manager/photo_manager.dart` if possible.

### Fix error

in the case you need to import all `wechat_assets_picker` package or a file that causes the error, you will need to use [conditional import](https://medium.com/flutter-community/conditional-imports-across-flutter-and-web-4b88885a886e).

```dart
import 'package:wechat_assets_picker/wechat_assets_picker.dart'
    if (dart.library.html) 'package:my_app/whatever_filename.dart';
```
in `whatever_filename.dart`:
```dart
/// export `photo_manager` to avoid not found error while compiling in web
export 'package:photo_manager/photo_manager.dart';

/// Add dumb classes to import for web instead of `wechat_assets_picker` to be able to compile
class AssetPicker {
  static Future<Null> pickAssets(_, {pickerConfig}) async => null;
}

class AssetPickerConfig {
  const AssetPickerConfig({
    this.maxAssets,
    this.requestType,
    this.filterOptions,
    this.themeColor,
    this.textDelegate,
    this.selectedAssets, // add all needed parameters
  });

  final maxAssets,
      requestType,
      filterOptions,
      themeColor,
      textDelegate,
      selectedAssets;
}
```

**Comment by AlexV525** [comment]
Discussed with @zmtzawqlp offline, we have some class conflicts here. Reopen for applying fixes.
