### ISSUE TITLE
[BUG] specialItemPosition: is not working properly.

### ISSUE THREAD

**Issue by orshih6** [fluttercandies/flutter_wechat_assets_picker#270]
i'm run example code from this package. but specialItemPosition is not working preperly. 
i'm set value **specialItemPosition: SpecialItemPosition.prepend,**
output
ANDROID: added leading of list.
IOS: added trailing of list.
<img width="358" alt="Screen Shot 2022-03-10 at 11 42 43" src="https://user-images.githubusercontent.com/34618353/157584330-92d5df2f-c679-42a6-accc-a5bdcb9d6a65.png">
<img width="358" alt="Screen Shot 2022-03-10 at 11 33 32" src="https://user-images.githubusercontent.com/34618353/157584349-0a9389d4-2a66-4ab4-9c16-9d4b89dac230.png">

**Comment by AlexV525** [comment]
#28.
