### ISSUE TITLE
[BUG] Command CompileSwiftSources failed with a nonzero exit code

### ISSUE THREAD

**Issue by Mocaris** [fluttercandies/flutter_wechat_assets_picker#274]
it run build successful ,
when it archive :

CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler (in target 'DKImagePickerController' from project 'Pods')
    cd /Users/mocaris/DevWork/AndroidStudio/Flutter/ocareer/ios/Pods
    export DEVELOPER_DIR\=/Applications/Xcode.app/Contents/Developer
    export SDKROOT\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name DKImagePickerController -O -whole-module-optimization -enforce-exclusivity\=checked @/Users/mocaris/Library/Developer/Xcode/DerivedData/Runner-bninnnirwjgaghgihpgglpsgdhlb/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/DKImagePickerController.build/Objects-normal/armv7/DKImagePickerController.SwiftFileList -D COCOAPODS -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -target armv7-apple-ios9.0 -g -module-cache-path /Users/mocaris/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -embed-bitcode -swift-version 5 -I /Users/mocaris/Library/Developer/Xcode/DerivedData/Runner-bninnnirwjgaghgihpgglpsgdhlb/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/DKImagePickerController -F /Users/mocaris/Library/Developer/Xcode/DerivedData/Runner-bninnnirwjgaghgihpgglpsgdhlb/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/DKImagePickerController -F /Users/mocaris/Library/Developer/Xcode/DerivedData/Runner-bninnnirwjgaghgihpgglpsgdhlb/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/DKPhotoGallery -F /Users/mocaris/Library/Developer/Xcode/DerivedData/Runner-bninnnirwjgaghgihpgglpsgdhlb/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/SDWebImage -F /Users/mocaris/Library/Developer/Xcode/DerivedData/Runner-bninnnirwjgaghgihpgglpsgdhlb/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/SwiftyGif -c -num-threads 8 -output-file-map /Users/mocaris/Library/Developer/Xcode/DerivedData/Runner-bninnnirwjgaghgihpgglpsgdhlb/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/DKImagePickerController.build/Objects-normal/armv7/DKImagePickerController-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/mocaris/Library/Developer/Xcode/DerivedData/Runner-bninnnirwjgaghgihpgglpsgdhlb/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/DKImagePickerController.build/Objects-normal/armv7/DKImagePickerController.swiftmodule -Xcc -I/Users/mocaris/Library/Developer/Xcode/DerivedData/Runner-bninnnirwjgaghgihpgglpsgdhlb/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/DKImagePickerController.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/mocaris/Library/Developer/Xcode/DerivedData/Runner-bninnnirwjgaghgihpgglpsgdhlb/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/DKImagePickerController.build/DKImagePickerController-generated-files.hmap -Xcc -I/Users/mocaris/Library/Developer/Xcode/DerivedData/Runner-bninnnirwjgaghgihpgglpsgdhlb/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/DKImagePickerController.build/DKImagePickerController-own-target-headers.hmap -Xcc -I/Users/mocaris/Library/Developer/Xcode/DerivedData/Runner-bninnnirwjgaghgihpgglpsgdhlb/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/DKImagePickerController.build/DKImagePickerController-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/mocaris/Library/Developer/Xcode/DerivedData/Runner-bninnnirwjgaghgihpgglpsgdhlb/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/DKImagePickerController.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/mocaris/Library/Developer/Xcode/DerivedData/Runner-bninnnirwjgaghgihpgglpsgdhlb/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/DKImagePickerController.build/DKImagePickerController-project-headers.hmap -Xcc -I/Users/mocaris/Library/Developer/Xcode/DerivedData/Runner-bninnnirwjgaghgihpgglpsgdhlb/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/DKImagePickerController/include -Xcc -I/Users/mocaris/Library/Developer/Xcode/DerivedData/Runner-bninnnirwjgaghgihpgglpsgdhlb/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/DKImagePickerController.build/DerivedSources-normal/armv7 -Xcc -I/Users/mocaris/Library/Developer/Xcode/DerivedData/Runner-bninnnirwjgaghgihpgglpsgdhlb/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/DKImagePickerController.build/DerivedSources/armv7 -Xcc -I/Users/mocaris/Library/Developer/Xcode/DerivedData/Runner-bninnnirwjgaghgihpgglpsgdhlb/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/DKImagePickerController.build/DerivedSources -Xcc -DPOD_CONFIGURATION_RELEASE\=1 -Xcc -DCOCOAPODS\=1 -Xcc -DPERMISSION_CAMERA\=1 -Xcc -DPERMISSION_MICROPHONE\=1 -Xcc -DPERMISSION_PHOTOS\=1 -Xcc -DPERMISSION_LOCATION\=1 -Xcc -DPERMISSION_NOTIFICATIONS\=1 -emit-objc-header -emit-objc-header-path /Users/mocaris/Library/Developer/Xcode/DerivedData/Runner-bninnnirwjgaghgihpgglpsgdhlb/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/DKImagePickerController.build/Objects-normal/armv7/DKImagePickerController-Swift.h -import-underlying-module -Xcc -ivfsoverlay -Xcc /Users/mocaris/Library/Developer/Xcode/DerivedData/Runner-bninnnirwjgaghgihpgglpsgdhlb/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/DKImagePickerController.build/unextended-module-overlay.yaml -working-directory /Users/mocaris/DevWork/AndroidStudio/Flutter/ocareer/ios/Pods

remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
Command CompileSwiftSources failed with a nonzero exit code

**Version information**

- Xcode 13.3
- Flutter Version: [e.g. v2.10.3]

**Additional context**

**Comment by AlexV525** [comment]
#28
