### ISSUE TITLE
[BUG] Error with something

### ISSUE THREAD

**Issue by xoxhk** [fluttercandies/flutter_wechat_assets_picker#276]
ios 接入这个库就这样了，跑不起来了

Launching lib/main.dart on lPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: VE8DA2XSJ2
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A photo_manager
      A video_player_avfoundation
      - Flutter
      - aliyun_log
      - device_info_plus
      - file_picker
      - package_info
      - pangle_flutter
      - path_provider_ios
      - pdfx
      - plain_notification_token
      - share_plus
      - sqflite
      - tencent_im_sdk_plugin
      - umeng_common_sdk
      - url_launcher_ios

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `aliyun_log` from `.symlinks/plugins/aliyun_log/ios`
    -> Fetching podspec for `device_info_plus` from `.symlinks/plugins/device_info_plus/ios`
    -> Fetching podspec for `file_picker` from `.symlinks/plugins/file_picker/ios`
    -> Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
    -> Fetching podspec for `pangle_flutter` from `.symlinks/plugins/pangle_flutter/ios`
    -> Fetching podspec for `path_provider_ios` from `.symlinks/plugins/path_provider_ios/ios`
    -> Fetching podspec for `pdfx` from `.symlinks/plugins/pdfx/ios`
    -> Fetching podspec for `photo_manager` from `.symlinks/plugins/photo_manager/ios`
    -> Fetching podspec for `plain_notification_token` from `.symlinks/plugins/plain_notification_token/ios`
    -> Fetching podspec for `share_plus` from `.symlinks/plugins/share_plus/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
    -> Fetching podspec for `tencent_im_sdk_plugin` from `.symlinks/plugins/tencent_im_sdk_plugin/ios`
    -> Fetching podspec for `umeng_common_sdk` from `.symlinks/plugins/umeng_common_sdk/ios`
    -> Fetching podspec for `url_launcher_ios` from `.symlinks/plugins/url_launcher_ios/ios`
    -> Fetching podspec for `video_player_avfoundation` from `.symlinks/plugins/video_player_avfoundation/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_b_b_4.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/b/b/4/AliyunLogProducer/2.5.0.alpha.2/AliyunLogProducer.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_1_6_1.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/1/6/1/DKImagePickerController/4.3.2/DKImagePickerController.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/1/6/1/DKImagePickerController/4.3.2/DKImagePickerController.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_4_2_c.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/2.10.2/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update

    ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    ### Command

    ```
    /usr/local/bin/pod install --verbose
    ```

    ### Report

    * What did you do?

    * What did you expect to happen?

    * What happened instead?

    ### Stack

    ```
       CocoaPods : 1.11.3
            Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
        RubyGems : 3.0.3.1
            Host : macOS 12.0.1 (21A559)
           Xcode : 13.2.1 (13C100)
             Git : git version 2.32.0 (Apple Git-132)
    Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
    Repositories : trunk - CDN - https://cdn.cocoapods.org/
    ```

    ### Plugins

    ```
    cocoapods-deintegrate : 1.0.5
    cocoapods-plugins     : 1.0.0
    cocoapods-search      : 1.0.1
    cocoapods-trunk       : 1.6.0
    cocoapods-try         : 1.2.0
    ```

    ### Podfile

    ```ruby
    # Uncomment this line to define a global platform for your project
    # platform :ios, '9.0'

    # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
    ENV['COCOAPODS_DISABLE_STATS'] = 'true'

    project 'Runner', {
      'Debug' => :debug,
      'Profile' => :release,
      'Release' => :release,
    }

    def flutter_root
      generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
      unless File.exist?(generated_xcode_build_settings_path)
        raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
      end

      File.foreach(generated_xcode_build_settings_path) do |line|
        matches = line.match(/FLUTTER_ROOT\=(.*)/)
        return matches[1].strip if matches
      end
      raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
    end

    require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

    flutter_ios_podfile_setup

    target 'Runner' do
      use_frameworks!
      use_modular_headers!

      flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
    end

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        flutter_additional_ios_build_settings(target)
      end
    end
    ```

    ### Error

    ```
    JSON::ParserError - 767: unexpected token at '{
      "name": "FlutterMacOS",
      "version": "2.10.2",
      "summary": "A UI toolkit for beautiful and fast apps.",
      "description": "Flutter is Google's UI toolkit for building beautiful, fast apps for mobile, web, desktop, and embedded devices from a single codebase.\nThis pod vends the macOS release mode Flutter engine framework. It is compatible with application frameworks created with this version of the engine and tools.",
      "homepage": "https://flutter.dev/",
      "license": {
        "type": "BSD",
        "text": "Copyright 2014 The Chromium Authors. All rights reserved.\n\nRedistribution and use in source and binary forms, with or without modification,\nare permitted provided that the following conditions are met:\n\n    * Redistributions of source code must retain the above copyright\n      notice, this list of conditions and the following disclaimer.\n    * Redistributions in binary form must reproduce the above\n      copyright notice, this list of conditions and the following\n      disclaimer in the documentation and/or other materials provided\n      with the distribution.\n    * Neither the name of Google Inc. nor the names of its\n      contributors may be used to endorse or promote products derived\n      from this software without specific prior written permission.\n\nTHIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND\nANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\nWARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\nDISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR\nANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\nLOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON\nANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\nSOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
      },
      "authors": {
        "Flutter Dev Team": "flutter-dev@googlegroups.com"
      },
      "source": {
        "http": "https://storage.googleapis.com/flutter_infra_release/flutter/a83ed0e5e3b9cd2b5e2f07ef31c72f43c55e93b7/darwin-x64-release/FlutterMacOS.framework.zip"
      },
      "documentation_url": "https://flutter.dev/docs",
      "platforms": {
        "osx": "10.11'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification/json.rb:61:in `from_json'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification.rb:748:in `from_string'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification.rb:722:in `from_file'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source.rb:188:in `specification'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification/set.rb:58:in `block in specification_name'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification/set.rb:56:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:216:in `search'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `select'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `search'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:385:in `find_cached_set'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:165:in `search_for'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_by'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_by!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
    ```

    ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    [!] Oh no, an error occurred.

    Search for existing GitHub issues similar to yours:
    https://github.com/CocoaPods/CocoaPods/search?q=767%3A+unexpected+token+at+%27%7B%0A++%22name%22%3A+%22FlutterMacOS%22%2C%0A++%22version%22%3A+%222.10.2%22%2C%0A++%22summary%22%3A+%22A+UI+toolkit+for+beautiful+and+fast+apps.%22%2C%0A++%22description%22%3A+%22Flutter+is+Google%27s+UI+toolkit+for+building+beautiful%2C+fast+apps+for+mobile%2C+web%2C+desktop%2C+and+embedded+devices+from+a+single+codebase.%5CnThis+pod+vends+the+macOS+release+mode+Flutter+engine+framework.+It+is+compatible+with+application+frameworks+created+with+this+version+of+the+engine+and+tools.%22%2C%0A++%22homepage%22%3A+%22https%3A%2F%2Fflutter.dev%2F%22%2C%0A++%22license%22%3A+%7B%0A++++%22type%22%3A+%22BSD%22%2C%0A++++%22text%22%3A+%22Copyright+2014+The+Chromium+Authors.+All+rights+reserved.%5Cn%5CnRedistribution+and+use+in+source+and+binary+forms%2C+with+or+without+modification%2C%5Cnare+permitted+provided+that+the+following+conditions+are+met%3A%5Cn%5Cn++++%2A+Redistributions+of+source+code+must+retain+the+above+copyright%5Cn++++++notice%2C+this+list+of+conditions+and+the+following+disclaimer.%5Cn++++%2A+Redistributions+in+binary+form+must+reproduce+the+above%5Cn++++++copyright+notice%2C+this+list+of+conditions+and+the+following%5Cn++++++disclaimer+in+the+documentation+and%2For+other+materials+provided%5Cn++++++with+the+distribution.%5Cn++++%2A+Neither+the+name+of+Google+Inc.+nor+the+names+of+its%5Cn++++++contributors+may+be+used+to+endorse+or+promote+products+derived%5Cn++++++from+this+software+without+specific+prior+written+permission.%5Cn%5CnTHIS+SOFTWARE+IS+PROVIDED+BY+THE+COPYRIGHT+HOLDERS+AND+CONTRIBUTORS+%5C%22AS+IS%5C%22+AND%5CnANY+EXPRESS+OR+IMPLIED+WARRANTIES%2C+INCLUDING%2C+BUT+NOT+LIMITED+TO%2C+THE+IMPLIED%5CnWARRANTIES+OF+MERCHANTABILITY+AND+FITNESS+FOR+A+PARTICULAR+PURPOSE+ARE%5CnDISCLAIMED.+IN+NO+EVENT+SHALL+THE+COPYRIGHT+OWNER+OR+CONTRIBUTORS+BE+LIABLE+FOR%5CnANY+DIRECT%2C+INDIRECT%2C+INCIDENTAL%2C+SPECIAL%2C+EXEMPLARY%2C+OR+CONSEQUENTIAL+DAMAGES%5Cn%28INCLUDING%2C+BUT+NOT+LIMITED+TO%2C+PROCUREMENT+OF+SUBSTITUTE+GOODS+OR+SERVICES%3B%5CnLOSS+OF+USE%2C+DATA%2C+OR+PROFITS%3B+OR+BUSINESS+INTERRUPTION%29+HOWEVER+CAUSED+AND+ON%5CnANY+THEORY+OF+LIABILITY%2C+WHETHER+IN+CONTRACT%2C+STRICT+LIABILITY%2C+OR+TORT%5Cn%28INCLUDING+NEGLIGENCE+OR+OTHERWISE%29+ARISING+IN+ANY+WAY+OUT+OF+THE+USE+OF+THIS%5CnSOFTWARE%2C+EVEN+IF+ADVISED+OF+THE+POSSIBILITY+OF+SUCH+DAMAGE.%5Cn%22%0A++%7D%2C%0A++%22authors%22%3A+%7B%0A++++%22Flutter+Dev+Team%22%3A+%22flutter-dev%40googlegroups.com%22%0A++%7D%2C%0A++%22source%22%3A+%7B%0A++++%22http%22%3A+%22https%3A%2F%2Fstorage.googleapis.com%2Fflutter_infra_release%2Fflutter%2Fa83ed0e5e3b9cd2b5e2f07ef31c72f43c55e93b7%2Fdarwin-x64-release%2FFlutterMacOS.framework.zip%22%0A++%7D%2C%0A++%22documentation_url%22%3A+%22https%3A%2F%2Fflutter.dev%2Fdocs%22%2C%0A++%22platforms%22%3A+%7B%0A++++%22osx%22%3A+%2210.11%27&type=Issues

    If none exists, create a ticket, with the template displayed above, on:
    https://github.com/CocoaPods/CocoaPods/issues/new

    Be sure to first read the contributing guide for details on how to properly submit a ticket:
    https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

    Don't forget to anonymize any private data!

    Looking for related issues on cocoapods/cocoapods...

Error output from CocoaPods:
↳
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin21/rbconfig.rb:230: warning: Insecure world writable dir /opt/homebrew/bin in PATH, mode 040777
    Searching for inspections failed: undefined method `map' for nil:NilClass

    [!] Automatically assigning platform `iOS` with version `11.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Exception: Error running pod install

**Comment by AlexV525** [comment]
#28

**Comment by xtuck** [comment]
+1
