### ISSUE TITLE
[BUG] Error with generating apk

### ISSUE THREAD

**Issue by akshay0542** [fluttercandies/flutter_wechat_assets_picker#279]
**Describe the bug**
issue with generating apk

**How to reproduce**
`Type com.bumptech.glide.GeneratedAppGlideModuleImpl is defined multiple times: /Users/akshaypatel/Documents/Wappnet/Fultter/Wappnet/vCreation/github/vCreations-Flutter/build/local_image_provider/intermediates/runtime_library_classes_jar/release/classes.jar:com/bumptech/glide/GeneratedAppGlideModuleImpl.class, /Users/akshaypatel/Documents/Wappnet/Fultter/Wappnet/vCreation/github/vCreations-Flutter/build/app/intermediates/javac/release/classes/com/bumptech/glide/GeneratedAppGlideModuleImpl.class

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
 com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/akshaypatel/Documents/Wappnet/Fultter/Wappnet/vCreation/github/vCreations-Flutter/build/local_image_provider/intermediates/runtime_library_classes_jar/release/classes.jar:com/bumptech/glide/GeneratedAppGlideModuleImpl.class`

flutter build apk

**Expected behavior**
need to generate apk

**Screenshots (If contains)**

**Version information**

- Device: Readmi note 10
- OS: Android
- Package Version: 7.0.5
- Flutter Version: v2.10.2

**Additional context**

![Screenshot 2022-03-28 at 8 37 45 PM](https://user-images.githubusercontent.com/74226412/160428964-729e7ecc-07b4-4709-8c19-7ef9574df466.png)
![Screenshot 2022-03-28 at 8 40 57 PM](https://user-images.githubusercontent.com/74226412/160429777-e955217d-bb0c-44bb-990a-f3de0f713202.png)

Quick help will be appreciated
Thanks in advance.

**Comment by AlexV525** [comment]
![image](https://user-images.githubusercontent.com/15884415/160431391-89729837-dbfb-495c-82f3-16f5aaa4f20b.png)

**Comment by akshay0542** [comment]
Hello @AlexV525 I feel that I have made some mistake while integrating the glide in android. Do you have any documentation or a link to verify the correct glide integration. I have followed the steps
->  `    implementation 'com.github.bumptech.glide:glide:4.11.0' //bumped from 4.8.0 to 4.9.0
    kapt 'com.github.bumptech.glide:compiler:4.11.0'` in app/build.gradle file
->  `apply plugin: 'kotlin-kapt'`  in app/build.gradle file
-> add ExampleAppGlideModule.java file in kotlin folder

This are the steps I have followed to configure Glide.

**Comment by CaiJingLong** [comment]
See the [document](https://github.com/fluttercandies/flutter_photo_manager#glide-issues).

**Comment by akshay0542** [comment]
I have one more issue as well, I am not able to fetch the thumbnail data in android, I can etch the whole image but no thumbnail is there. Any ideas on it?

**Comment by akshay0542** [comment]
Hello Guys,
I found my mistakes and resolved as follow
1. I have added (ExampleAppGlideModule) java file in kotlin folder i change it to kotlin file
2. I have removed local_image_provider library which is responsible for GeneratedAppGlideModuleImpl is defined multiple times while generating the apk.

Thanks guys.
