### ISSUE TITLE
[Feature] Can the author provide support 华为鸿蒙系统（HUAWEI Harmony OS）

### ISSUE THREAD

**Issue by sbiweeq** [fluttercandies/flutter_wechat_assets_picker#281]
**Version information**
 - Device: *e.g. Harmony OS*
 - OS: *e.g. Harmony OS*
 - Package Version: *e.g. v2.4.1*
 - Flutter Version: *e.g. v2.5.0*

**Is your feature request related to a problem?**
no

**Describe the solution you'd like**
    Can the author provide support 华为鸿蒙系统（HUAWEI Harmony OS）
At present, flutter native can support opening pictures and permissions, but there is no plug-in UI. I hope the author can provide adaptation

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by AlexV525** [comment]
| ![32F859092033541FDF07D1ADD6A6A07D](https://user-images.githubusercontent.com/15884415/160573938-bed2d7cf-22ca-4723-ba3c-ec3a61f81eaa.png) | ![B3B286AD90F6F3DBFBB8F0514AD50B9B](https://user-images.githubusercontent.com/15884415/160573955-daaa0035-50ac-4c28-b174-9a44252f0e7b.png) | ![BCC7713077DE88FA28A9F21EC13FC5CE](https://user-images.githubusercontent.com/15884415/160573970-ec955ba1-4716-4bbb-979a-c39e8b64233e.png) |
| -- | -- | -- |
