### ISSUE TITLE
Not working wth Latest version

### ISSUE THREAD

**Issue by GauravCalidig** [fluttercandies/flutter_wechat_assets_picker#282]
final _entity = await CameraPicker.pickFromCamera(
      context,
      pickerConfig: CameraPickerConfig(
          enableRecording: true,
          onlyEnableRecording: true,
          enableTapRecording: true,
          resolutionPreset: ResolutionPreset.max,
          // onEntitySaving: (context, viewType, file) async {
          //   log('onEntitySaving: $viewType');
          //   log('onEntitySaving: $file');
          // },
          textDelegate: EnglishCameraPickerTextDelegateWithTapRecording(),
          maximumRecordingDuration: const Duration(seconds: 20)),
    );
![image](https://user-images.githubusercontent.com/90178033/161008135-d864d63e-2839-48a1-aeba-bd7c9c416d41.png)

**Comment by AlexV525** [comment]
#28
