### ISSUE TITLE
[BUG] Error with something

### ISSUE THREAD

**Issue by muxinSW** [fluttercandies/flutter_wechat_assets_picker#288]
Execution failed for task ':photo_manager:compileDebugKotlin'.

ע: C:\soft\env\flutter\flutter\.pub-cache\hosted\pub.flutter-io.cn\path_provider_android-2.0.12\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.javaʹ����δ�����򲻰�ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
e: C:\soft\env\flutter\flutter\.pub-cache\hosted\pub.flutter-io.cn\photo_manager-2.0.6\android\src\main\kotlin\com\fluttercandies\photo_manager\core\utils\ConvertUtils.kt: (73, 29): Unresolved reference: lowercase

**Comment by AlexV525** [comment]
#28
