### ISSUE TITLE
IOS HEIC HEIF 图片格式问题

### ISSUE THREAD

**Issue by tangdehao** [fluttercandies/flutter_wechat_assets_picker#3]
在IOS手机上，手机自带相机拍摄出来的图片都是 heic 和 heif 格式的，在相册中无法显示 ，
PS：这个格式其实挺恶心的flutter 上目前没有图片组件能够直接显示需要转换成流才能给控件显示
![2921586421986_ pic](https://user-images.githubusercontent.com/7867846/78876556-18491000-7a82-11ea-94d3-2bf98795627a.jpg)

**Comment by AlexVincent525** [comment]
Flutter不支持，我何德何能呢...

**Comment by tangdehao** [comment]
控件是不直接可以但是可以用文件流的

**Comment by SchnMar** [comment]
Maybe you can add a conversion of the image on iOS to jpeg?
