### ISSUE TITLE
Deleted files are still displayed in assetPicker and only loads the initial first page of 80 data

### ISSUE THREAD

**Issue by fanpener** [fluttercandies/flutter_wechat_assets_picker#302]
**Describe the bug**
bug1:
Deleted files are still displayed in assetPicker and I don't know why
bug2:
Assetpicker only loads the initial first page of 80 data

**How to reproduce**
I just checked out the latest version of the AssetPicker example project and found the bug
At first, I thought the reason for Bug2 was that Bug1 threw an exception and interrupted the program so that more data was not loaded. However, after I ran the example program and clicked the Video Picker Item, I found that the selected Video also showed only 80 data on the first page
   
1.Just run the Example project
2.Click on all item

**Expected behavior**
I hope to find out the cause of the bug and fix it

**Screenshots (If contains)**
bug1:
![image](https://user-images.githubusercontent.com/9603553/161628226-768d0a45-175a-48a3-a16a-9fd3c3709e24.png)
some log:
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/9603553/161628443-a4ffbf5c-13cf-4a3f-9f1f-18d384269e87.png">

bug2:
Only the first page of data is loaded, no screenshots

**Version information**

- Device: redmi k30 5g(MIUI 12.0.5,Android 10), HUAWEI mate 20(HarmonyOS 2.0.0), HUAWEI mate 40 pro(HarmonyOS 2.0.0)
wechat_assets_picker: 7.0.5   
wechat_camera_picker: 3.0.1    
<img width="588" alt="image" src="https://user-images.githubusercontent.com/9603553/161630790-267ccaec-7194-41bc-b5ae-d7a26b469605.png">

**Additional context**
I have tested three Android devices and found these bugs. I hope you can help solve them. Thank you

**Comment by AlexV525** [comment]
This has been already tracking at fluttercandies/flutter_photo_manager#734, closing.
