### ISSUE TITLE
[Feature] How to mock AssetPicker.pickAssets in test

### ISSUE THREAD

**Issue by IvoneDjaja** [fluttercandies/flutter_wechat_assets_picker#305]
This feature request is how to mock AssetPicker.pickAssets to test whether it is actually called with the correct arguments. I am running in IOS simulator, we will need to add this key in `ios/Runer/Info.plist`, otherwise the simulator will close unexpectedly after clicking the add button.

```
<key>NSPhotoLibraryUsageDescription</key>
<string>Autorize app to use photos from your gallery.</string>
```

# main.dart
```
import 'package:flutter/material.dart';
import 'package:wechat_assets_picker/wechat_assets_picker.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const [],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          final List<AssetEntity>? result =
              await AssetPicker.pickAssets(context);
        },
        tooltip: 'Add photo',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

# widget_test.dart
```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:wechat/main.dart';

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    await tester.pumpWidget(const MyApp());

    await tester.tap(find.byIcon(Icons.add));
    await tester.pump();
  });
}
```

**Comment by AlexV525** [comment]
> I am running in IOS simulator, we will need to add this key in `ios/Runer/Info.plist`, otherwise the simulator will close unexpectedly after clicking the add button.

This is the basic requirement to use the package. I'm not sure how does it related to the issue.

Regarding the test part, can you write some pseudo code of tests to indicate your request?

**Comment by IvoneDjaja** [comment]
Thank you for your reply, here is an example code using flutter mocktail package. https://pub.dev/packages/mocktail

# widget_test.dart
```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';
import 'package:wechat/main.dart';
import 'package:wechat_assets_picker/wechat_assets_picker.dart';

class _MockAssetPicker extends Mock implements AssetPicker {}

void main() {
  testWidgets('It should call the WeChat asset picker',
      (WidgetTester tester) async {
    await tester.pumpWidget(const MyApp());
    final BuildContext context = tester.element(find.byType(MyApp));

    final assetPickerMock = _MockAssetPicker();
    when(() => assetPickerMock.pickAssets(context)).thenAnswer((_) => Future.value([
          const AssetEntity(
            id: 'id1',
            typeInt: 1,
            width: 100,
            height: 100,
          ),
        ]));
    AssetPicker.instance = assetPickerMock;

    await tester.tap(find.byIcon(Icons.add));
    await tester.pump();

    verify(() => assetPickerMock.pickAssets(context)).called(1);
  });
}
```

**Comment by AlexV525** [comment]
`pickAssets` is a static method, and it won't do assets picking automatically for you. Actually, the future call only binds with the picking route.

Given the fact that `pickAssets` is a static method, there is no proper way to mock the entry for the package currently. But I'll update another test branch to see if it's doable.

**Comment by ValentinVignal** [comment]
@AlexV525 What the other packages are usually doing is to create an static instance that can be mocked in the tests:

```dart
class MyClass {
  MyClass._();
  
  MyClass? _instance;
  MyClass get instance => _instance ??= MyClass._();
  @visibleForTesting
  set instance(MyClass instance) {  // <- He can pass our mock here
    _instance = instance;
  }
}
```

Would it be possible to do something similar ?

**Comment by AlexV525** [comment]
> Would it be possible to do something similar ?

In my imagination, the improvement would be something like this:
```dart
class AssetPicker {
  static Future<List<AssetEntity>?> pickAssets() {
    const AssetPickerDelegate delegate = AssetPickerDelegate._();
    return delegate.pickAssets();
  }
}

/// Creating a new delegate for mocking.
class AssetPickerDelegate {
  const AssetPickerDelegate._();

  @visibleForTest
  const AssetPickerDelegate.forTest();

  Future<List<AssetEntity>?> pickAssets() async {
    //...
  }
}
```

**Comment by ValentinVignal** [comment]
> > Would it be possible to do something similar ?
> 
> In my imagination, the improvement would be something like this:
> 
> ```dart
> class AssetPicker {
>   static Future<List<AssetEntity>?> pickAssets() {
>     const AssetPickerDelegate delegate = AssetPickerDelegate._();
>     return delegate.pickAssets();
>   }
> }
> 
> /// Creating a new delegate for mocking.
> class AssetPickerDelegate {
>   const AssetPickerDelegate._();
> 
>   @visibleForTest
>   const AssetPickerDelegate.forTest();
> 
>   Future<List<AssetEntity>?> pickAssets() async {
>     //...
>   }
> }
> ```

How would you use this mock in a test?

**Comment by AlexV525** [comment]
> How would you use this mock in a test?

As per https://github.com/fluttercandies/flutter_wechat_assets_picker/issues/305#issuecomment-1104686185, will try to implement this in a separate branch.

**Comment by AlexV525** [comment]
In #315, users can use `AssetPicker.setPickerDelegate` to override the default picker delegate with your customized one, e.g. a mock-tailed one, then verify picking calls.

Let me know if the PR solves the request.

**Comment by IvoneDjaja** [comment]
Thank you, I am able to write the test now.
