### ISSUE TITLE
[BUG] iOS选择照片部分允许相关问题

### ISSUE THREAD

**Issue by 1203556555** [fluttercandies/flutter_wechat_assets_picker#309]
**Describe the bug**
选择允许部分访问后不选择图片，将无法再选择图片
![image](https://user-images.githubusercontent.com/18067025/165435443-d5bc002a-b875-4c53-8548-d6e62d597b57.png)
第二次进入之后，列表
![image](https://user-images.githubusercontent.com/18067025/165435481-22a83139-f4ae-40a9-81f4-8362ef896e3f.png)
选择图片之后，文字颜色看不清
![image](https://user-images.githubusercontent.com/18067025/165435908-62961193-5aae-4f46-8b57-38f1c1a8ef5b.png)
![image](https://user-images.githubusercontent.com/18067025/165435929-a30600e7-c073-4247-89a3-642ad9ea9455.png)

**How to reproduce**
官方demo就能复现

**Version information**

- Device: [e.g. iPhone 13]
- OS: [e.g. iOS 15.2]
- Package Version: [e.g. 7.1.1]
- Flutter Version: [e.g. v2.8.1]

**Comment by AlexV525** [comment]
The first question is duplicated to https://github.com/fluttercandies/flutter_photo_manager/issues/643.

The second one needs investigations.

**Comment by AlexV525** [comment]
![image](https://user-images.githubusercontent.com/15884415/165448747-71ef6ef5-80b3-4794-b4a5-9d16871d713e.png)

**Comment by 1203556555** [comment]
@AlexV525 没有选择图片，后面打开图片选择器没有其他入口可以增加选择图片
![image](https://user-images.githubusercontent.com/18067025/165450007-3901aeac-d818-40b5-bebe-edc294f0ac2a.png)
