### ISSUE TITLE
No option to change button text language.

### ISSUE THREAD

**Issue by CyberGhost007** [fluttercandies/flutter_wechat_assets_picker#31]
After opening the picker, the button on the top right corner, not able to change the language of that button to English.

**Comment by AlexVincent525** [comment]
Is the right button refer to the confirm button?

**Comment by AlexVincent525** [comment]
No matter what button it is, there's a text delegate to implement the custom text. Since you didn't follow the issue template, this issue will be lock and close now.
Please follow the instruction in the pinned issue.
