### ISSUE TITLE
Unhandled Exception: PlatformException(STORAGE_NOT_LEGACY, Use `requestLegacyExternalStorage` when your project is targeting above Android Q., null, null)[BUG] Error with something

### ISSUE THREAD

**Issue by CarminBack** [fluttercandies/flutter_wechat_assets_picker#311]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(STORAGE_NOT_LEGACY, Use `requestLegacyExternalStorage` when your project is targeting above Android Q., null, null)
E/flutter (30707): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (30707): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
E/flutter (30707): <asynchronous suspension>
E/flutter (30707): #2      PhotoManagerPlugin.requestPermissionExtend (package:photo_manager/src/internal/plugin.dart:68:24)
E/flutter (30707): <asynchronous suspension>
E/flutter (30707): #3      AssetPicker.permissionCheck (package:wechat_assets_picker/src/widget/asset_picker.dart:24:33)
E/flutter (30707): <asynchronous suspension>
E/flutter (30707): #4      AssetPicker.pickAssets (package:wechat_assets_picker/src/widget/asset_picker.dart:39:33)
E/flutter (30707): <asynchronous suspension>
E/flutter (30707): #5      Common.openPic (package:xapp/utils/common.dart:145:40)
E/flutter (30707): <asynchronous suspension>
E/flutter (30707): #6      _CreateWorldWallPageState._getImage (package:xapp/pages/faxian/child/createWorldWell.dart:61:38)
E/flutter (30707): <asynchronous suspension>

**Comment by AlexV525** [comment]
#28

**Comment by petermusembi69** [comment]
@CarminBack add this in your manifest 

```xml
    <application
            android:requestLegacyExternalStorage="true"
```

**Comment by sleewok** [comment]
> @CarminBack add this in your manifest
> 
> ```
>     <application
>             android:requestLegacyExternalStorage="true"
> ```

This does not work when targeting SDK > 30

**Comment by UlasAkgun** [comment]
+1 to this, adding 

`<application
        android:requestLegacyExternalStorage="true"`

doesn't work, gives the same error the author of this issue has posted.

**Comment by AlexV525** [comment]
TBH, the author of this issue, and the people who said "it's not working", should learn how to read documents and the example hard, since all of these are working fine. :)
