### ISSUE TITLE
[BUG] Cannot pick from camera when photo library is empty (iOS)

### ISSUE THREAD

**Issue by ZhuBoao** [fluttercandies/flutter_wechat_assets_picker#313]
**Describe the bug**
I have a brand new iPhone with zero photo in it. When I was running the plugin example and test `Pick from camera` function, the page shows nothing but an empty list. After I took a photo with system camera then tried again, the screen shows the recent photo and a camera button from `specialItemBuilder`.
I suppose the camera button should be shown no matter the user have a photo or not.
I didn't test it on Android so I don't know if this bug is platform depending.

**How to reproduce**
1. Prepare a iPhone with no photo in it.
2. Run plugin example app, then press `Pick from camera` or `Pick from camera and stay`

**Expected behavior**
The camera button should be shown no matter the user have a photo or not.

**Screenshots (If contains)**
<a href="https://ibb.co/Lp4L8Mb"><img src="https://i.ibb.co/RHLx91Z/Wechat-IMG227.jpg" alt="Wechat-IMG227" border="0" /></a>

**Version information**
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] VS Code (version 1.66.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability
Package Version: latest from master branch

**Additional context**
Actually there is another tiny issue when device having no photo. As you can see from the screenshot above, the top area should show the name of a current image folder even if there is no photo (e.g `Recent` folder). Instead there is only an empty string in it. I have tested this function in Wechat itself, and Wechat gave me the same screen but with `Recent` on top.

**Comment by AlexV525** [comment]
`specialItemBuilder` allows you to build according to the `AssetPathEntity`, and it's not a default behavior in the example.

**Comment by ZhuBoao** [comment]
> `specialItemBuilder` allows you to build according to the `AssetPathEntity`, and it's not a default behavior in the example.

Understood. So the problem is I was expecting the special item to be rendered even in an empty photo list. I guess it will make much more sense to make sure the special item will show when the develop set `specialItemPosition: SpecialItemPosition.prepend` and give `specialItemBuilder` to a pick method. Am I correct?

**Comment by AlexV525** [comment]
Your goal can be achieved by:
```dart
SpecialItemBuilder<AssetPathEntity> builder = (
  BuildContext context,
  AssetPathEntity? path,
  int length,
) {
  // Ignore when the path is `null` or not `isAll`,'
  // build the special item all the time.
  return xxxWidget;
};
```

However, there are some exceptions when building like this. I'll submit a fix later.

**Comment by ZhuBoao** [comment]
> Your goal can be achieved by:
> 
> ```dart
> SpecialItemBuilder<AssetPathEntity> builder = (
>   BuildContext context,
>   AssetPathEntity? path,
>   int length,
> ) {
>   // Ignore when the path is `null` or not `isAll`,'
>   // build the special item all the time.
>   return xxxWidget;
> };
> ```
> 
> However, there are some exceptions when building like this. I'll submit a fix later.
> 
> Closing as the issue is not addressing an exception, but addressing an existing solution instead.

Glad to know that. Thanks!
