### ISSUE TITLE
[BUG] AssetPickerConfig  requestType: RequestType.video 设置选择视频，在iOS手机上会显示图片

### ISSUE THREAD

**Issue by teaplant** [fluttercandies/flutter_wechat_assets_picker#316]
**Describe the bug**

 选择相册视频的时候，图片也会出现
**How to reproduce**

4. Error occurred.

**Expected behavior**

**Screenshots (If contains)**

**Version information**

- Device: [e.g. iPhone X]
- OS: [e.g. iOS 14.7.1]
- Package Version: [e.g. 2.4.1]
- Flutter Version: [e.g. v2.5.0]

**Additional context**

**Comment by AlexV525** [comment]
#28

**Comment by fangwy** [comment]
AssetPicker.pickAssets.  pickerConfig   filterOptions:FilterOptionGroup(containsLivePhotos:false)
