### ISSUE TITLE
[BUG] demo 中在android 11上预览 手机内部图片时报错.

### ISSUE THREAD

**Issue by zhangshuqi** [fluttercandies/flutter_wechat_assets_picker#318]
**Describe the bug**

  demo 中在android 11上预览 手机内部图片时报错. 如果使用插件自带的相机拍照则可以预览
  报错图片路径(报错): /storage/emulated/0/DCIM/Screenshots/Screenshot_2022-05-09-01-57-22-11_92b64b2a7aa6eb3771ed6e18d0029815.jpg
 插件拍照路径(不报错) ;/storage/emulated/0/Pictures/CAP6241015426235493956.jpg

**How to reproduce**

  demo即可复现

 1.点击预览图片

**Expected behavior**

**Screenshots (If contains)**

![image](https://user-images.githubusercontent.com/15172679/167593527-26fb5a55-12d1-460b-bfec-ee64cb07b63f.png)
![image](https://user-images.githubusercontent.com/15172679/167593789-d1b6ab7c-b262-475b-ac36-9af2061c72c7.png)

**Version information**

- Device: [e.g. iPhone X]
- OS: [e.g. iOS 14.7.1]
- Package Version: [e.g. 2.4.1]
- Flutter Version: [e.g. v2.5.0]

**Additional context**

**Comment by zhangshuqi** [comment]
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1645], locale zh-CN)
    • Flutter version 2.10.3 at C:\Users\tank\Documents\Flutter\Flutter SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (10 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by AlexV525** [comment]
> **Version information**
> 
> * Device: [e.g. iPhone X]
> * OS: [e.g. iOS 14.7.1]
> * Package Version: [e.g. 2.4.1]
> * Flutter Version: [e.g. v2.5.0]

提供不出有效的版本？#28
