### ISSUE TITLE
[BUG] app crashd when plugin get thumb failed. 插件获取缩略图失败，导致app崩溃

### ISSUE THREAD

**Issue by suyie001** [fluttercandies/flutter_wechat_assets_picker#323]
**Describe the bug**

when I use this plugin to get assets ，it will get thumb failed with some items in the grid. And when I close this picker view, and reopen , it will crash my app.
在我获取资源的时候，在资源选择页面，有些资源会获取缩略图失败，会获得一个报错，但并不会马上崩溃，但是我关掉选择页面，再重新打开的时候 就会导致应用崩溃。 

**How to reproduce**

1. run  AssetPicker.pickAssets method.
2. if there are some get thumb failed，then close this page.//如果这个选择页面里有一些缩略图获取失败的话 就关闭页面。
3. run AssetPicker.pickAssets method again.
4. it will crash.

**Expected behavior**

  no crash.

**Screenshots (If contains)**

**Version information**

- Device: meizu 17
- OS: android 11
- Package Version:wechat_assets_picker: 7.2.0
- Flutter Version: flutter 3.0

**Additional context**

There is the error log.

E/PhotoManager(20128): get 61890 thumbnail error, width : 80, height: 80
E/PhotoManager(20128): java.io.FileNotFoundException: open failed: EFAULT (Bad address)
E/PhotoManager(20128): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
E/PhotoManager(20128): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:781)
E/PhotoManager(20128): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1985)
E/PhotoManager(20128): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1800)
E/PhotoManager(20128): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1477)
E/PhotoManager(20128): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.convertCursorToAssetEntity(AndroidQDBUtils.kt:257)
E/PhotoManager(20128): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.getAssetEntity(AndroidQDBUtils.kt:292)
E/PhotoManager(20128): 	at com.fluttercandies.photo_manager.core.PhotoManager.getThumb(PhotoManager.kt:91)
E/PhotoManager(20128): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$4.invoke(PhotoManagerPlugin.kt:266)
E/PhotoManager(20128): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$4.invoke(PhotoManagerPlugin.kt:262)
E/PhotoManager(20128): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.runOnBackground$lambda-0(PhotoManagerPlugin.kt:46)
E/PhotoManager(20128): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.lambda$bZa62ZrXsGssc32bPH4oVAuIci4(Unknown Source:0)
E/PhotoManager(20128): 	at com.fluttercandies.photo_manager.core.-$$Lambda$PhotoManagerPlugin$Companion$bZa62ZrXsGssc32bPH4oVAuIci4.run(Unknown Source:2)
E/PhotoManager(20128): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/PhotoManager(20128): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/PhotoManager(20128): 	at java.lang.Thread.run(Thread.java:923)
E/flutter (20128): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(201, get thumb error, java.io.FileNotFoundException: open failed: EFAULT (Bad address)
E/flutter (20128): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
E/flutter (20128): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:781)
E/flutter (20128): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1985)
E/flutter (20128): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1800)
E/flutter (20128): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1477)
E/flutter (20128): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.convertCursorToAssetEntity(AndroidQDBUtils.kt:257)
E/flutter (20128): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.getAssetEntity(AndroidQDBUtils.kt:292)
E/flutter (20128): 	at com.fluttercandies.photo_manager.core.PhotoManager.getThumb(PhotoManager.kt:91)
E/flutter (20128): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$4.invoke(PhotoManagerPlugin.kt:266)
E/flutter (20128): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$4.invoke(PhotoManagerPlugin.kt:262)
E/flutter (20128): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.runOnBackground$lambda-0(PhotoManagerPlugin.kt:46)
E/flutter (20128): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.lambda$bZa62ZrXsGssc32bPH4oVAuIci4(Unknown Source:0)
E/flutter (20128): 	at com.fluttercandies.photo_manager.core.-$$Lambda$PhotoManagerPlugin$Companion$bZa62ZrXsGssc32bPH4oVAuIci4.run(Unknown Source:2)
E/flutter (20128): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/flutter (20128): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/flutter (20128): 	at java.lang.Thread.run(Thread.java:923)
E/flutter (20128): , null)
E/flutter (20128): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (20128): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter (20128): <asynchronous suspension>
E/flutter (20128): #2      DefaultAssetPickerProvider.getThumbnailFromPath (package:wechat_assets_picker/src/provider/asset_picker_provider.dart:440:34)
E/flutter (20128): <asynchronous suspension>
E/flutter (20128): 
E/PhotoManager(20128): get 11547 thumbnail error, width : 80, height: 80
E/PhotoManager(20128): java.io.FileNotFoundException: open failed: EFAULT (Bad address)
E/PhotoManager(20128): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
E/PhotoManager(20128): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:781)
E/PhotoManager(20128): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1985)
E/PhotoManager(20128): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1800)
E/PhotoManager(20128): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1477)
E/PhotoManager(20128): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.convertCursorToAssetEntity(AndroidQDBUtils.kt:257)
E/PhotoManager(20128): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.getAssetEntity(AndroidQDBUtils.kt:292)
E/PhotoManager(20128): 	at com.fluttercandies.photo_manager.core.PhotoManager.getThumb(PhotoManager.kt:91)
E/PhotoManager(20128): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$4.invoke(PhotoManagerPlugin.kt:266)
E/PhotoManager(20128): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$4.invoke(PhotoManagerPlugin.kt:262)
E/PhotoManager(20128): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.runOnBackground$lambda-0(PhotoManagerPlugin.kt:46)
E/PhotoManager(20128): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.lambda$bZa62ZrXsGssc32bPH4oVAuIci4(Unknown Source:0)
E/PhotoManager(20128): 	at com.fluttercandies.photo_manager.core.-$$Lambda$PhotoManagerPlugin$Companion$bZa62ZrXsGssc32bPH4oVAuIci4.run(Unknown Source:2)
E/PhotoManager(20128): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/PhotoManager(20128): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/PhotoManager(20128): 	at java.lang.Thread.run(Thread.java:923)
E/flutter (20128): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(201, get thumb error, java.io.FileNotFoundException: open failed: EFAULT (Bad address)
E/flutter (20128): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
E/flutter (20128): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:781)
E/flutter (20128): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1985)
E/flutter (20128): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1800)
E/flutter (20128): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1477)
E/flutter (20128): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.convertCursorToAssetEntity(AndroidQDBUtils.kt:257)
E/flutter (20128): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.getAssetEntity(AndroidQDBUtils.kt:292)
E/flutter (20128): 	at com.fluttercandies.photo_manager.core.PhotoManager.getThumb(PhotoManager.kt:91)
E/flutter (20128): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$4.invoke(PhotoManagerPlugin.kt:266)
E/flutter (20128): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$4.invoke(PhotoManagerPlugin.kt:262)
E/flutter (20128): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.runOnBackground$lambda-0(PhotoManagerPlugin.kt:46)
E/flutter (20128): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.lambda$bZa62ZrXsGssc32bPH4oVAuIci4(Unknown Source:0)
E/flutter (20128): 	at com.fluttercandies.photo_manager.core.-$$Lambda$PhotoManagerPlugin$Companion$bZa62ZrXsGssc32bPH4oVAuIci4.run(Unknown Source:2)
E/flutter (20128): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/flutter (20128): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/flutter (20128): 	at java.lang.Thread.run(Thread.java:923)
E/flutter (20128): , null)
E/flutter (20128): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (20128): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter (20128): <asynchronous suspension>
E/flutter (20128): #2      DefaultAssetPickerProvider.getThumbnailFromPath (package:wechat_assets_picker/src/provider/asset_picker_provider.dart:440:34)
E/flutter (20128): <asynchronous suspension>
E/flutter (20128): 
E/AndroidRuntime(20128): FATAL EXCEPTION: pool-2-thread-2
E/AndroidRuntime(20128): Process: com.example.veterans, PID: 20128
E/AndroidRuntime(20128): java.lang.Error: java.io.FileNotFoundException: open failed: EFAULT (Bad address)
E/AndroidRuntime(20128): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173)
E/AndroidRuntime(20128): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(20128): 	at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime(20128): Caused by: java.io.FileNotFoundException: open failed: EFAULT (Bad address)
E/AndroidRuntime(20128): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
E/AndroidRuntime(20128): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:781)
E/AndroidRuntime(20128): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1985)
E/AndroidRuntime(20128): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1800)
E/AndroidRuntime(20128): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1477)
E/AndroidRuntime(20128): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.convertCursorToAssetEntity(AndroidQDBUtils.kt:257)
E/AndroidRuntime(20128): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.access$convertCursorToAssetEntity(AndroidQDBUtils.kt:29)
E/AndroidRuntime(20128): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils$getAssetFromGalleryId$1$1.invoke(AndroidQDBUtils.kt:179)
E/AndroidRuntime(20128): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils$getAssetFromGalleryId$1$1.invoke(AndroidQDBUtils.kt:178)
E/AndroidRuntime(20128): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.cursorWithRange(AndroidQDBUtils.kt:140)
E/AndroidRuntime(20128): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.getAssetFromGalleryId(AndroidQDBUtils.kt:178)
E/AndroidRuntime(20128): 	at com.fluttercandies.photo_manager.core.PhotoManager.getAssetList(PhotoManager.kt:70)
E/AndroidRuntime(20128): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$2.invoke(PhotoManagerPlugin.kt:245)
E/AndroidRuntime(20128): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$2.invoke(PhotoManagerPlugin.kt:239)
E/AndroidRuntime(20128): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.runOnBackground$lambda-0(PhotoManagerPlugin.kt:46)
E/AndroidRuntime(20128): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.lambda$bZa62ZrXsGssc32bPH4oVAuIci4(Unknown Source:0)
E/AndroidRuntime(20128): 	at com.fluttercandies.photo_manager.core.-$$Lambda$PhotoManagerPlugin$Companion$bZa62ZrXsGssc32bPH4oVAuIci4.run(Unknown Source:2)
E/AndroidRuntime(20128): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(20128): 	... 2 more
I/Process (20128): Sending signal. PID: 20128 SIG: 9

**Comment by AlexV525** [comment]
Fixed by https://github.com/fluttercandies/flutter_photo_manager/pull/761. Closing.
