### ISSUE TITLE
[Feature] 增加选中资源的大小字段

### ISSUE THREAD

**Issue by 1203556555** [fluttercandies/flutter_wechat_assets_picker#325]
**Is your feature request related to a problem?**

我想要在选中资源的时候限制选中资源的大小。

**Describe the solution you'd like**

希望可以在AssetEntity中增加一个资源大小的字段

**Comment by 1203556555** [comment]
@AlexV525

**Comment by AlexV525** [comment]
Use `selectPredicate`.
