### ISSUE TITLE
[BUG] The list of unselected images will still be returned

### ISSUE THREAD

**Issue by vangeldu** [fluttercandies/flutter_wechat_assets_picker#328]
**Describe the bug**

After unselecting all images on the preview page, the list of unselected images will still be returned.

**How to reproduce**

1. Open the assets picker
2. Select three images
3. Click on the preview at the bottom left
4. Unselect all images
5. Click the Confirm button on the top right

**Expected behavior**

return empty images
**Screenshots (If contains)**

**Version information**

- Device: google pixel
- OS: Android 12
- Package Version: 7.1.0
- Flutter Version: 2.10.0

**Additional context**

**Comment by Bingbing0311** [comment]
iOS still has this problem

**Version information**

Device: iPhone 12 pro max
OS:iOS 14.8
Package Version: 7.3.1
Flutter Version: 3.0.0

**Comment by AlexV525** [comment]
> iOS still has this problem

Provide your usage code.

**Comment by Bingbing0311** [comment]
> > iOS still has this problem
> 
> Provide your usage code.

<img width="611" alt="image" src="https://user-images.githubusercontent.com/13670665/172558707-633fe5d2-aeaa-43c6-882c-5032aa64d8e8.png">
