### ISSUE TITLE
[BUG] Show "Load failed" when display image saved from WhatsApp

### ISSUE THREAD

**Issue by anderscheow** [fluttercandies/flutter_wechat_assets_picker#329]
**Describe the bug**
Show "Load failed" whenever try to preview the image saved from WhatsApp.

**How to reproduce**

1. Saved an image from WhatsApp
2. Open AssetPicker
3. Preview the saved image

**Expected behavior**

**Screenshots (If contains)**

![PHOTO-2022-05-31-16-58-51](https://user-images.githubusercontent.com/11788504/171136410-94edc873-2b3c-4ad3-ad4f-171c0cd14fb4.jpg)

**Version information**

- Device: Any Android device
- OS: Android (any version)
- Package Version: 7.1.2
- Flutter Version: 2.10.5

**Additional context**

**Comment by AlexV525** [comment]
Please make sure your `photo_manager` is using the latest version (2.1.2), and provide the exception log after using it.
