### ISSUE TITLE
[Missing feature] The image preview is missing the current selection 

### ISSUE THREAD

**Issue by PavieOlivier** [fluttercandies/flutter_wechat_assets_picker#33]
The header and bottom selection widgets are missing from the actual widget you provided, it makes it hard to select items only by using the small icon on the top: 
I am using android 10, OnePlus 7 Pro

|  Expected (given by you) | Current (on my phone)  |
| :------------: | :------------: |
| ![your work](https://github.com/fluttercandies/flutter_wechat_assets_picker/raw/master/screenshots/5.jpg "your work")  | ![what i get ](https://img.techpowerup.org/200620/image-2020-06-21-00-48-23.jpg "what i get ")  |

**Comment by AlexVincent525** [comment]
Hi, I've noticed that your viewer of the **Current** is under the mode what I called **"All assets preview mode"**, in this mode you can only see assets under your current path entity. And the preview mode in my introduce can only triggered by the preview button on the start of the bottom action bar.
![image](https://user-images.githubusercontent.com/15884415/85217772-d95f0100-b3c6-11ea-993b-d731b435de89.png)

The only way to select any unselected assets is to use the checkbox on the top end of the item, but its size is larger than you thought (maybe, see the screenshot). It can still be enlarged by setting more padding and align it more precisely.
![image](https://user-images.githubusercontent.com/15884415/85217727-9b61dd00-b3c6-11ea-9a93-670df2c54d49.png)

The reason why I didn't provide selection in the **"All assets preview mode"** is that we usually have hundreds and thousands of assets in our device. When you're previewing them in this mode, it's hard to pick some assets just using the swipe action, you still need to go back to the picker and pick them separately. Therefore I separate the behavior as two modes to provide accurate actions for the users.

Feel free to provide more informations and ideas about this behavior. 😄

**Comment by PavieOlivier** [comment]
Yess yess thank you
I was able to change the text color and almost get all settings done using themeData however i had to dig inside your code and some values are hard coded so I could not change them

Have a look at the Asset picker viewer
![app bar](https://img.techpowerup.org/200621/image-2020-06-21-13-58-02.jpg "app bar")

There is no way to change the color so i found this inside your code
![app bar code](https://img.techpowerup.org/200621/screen-shot-2020-06-21-at-1-44-42-pm.png "app bar code")

Also you talked about the padding of the button 
![padding](https://user-images.githubusercontent.com/15884415/85217727-9b61dd00-b3c6-11ea-9a93-670df2c54d49.png "padding")

How do you add more padding into it ? there is no easy way of doing that, there is no parameters in the constructor to add it. I alway accidently end up "NOT" selecting the picture en endding up on the asset previewer page.
So I checked the code again and i got into this.. can this be edited ?
I don't think i can fork the project right now and make the necessary changes.
![select indicator ](https://img.techpowerup.org/200621/screen-shot-2020-06-21-at-1-53-56-pm.png "select indicator ")

One last thing, I tried to change this color using the theme data i want the backdrop to be with a different color, i checked your code but i couldn't find the place where you colored this, can you please tell me which parameter of the themeData i shall change to achieve this without changing the app bar color ?
![app bar color](https://img.techpowerup.org/200621/image-2020-06-21-14-14-05.jpg "app bar color")

Thank you so much and sorry for asking too many questions

**Comment by AlexVincent525** [comment]
I found that you're asking about themes customization, there's an issue tracking about some related stuff at #32 . Check this and see if it helps.

The padding of the select indicator should be fixed as I thought, since there's no need to change this one commonly. I can enlarge the size to 1/4 or 1/3 of the top end area, what do you think?

**Comment by PavieOlivier** [comment]
> The padding of the select indicator should be fixed as I thought, since there's no need to change this one commonly. I can enlarge the size to 1/4 or 1/3 of the top end area, what do you think?

Yes please that would be nice 


> I found that you're asking about themes customization, there's an issue tracking about some related stuff at #32 . Check this and see if it helps.

I saw it sir,  **you hard coded the value to white it cannot be changed**.
Please, Sir can you read my previous question properly, I am pointing at places inside **your code** , not mine :) 

Sir you alse hard coded the value of the app bar color 
![your pic](https://camo.githubusercontent.com/4bbe94eaba57d4bc22f5b03c61076dc47dc4bca5/68747470733a2f2f696d672e74656368706f77657275702e6f72672f3230303632312f73637265656e2d73686f742d323032302d30362d32312d61742d312d34342d34322d706d2e706e67)

**This is your code** :(

**Comment by PavieOlivier** [comment]
also is it possible to have this orange black but the app bar orange?
![your pic](https://camo.githubusercontent.com/0ce802f0a5835de80018ad3c48fd2e48b88b8a88/68747470733a2f2f696d672e74656368706f77657275702e6f72672f3230303632312f696d6167652d323032302d30362d32312d31342d31342d30352e6a7067)

**Comment by AlexVincent525** [comment]
Let's see if we can expose more color customization.

**Comment by PavieOlivier** [comment]
ok ok thank you sir

**Comment by PavieOlivier** [comment]
Sir thank you for your help :)
I forked your project and made some changes to it (lots of changes) to meet my project requirements. I hope we will be able to edit pictures in the future

**Comment by PavieOlivier** [comment]
Sir thank you for your help :)
I forked your project and made some changes to it (lots of changes) to meet my project requirements. I hope we will be able to edit pictures in the future

**Comment by AlexVincent525** [comment]
> I hope we will be able to edit pictures in the future

There is a plan for editing assets, still needs more time to integrate with. We already have a [image editor](https://github.com/fluttercandies/flutter_image_editor).

**Comment by AlexVincent525** [comment]
> Yes please that would be nice

The size of the select indicator has been enlarged to 1/4 of the item, it should more accessible.

**Comment by PavieOlivier** [comment]
yes Thanks I saw this :)
