### ISSUE TITLE
Turkish Language Support

### ISSUE THREAD

**Issue by cevheri** [fluttercandies/flutter_wechat_assets_picker#330]
There is no Turkish language support.
 
**Version information**
➜  ~ flutter --version
Flutter 3.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fb57da5f94 (13 days ago) • 2022-05-19 15:50:29 -0700
Engine • revision caaafc5604
Tools • Dart 2.17.1 • DevTools 2.12.2

**Comment by AlexV525** [comment]
#28
