### ISSUE TITLE
TextDelegate的国际化问题

### ISSUE THREAD

**Issue by oliverchu** [fluttercandies/flutter_wechat_assets_picker#34]
![image](https://user-images.githubusercontent.com/13822928/85395786-428b7380-b583-11ea-9bb8-ea7a9686b59d.png)
也许不能这样定义TextDelegate，因为项目中用到了国际化，而国际化取对应的key的语言用到了context。建议使用普通的class来处理，传入固定的构造参数即可

**Comment by AlexVincent525** [comment]
Please fire the issue with issue template, ref #28 .
