### ISSUE TITLE
[BUG] Error with something

### ISSUE THREAD

**Issue by fuwuyuan** [fluttercandies/flutter_wechat_assets_picker#340]
**Describe the bug**

问题描述：IOS系统选择的图片，如果是HEIC格式上传到阿里云OSS提示不支持的格式（OSS告诉我某些图片是HEIC）。我尝试过自己做一遍转码，但是这带来的太多的开销，因为并不清楚图片的格式，只是对所有图片强制转码了（上传成功），性能极差。

**How to reproduce**

能否拓展一下AssetType，标识一下HEIC图片，或者看看库本身对HEIC的支持是否存在bug

**Screenshots (If contains)**

**Version information**

- Device: [e.g. iPhone X]
- OS: [e.g. iOS 14.7.1]
- Package Version: [e.g. 2.4.1]
- Flutter Version: [e.g. v2.5.0]

**Additional context**

**Comment by AlexV525** [comment]
显然你清楚格式。在调用 .originFile 后能获取到后缀名。也可以参考 AssetEntityImageProvider 进行判断。

**Comment by fuwuyuan** [comment]
> 显然你清楚格式。在调用 .originFile 后能获取到后缀名。也可以参考 AssetEntityImageProvider 进行判断。

已知晓~谢谢

**Comment by liraku** [comment]
> > 显然你清楚格式。在调用 .originFile 后能获取到后缀名。也可以参考 AssetEntityImageProvider 进行判断。
> 
> 已知晓~谢谢

可以问下现在是怎么处理的吗，flutter端怎么做的转码

**Comment by fuwuyuan** [comment]
> > > 显然你清楚格式。在调用 .originFile 后能获取到后缀名。也可以参考 AssetEntityImageProvider 进行判断。
> > 
> > 
> > 已知晓~谢谢
> 
> 可以问下现在是怎么处理的吗，flutter端怎么做的转码

OSS那边处理的
