### ISSUE TITLE
Module 'path_provider_ios' not found

### ISSUE THREAD

**Issue by onexuan** [fluttercandies/flutter_wechat_assets_picker#347]
add dependencies
wechat_assets_picker: ^7.3.4

but run ios, get this bug

Module 'path_provider_ios' not found

#import "GeneratedPluginRegistrant.h"

#if __has_include(<path_provider_ios/FLTPathProviderPlugin.h>)
#import <path_provider_ios/FLTPathProviderPlugin.h>
#else
@import path_provider_ios; //Module 'path_provider_ios' not found
#endif

**Comment by AlexV525** [comment]
#28
