### ISSUE TITLE
[BUG] Navigation bar's color unable to restored after the picker was dismissed

### ISSUE THREAD

**Issue by fangshengfy** [fluttercandies/flutter_wechat_assets_picker#35]
**Describe the bug (描述)**
 BottomNavigationBar color was changed after picker closed
**How to reproduce (如何复现)**
close picker

Steps to reproduce the behavior (描述复现步骤):

close picker

**Expected behavior (期望行为)**

**Screenshots (If contains) (是否有截图可以提供)**

**Device information (设备信息)**
 - Device: Android

**Additional context (附加信息)**
Add any other context about the problem here. 在此提供更多的内容。

**Comment by AlexVincent525** [comment]
Please provide the usage of your code.

**Comment by fangshengfy** [comment]
> Please provide the usage of your code.

  action(String name) async {
    if (name == '相册') {
      final List<AssetEntity> assets = await AssetPicker.pickAssets(context);
    } else if (name == '拍摄') {
      File file = await Navigator.push(
          context,
          MaterialPageRoute(
              builder: (context) => Camera(mode: CameraMode.fullscreen)));
    } else{
    }
  }

**Comment by fangshengfy** [comment]
BottomNavigationBar color from white to black

**Comment by fangshengfy** [comment]
it‘s ok after Lock screen

**Comment by fangshengfy** [comment]
test phone is redmi  7

**Comment by AlexVincent525** [comment]
Can you provide a smallest demo to reproduce the issue?

**Comment by fangshengfy** [comment]
> Can you provide a smallest demo to reproduce the issue?

import 'package:flutter/material.dart';
import 'package:wechat_assets_picker/wechat_assets_picker.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);


  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {


  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(

        title: Text(widget.title),
      ),
      body: Center(),
      floatingActionButton: FloatingActionButton(
        onPressed: ()async{
          final List<AssetEntity> assets = await AssetPicker.pickAssets(context);
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

**Comment by fangshengfy** [comment]
lock screen didn't fix it

**Comment by AlexVincent525** [comment]
I didn't found any `BottomNavigationBar` in here.
| Before | First Select | After | Second Select |
|--------|--------------------|-------|-----------------------|
| ![image](https://user-images.githubusercontent.com/15884415/85947202-c1195400-b97b-11ea-9ad6-d1d3a65a38d2.png) | ![image](https://user-images.githubusercontent.com/15884415/85947225-d8f0d800-b97b-11ea-86c4-4a6f79a83aa7.png) | ![image](https://user-images.githubusercontent.com/15884415/85947217-d1313380-b97b-11ea-929d-38311d8921f1.png) | 
![image](https://user-images.githubusercontent.com/15884415/85947235-e8702100-b97b-11ea-942e-04bec104490c.png) |

**Comment by fangshengfy** [comment]
[https://github.com/fangshengfy/react-ueditor/blob/master/Screenshot_2020-06-28-19-30-15-505_com.example.fl.jpg](url)

**Comment by fangshengfy** [comment]
![Uploading Screenshot_2020-06-28-19-32-38-685_com.example.fl.jpg…]()
![Screenshot_2020-06-28-19-30-15-505_com example fl](https://user-images.githubusercontent.com/32052317/85947459-63860700-b97d-11ea-8f4e-ff455cde2834.jpg)

**Comment by fangshengfy** [comment]
![Screenshot_2020-06-28-19-32-38-685_com example fl](https://user-images.githubusercontent.com/32052317/85947479-89aba700-b97d-11ea-9ecb-00aa1878bdf6.jpg)

**Comment by fangshengfy** [comment]
because your BottomNavigationBar is black

**Comment by AlexVincent525** [comment]
Cannot reproduce, because the code you have provided starts with a black navigator on my side.

**Comment by fangshengfy** [comment]
but redme 7 defalut color is white

**Comment by AlexVincent525** [comment]
Oh now it takes effect.

**Comment by AlexVincent525** [comment]
Finish investigation, ref [flutter/40590](https://github.com/flutter/flutter/issues/40590) .

Add below line into the `main` method which will be:

```dart
void main() {
  runApp(MyApp());
  WidgetsBinding.instance.renderView.automaticSystemUiAdjustment = false;
}
```

**Comment by fangshengfy** [comment]
before
![Screenshot_2020-06-28-21-25-35-463_com example pr](https://user-images.githubusercontent.com/32052317/85948945-51f52d00-b986-11ea-94ac-70727d97e7a3.jpg)
after
![Screenshot_2020-06-28-21-27-11-692_com example pr](https://user-images.githubusercontent.com/32052317/85948946-56b9e100-b986-11ea-9660-4462c915a529.jpg)
to be honest，it is not a best solution

**Comment by AlexVincent525** [comment]
You can use a light theme to implement your picker, rather than a dark version.

**Comment by AlexVincent525** [comment]
Though, it's not an issue from the picker. :-)

**Comment by fangshengfy** [comment]
void main()  {
  WidgetsBinding.instance.renderView.automaticSystemUiAdjustment = false;
  runApp(createApp());
}

Color barColor;
  @override
  initState() {
    super.initState();
    FlutterStatusbarcolor.getNavigationBarColor().then((value) {
      barColor = value;
    });
  }

    if (barColor != null) {
        if (barColor.value == Colors.white.value) {
          //底部为白色
          await FlutterStatusbarcolor.setNavigationBarColor(Colors.black);
          await FlutterStatusbarcolor.setNavigationBarWhiteForeground(true);
          //状态栏的前景色需要区别，我的状态栏是白底黑字
          await FlutterStatusbarcolor.setStatusBarWhiteForeground(true);
          final List<AssetEntity> assets =
              await AssetPicker.pickAssets(context);
          //状态栏的前景色需要区别，我的状态栏是白底黑字
          await FlutterStatusbarcolor.setStatusBarWhiteForeground(false);
          await FlutterStatusbarcolor.setNavigationBarColor(barColor);
          await FlutterStatusbarcolor.setNavigationBarWhiteForeground(false);
        } else {
          //底部为黑色
          await FlutterStatusbarcolor.setNavigationBarColor(Colors.white);
          await FlutterStatusbarcolor.setNavigationBarWhiteForeground(false);
          //状态栏的前景色需要区别
          await FlutterStatusbarcolor.setStatusBarWhiteForeground(true);
          final List<AssetEntity> assets =
              await AssetPicker.pickAssets(context);
          //状态栏的前景色需要区别
          await FlutterStatusbarcolor.setStatusBarWhiteForeground(false);
          await FlutterStatusbarcolor.setNavigationBarColor(barColor);
          await FlutterStatusbarcolor.setNavigationBarWhiteForeground(true);
        }
      }

it is my current solution

**Comment by AlexVincent525** [comment]
The `pickerTheme` property provided the ability to set the brightness to the status bar and the navigation bar.

Locking this until the official one is resolved.
