### ISSUE TITLE
[BUG] 鸿蒙系统点击无反应

### ISSUE THREAD

**Issue by liranhao** [fluttercandies/flutter_wechat_assets_picker#350]
其他安卓和iOS正常，鸿蒙系统测了两部手机都不行
使用版本：wechat_assets_picker: 7.2.0
flutter版本：2.10.5
![image](https://user-images.githubusercontent.com/15797388/186051916-5c06ce98-0758-44d9-8c4b-0882884719b7.png)

https://user-images.githubusercontent.com/15797388/186051947-0948c306-d424-464a-8dc3-e10d723d4396.mp4

**Comment by AlexV525** [comment]
#28
