### ISSUE TITLE
[BUG] iOS系统，预览10M的图片加载不出来，选中，不选中图片，崩溃

### ISSUE THREAD

**Issue by wglios** [fluttercandies/flutter_wechat_assets_picker#351]
崩溃信息：
libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
* thread #11, name = 'io.flutter.1.io', stop reason = signal SIGABRT
    frame #0: 0x00000001b8435964 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1b8435964 <+8>:  b.lo   0x1b8435984               ; <+40>
    0x1b8435968 <+12>: pacibsp 
    0x1b843596c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1b8435970 <+20>: mov    x29, sp
Target 0: (Runner) stopped.

flutter版本: 
Flutter (Channel stable, 3.0.5, on macOS 12.0.1 21A559 darwin-arm (Rosetta), locale zh-Hans-CN)

插件版本: 8.0.0

**Comment by AlexV525** [comment]
提供稳定复现的图片。

**Comment by AlexV525** [comment]
同时，调整 `previewThumbnailSize` 后再次尝试。

**Comment by wglios** [comment]
当我设置了previewThumbnailSize值，图片会变的很模糊，我想图片大小大于一定的值时，设置previewThumbnailSize，否则显示原图

**Comment by AlexV525** [comment]
将数值调高。

**Comment by wglios** [comment]
当我在相册中快速点击某个照片时，会崩溃 @AlexV525 
 
![image](https://user-images.githubusercontent.com/12129958/187345488-8adcf0ae-215c-4bb6-a9ab-b25a62a5ec24.png)
<img width="845" alt="image" src="https://user-images.githubusercontent.com/12129958/187345560-562a72d7-8d78-4b1d-9dcb-883d67698dd3.png">
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/12129958/187345583-b3694495-627d-4e3b-b6b2-c6c46d4fa146.png">

**Comment by AlexV525** [comment]
需求问题与本 package 无关。
