### ISSUE TITLE
[BUG] UI display error after deleting photo. (删除照片后，UI显示错误)

### ISSUE THREAD

**Issue by ycrep** [fluttercandies/flutter_wechat_assets_picker#358]
Describe the bug
UI display error after deleting photo.
照片从手机中删除后，app切换相册目录时UI显示错误。

How to reproduce
Use the example from the project.
使用官方项目中的 example。

case A: Screenshots 1 (如图1所示)
1. Click on 'Custom' tab item
2. Click on 'Multi tab picker'
3. Click on 'Call the Picker'
4. Select first photo in Recents (选中照片)
5. Switch to another path (切换目录)
6. Delete the selected photo in step 4 (删除步骤4选中的图片)
7. Switch path to Recents (切换目录至 Recents)
8. Display error: photo is hide but selected list is not update (图片不显示，但是数量未更新)

case B: Screenshots 2 (如图2所示)
1...
2...
3...
4. Delete all photo in 'A' path (删除目录A中的所有照片)
5. Switch to path 'A' (切换目录至A) 
6. It's always loading (一直在加载中)
7. Can't switch path (不能切换目录)

Expected behavior
like WeChat: Photos are still displayed after being deleted.
跟微信类型：照片从手机中删除后，app切换相册目录时，该照片仍然显示。

Screenshots
![Simulator Screen Shot - iPhone 13 - 2022-09-08 at 14 56 22](https://user-images.githubusercontent.com/16078340/189055365-d00fb3cc-5f7f-43d2-87c1-e6460d3b8973.png)
![Simulator Screen Shot - iPhone 13 - 2022-09-08 at 15 48 41](https://user-images.githubusercontent.com/16078340/189065942-b8204a1d-5c7b-491d-ae87-cc1024fa8f2b.png)

Version information
- Device: iPhone 6P or Simulator
- OS: iOS 15
- Package Version: 8.0.2
- Flutter Version: v3.0.0

Additional context
1、猜测为切换目录时，更新目录下的资源导致。
2、微信中删除照片，仍然可以选择，并且可以正常发送。
3、建议跟微信类似，如果删除照片后，切换目录时更新资源，可能会导致其他UI显示错误: 当前页面的刷新问题、目录列表的刷新问题、选中状态的更新问题等。
4、安卓手机未测试。

**Comment by AlexV525** [comment]
你使用的是自定义的 tab 示例，请切换至首页的示例再进行测试。

**Comment by ycrep** [comment]
> 你使用的是自定义的 tab 示例，请切换至首页的示例再进行测试。

首页的 Image picker，效果是一样的。
