### ISSUE TITLE
[BUG] 安装报错 Android embedding v2

### ISSUE THREAD

**Issue by zhangweiwei0326** [fluttercandies/flutter_wechat_assets_picker#36]
**Describe the bug (描述)**

Running "flutter pub get" in byapp...                               1.2s
The plugin `assets_audio_player` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.
exit code 1

**Device information (设备信息)**
• Flutter version 1.17.3
    • Framework revision b041144f83 (2 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

**Additional context (附加信息)**
Add any other context about the problem here. 在此提供更多的内容。

**Comment by AlexVincent525** [comment]
Plugin require your flutter project to upgrade with Android Embedding v2.
