### ISSUE TITLE
[BUG] don't has confirm button in thumbnail pages on Android when in singleAssetMode

### ISSUE THREAD

**Issue by hellohejinyu** [fluttercandies/flutter_wechat_assets_picker#366]
**Describe the bug**

Android user can't select single asset in thumbnail page. Because there don't has confirm button.

<img width="703" alt="image" src="https://user-images.githubusercontent.com/8766034/191205375-a50f0f4d-0ff9-4aa7-bd95-24b1d17e6bed.png">

I see some comments like above. So I am not sure it's a bug or not.

**Expected behavior**

Has a confirm button in thumbnail page.

**Screenshots (If contains)**

https://user-images.githubusercontent.com/8766034/191204823-967f04b9-4ab1-4c8a-a103-62f8459e657d.mp4

**Version information**

- Device: Honor
- OS: Android 10
- Package Version: 8.1.0
- Flutter Version: 3.3.2

**Comment by hellohejinyu** [comment]
https://user-images.githubusercontent.com/8766034/191206874-bf6235ab-eb63-4a1a-acf1-33bf5e526df7.mp4

I found a previous version of the app and it was working fine

**Comment by AlexV525** [comment]
Thanks, `!isSingleAssetMode` should be `isPreviewEnabled` here.

**Comment by AlexV525** [comment]
@all-contributors Add @hellohejinyu for bugs.
