### ISSUE TITLE
[Feature] 希望增加根据类型区分maxAssets

### ISSUE THREAD

**Issue by zhangweiwei0326** [fluttercandies/flutter_wechat_assets_picker#37]
**Version information (版本信息)**
 - Device: *e.g. iPhone6*
 - OS: *e.g. iOS 13.4*
 - Package Version: *e.g. v2.1.0*
 - Flutter Version: *e.g. v1.17.1*

**Describe the solution you'd like (描述你期望的解决方案)**
比如：requestType 为RequestType.common时，希望如果用户选择视频只能选1个，但是选择图片的话就可以选择9个
**Describe alternatives you've considered (其他解决方案或疑虑)**

**Additional context (附加内容)**

**Comment by AlexVincent525** [comment]
> 我调研了一下微信的朋友圈选择资源，一共有两种情况：
> 
> 选择视频后，无法再进行选择。目前暂时还无法达成，因为对于所有资源来说都可以多选，后面可以加一个完全匹配微信的模式，但是选择视频确认后不能再选图片是由你自己控制的，屏蔽入口即可。

Is the case that you're talking about?

**Comment by AlexVincent525** [comment]
Some other developers are asking for this implementation, so the feature is started developing when there's no respond from the author.
