### ISSUE TITLE
[BUG] Don't have confirm button in thumbnail pages on Android when in multiAssetMode

### ISSUE THREAD

**Issue by mongugay** [fluttercandies/flutter_wechat_assets_picker#370]
**Describe the bug**
After selecting several photos in preview mode, the confirmation button does not appear.

1. Multi
2. No preview
3. Selected several photos.

**Expected behavior**
Has a confirm button in thumbnail page.

**Screenshots (If contains)**

https://user-images.githubusercontent.com/1773504/193616791-5958d2aa-8fcc-458c-8262-ca8797478e14.mp4

**Version information**

- Device: Samsung a51
- OS: Android 11
- Package Version: 8.1.1
- Flutter Version: 3.0.5

**Comment by AlexV525** [comment]
Sorry for the bad code. I've added tests to avoid it and hope it won't happen again.
