### ISSUE TITLE
[BUG] Custom MultiTab Picker not loading more pages

### ISSUE THREAD

**Issue by isigr57** [fluttercandies/flutter_wechat_assets_picker#372]
Hello everyone,

The custom implementation of the Multi Tab Picker is not loading pages properly when there are more items to load. I've tested with the app example on iOS and Android.

**Comment by Tpow99** [comment]
Any update on this?

**Comment by Tpow99** [comment]
@isigr57 I was able to fix the issue with the following: 



`import 'package:wechat_assets_picker/wechat_assets_picker.dart';

class MyPickerProvider extends DefaultAssetPickerProvider {
  MyPickerProvider({
    super.selectedAssets,
    super.maxAssets,
    super.pageSize,
    super.pathThumbnailSize,
    Duration initializeDelayDuration = const Duration(milliseconds: 250),
  }) {
    // Call [getAssetList] with route duration when constructing.
    Future<void>.delayed(initializeDelayDuration, () async {
      await getPaths();
      await getAssetsFromCurrentPath();
    });
  }


  @override
  Future<void> loadMoreAssets() async {
    print("called");
    await getAssetsFromPath();
  }
}
`

**Comment by Tpow99** [comment]
Then use your own picker instead of the default
