### ISSUE TITLE
黑屏转圈,权限已开

### ISSUE THREAD

**Issue by gyyxiaogao** [fluttercandies/flutter_wechat_assets_picker#378]
**Describe the bug**

本地图片出现预览转圈的问题
**How to reproduce**

![image](https://user-images.githubusercontent.com/16957066/200308109-6bfa6beb-3ef7-4de9-b5f9-cc570da9eb4b.png)
![image](https://user-images.githubusercontent.com/16957066/200308134-7b004fed-42cf-47e1-bea2-aed0cc05eba6.png)

4. Error occurred.

**Expected behavior**

**Screenshots (If contains)**

**Version information**

- Device: [e.g. iPhone X]
- OS: [e.g. iOS 14.7.1]
- Package Version: [e.g. 2.4.1]
- Flutter Version: [e.g. v2.5.0]

**Additional context**

**Comment by hhgz9527** [comment]
你好，想问下这个后续解决了吗？

**Comment by canyuegongzi** [comment]
解决了吗

**Comment by tiangaopan** [comment]
解决了吗
