### ISSUE TITLE
列表为空

### ISSUE THREAD

**Issue by gyyxiaogao** [fluttercandies/flutter_wechat_assets_picker#379]
**Describe the bug**

**How to reproduce**

4. Error occurred.

**Expected behavior**

**Screenshots (If contains)**

**Version information**

- Device: [e.g. iPhone X]
- OS: [e.g. iOS 14.7.1]
- Package Version: [e.g. 2.4.1]
- Flutter Version: [e.g. v2.5.0]

**Additional context**

**Comment by chenenyu** [comment]
photo_manager 2.5.2的改动会导致android上概率性的缩略图加载不出来

**Comment by chenenyu** [comment]
@AlexV525 @gyyxiaogao
