### ISSUE TITLE
[Feature] Add Click the title bar to scroll to the top

### ISSUE THREAD

**Issue by lcm1475** [fluttercandies/flutter_wechat_assets_picker#380]
**Version information**
 - Device: *e.g. iPhone 13*
 - OS: *e.g. iOS 14.7.1*
 - Package Version: *e.g. v2.4.1*
 - Flutter Version: *e.g. v3.0.0*

**Is your feature request related to a problem?**

no

**Describe the solution you'd like**

There may be a large number of photos in the album. If you want to find the previous photos, you need to slide for a long time. Add the title bar and click to slide to the top

**Describe alternatives you've considered**

Flutter or iOS native scrolling list supports this function

**Additional context**

no

**Comment by AlexV525** [comment]
In the picker, the grid is reverted on iOS by default, which is at the top position of the grid. The scroll-to-top behavior is not suitable in this case.
