### ISSUE TITLE
[BUG] Empty list shown when device has folders containing pictures

### ISSUE THREAD

**Issue by ayomessenger** [fluttercandies/flutter_wechat_assets_picker#388]
**Describe the bug**
Asset picker shows 'Empty list' even though device has pictures in library

**How to reproduce**
Called with: 

``` dart
await AssetPicker.pickAssets(
      context,
      pickerConfig: AssetPickerConfig(
        requestType: RequestType.image,
    ),
);
```

permissions in AndroidManifest:

`    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"  />
`

1. Open the asset picture
2. Empty list is dipslayed

**Expected behavior**
The device files containing images to be displayed.

**Screenshots (If contains)**
![image](https://user-images.githubusercontent.com/99839615/203649569-2d055cb1-a337-4d3f-a5b1-a603138bcfbf.png)

**Version information**

- Device: Google Pixel 6
- OS: Android 13
- Package Version: 8.1.4
- Flutter Version: 3.6.0

**Additional context**
This package used to work with 7.3.2 but now I checkout this version still this unexpected 'Empty list' behaviour occurs. I couldn't say what changed since then, Android Version? An incompatible image type?

**Comment by AlexV525** [comment]
Please verify if the example is working on your phone.

**Comment by ayomessenger** [comment]
If this messages intended for me? If so, I don't understand what you want me to test

**Comment by AlexV525** [comment]
Use the example of the package to test if the issue is reproducible.

**Comment by ayomessenger** [comment]
Oh okay, I just tried the example and that worked. So I added the filter `AssetPickerConfig` with only on images, and now this works as well. I don't really understand how to be honest but it works now so thanks for your help.

**Comment by ayomessenger** [comment]
It worked briefly, but after the next build the same behaviour started appearing...

I tried with the example and still get the same 'Empty List' screen.

**Comment by AlexV525** [comment]
Is your Pixel 6 an emulator or a real device? I can't reproduce the issue on my Android 13 device (OnePlus 9 Pro).
![1553c718a2a3b354f59ad6cc8ae81ca](https://user-images.githubusercontent.com/15884415/203994262-d6a98c14-1e5d-4801-a1cc-e2e173dadb9c.jpg)

**Comment by ayomessenger** [comment]
I'm also working with a real device with Android 13

**Comment by Danzzel** [comment]
I have the same issue on 13 Android. Just empty screen...

**Comment by AlexV525** [comment]
I've double-checked the configuration in the example and found no issues. Please help to identify the root cause by following steps:
1. Update the cloned repo to the latest (e0951d4) and revert all local changes (if any).
2. Run `flutter clean`, delete `build` and `example/build` folders, and run `flutter pub upgrade` for the package and the example, make sure the `photo_manager` is resolved as `2.5.0` in the `pubspec.lock`.
3. If the issue persists, open the logcat and filter all logs related to `PhotoManager` and paste them into a log file, then upload them to this thread.

> I'm also working with a real device with Android 13

> I have the same issue on 13 Android. Just empty screen...

@ayomessenger @Danzzel Please both provide full device information and an extra screen recording when testing with the example. Thanks.

**Comment by AlexV525** [comment]
Also please try to add the `android.permission.READ_EXTERNAL_STORAGE` permission to the manifest.

**Comment by Danzzel** [comment]
![Screenshot 2022-11-26 at 12 37 22](https://user-images.githubusercontent.com/75837219/204085804-028c1113-9986-4648-aeca-10b069811fa8.png)
![Screenshot 2022-11-26 at 12 37 50](https://user-images.githubusercontent.com/75837219/204085805-7cc88fe2-bcc0-41a3-95d8-0914396738b0.png)

https://user-images.githubusercontent.com/75837219/204085799-806f683e-ed3a-
[Untitled.docx](https://github.com/fluttercandies/flutter_wechat_assets_picker/files/10096089/Untitled.docx)
4c43-a85e-22090bc2e34b.mp4

I testing on a real device, a Google Pixel 5a
my logs in doc
Thank you for trying to help me.

**Comment by Danzzel** [comment]
[]

https://user-images.githubusercontent.com/75837219/204085986-20d20663-d6f9-4598-bb08-073857daac6e.mp4

(url)

**Comment by AlexV525** [comment]
>  video_2022-11-26_13-05-55.mp4

@Danzzel Please provide full device information and an extra screen recording when **testing with the example**.

Also, please try to add the `android.permission.READ_EXTERNAL_STORAGE` permission to the manifest.

**Comment by Danzzel** [comment]
@AlexV525 I added this permission, you can see it upper on one of my screenshots. And, of course, I can do a new record, but maybe you want to see some specific data or moments?

**Comment by AlexV525** [comment]
No. Because when you're involving too many variants of configurations, it'll be hard to figure out what's wrong here.

BTW, the `targetSdkVersion` and `compileSdkVersion` matters, upgrade them to `33` if they aren't `33`.

**Comment by Danzzel** [comment]
@AlexV525 now I have compileSdkVersion = 33 and  targetSdkVersion = 31. I'll try to upgrade targetSdkVersion to 33 and I will write the result with other details

**Comment by Danzzel** [comment]
@AlexV525 Your truth, with targetSdkVersion 33 it's working.
 Thanks a lot, you cool guy!)))

**Comment by ayomessenger** [comment]
Just to confirm for me as well. Upgrading the `targetSdkVersion` to 33 also did the trick, thanks everyone :)

**Comment by AlexV525** [comment]
This is now explained in the README since 434ab29.

**Comment by rlee1990** [comment]
@AlexV525 is there a way around setting the target device to 33? There is an issue with the camera when set to 33 
[Issue](https://github.com/flutter/flutter/issues/109769)

**Comment by AlexV525** [comment]
> @AlexV525 is there a way around setting the target device to 33? There is an issue with the camera when set to 33 

No workaround unless you use a fork camera plugin.
