### ISSUE TITLE
[Feature] Take picture with Camera in list image picker

### ISSUE THREAD

**Issue by nhtlquan** [fluttercandies/flutter_wechat_assets_picker#39]
**Version information (版本信息)**
 - Device: *e.g. iPhone6*
 - OS: *e.g. iOS 13.4*
 - Package Version: *e.g. v2.1.0*
 - Flutter Version: *e.g. v1.17.1*

**Is your feature request related to a problem?  (功能是否与已有问题关联)**
Capture camera.

**Describe the solution you'd like (描述你期望的解决方案)**
Capture camera when picker multi image, insert one more button on index 0 of list image picker!

**Describe alternatives you've considered (其他解决方案或疑虑)**

**Additional context (附加内容)**

**Comment by AlexVincent525** [comment]
Is it okay if you put an option before pick assets to let users choose to take camera or pick assets?

**Comment by nhtlquan** [comment]
> Is it okay if you put an option before pick assets to let users choose to take camera or pick assets?

I know, but Design and BA need take picture from gridview Image! Please help me.
I have tried adding an item camera in the gridview . But when I took a picture and reloaded the image from getAssetsFromEntity. But it takes about 10 seconds for new images to appear. :(

**Comment by AlexVincent525** [comment]
> But when I took a picture and reloaded the image from getAssetsFromEntity. But it takes about 10 seconds for new images to appear. :(

Have you tried to add `AssetEntity` through photo manager? Ref: https://github.com/CaiJingLong/flutter_photo_manager#insert-new-item

Provide the ability to customize the first or the last item is better than provide a camera shooting as I thought. But still, it needs some time to investigate and implement.

**Comment by nhtlquan** [comment]
`  void takeCamera() async {
    final file = await ImagePicker.pickImage(source: ImageSource.camera);
    if (file == null) {
      return;
    }
    final Uint8List byteData = await file.readAsBytes(); // Convert to Uint8List
    final AssetEntity imageEntity = await PhotoManager.editor.saveImage(byteData);
    provider.addAssetCamera(imageEntity);
    _isLoadingSubject.sink.add(true);
  }`
I tried, but not work. On pixel 3 XL, android 10.

**Comment by AlexVincent525** [comment]
> I tried, but not work. On pixel 3 XL, android 10.

Which part didn't worked? Returned null? Or a error thrown?

/cc @CaiJingLong

**Comment by nhtlquan** [comment]
> > I tried, but not work. On pixel 3 XL, android 10.
> 
> Which part didn't worked? Returned null? Or a error thrown?
> 
> /cc @CaiJingLong
Take 1 picture with camera => open grid image with _flutter_wechat_assets_picker_ ==> 
photo just taken not appear
==> need wait 10 second or take one more picture with camera ==> item will be appear

**Comment by nhtlquan** [comment]
Sorry bro, I made a mistake.

**Comment by nhtlquan** [comment]
Hi bro, Please update new feature: Take camera in grid view list image!

**Comment by AlexVincent525** [comment]
Is there any problem currently when you're trying to integrate with *photo_manager* ?

**Comment by AlexVincent525** [comment]
Try `3.0.0-dev.1` .

**Comment by AlexV525** [comment]
Published in `3.0.0` .
