### ISSUE TITLE
[BUG] Padding issue in MultiTabs delegate example on iOS

### ISSUE THREAD

**Issue by LeGoffMael** [fluttercandies/flutter_wechat_assets_picker#395]
**Describe the bug**
There is an unnecessary padding at the top of the grid view in the `MultiTabAssetPickerBuilder` example on iOS.

**How to reproduce**
Run the `MultiTabAssetPickerBuilder` example on an iPhone.

**Expected behavior**
The grid view and the path list dropdown widget should be stick to the top of the view.

It seems that it comes from `kToolbarHeight` at line [1197](https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/main/lib/src/delegates/asset_picker_builder_delegate.dart#L1193) and [1593](https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/main/lib/src/delegates/asset_picker_builder_delegate.dart#L1593) of DefaultAssetPickerBuilderDelegate.

Remove it fix the issue for MultiTabAssetPickerBuilder but the problem of padding appear on the commun pickers when `shouldRevertGrid: false`.

i could fixed it with an ugly fix, but it is definitely not ideal.
```dart
MediaQuery(
  data: MediaQuery.of(context).copyWith(
    padding: const EdgeInsets.only(top: -kToolbarHeight),
  ),
  child: Builder(
    builder: (BuildContext context) => Stack(
      children: <Widget>[
        RepaintBoundary(
          child: Column(
            children: <Widget>[
              Expanded(child: assetsGridBuilder(context)),
              if (isPreviewEnabled) bottomActionBar(context),
            ],
          ),
        ),
        pathEntityListBackdrop(context),
        pathEntityListWidget(context),
      ],
    ),
  ),
)
```

**Screenshots (If contains)**
the blue arrow shows the top padding
| grid view | albums list |
| -- | -- |
| <img src="https://user-images.githubusercontent.com/22376981/207527948-d341e9b9-0f1a-4e13-8498-ac33bb5224af.jpeg" height=600 /> | <img src="https://user-images.githubusercontent.com/22376981/207525866-742da9a7-ef4b-46cf-9299-9c29dab1e8de.PNG" height=600 /> |

**Version information**

- Device: iPhone 11 pro
- OS: 16.1.1
- Package Version: master branch, 8.2.0
- Flutter Version: 3.3.9

**Comment by AlexV525** [comment]
This is likely caused by extra calculations when reverting the asset grid. I didn't pay too much caution when writing the multi-tab example.
