### ISSUE TITLE
[Feature] custom usage as a widget

### ISSUE THREAD

**Issue by SchnMar** [fluttercandies/flutter_wechat_assets_picker#40]
Dear Alex,

**Describe the solution you'd like (描述你期望的解决方案)**
I would like to use the assets_picker to develop a custom application behaviour(similar to instagram-share-behaviour).
First, I want to show the asset picker using a ```Navigator.of(context, rootNavigator: true).push```. When the user presses the confirmation button on the top right side I want to push a follow up page on which a user can edit a post by adding some text and some additional information and remove assets from the current asset selection. 
On top of that, I want to be able to use the back chevron of Navigator to return to the assets_picker using the typical Navigator back behaviour and not by doing another ```Navigator.of(context, rootNavigator: true).push```.

**Describe alternatives you've considered (其他解决方案或疑虑)**
I've considered extracting some logic of AssetPicker, but I keep running in to errors.

**Solution proposal**
Provide a way to use the assets_picker as a widget additionally to the already implemented push-behaviour.

Can you please help me out on this? 

If you need additional information, please let me know.
Thank you!

**Comment by SchnMar** [comment]
I tried adding the functionality by adding the following method to asset_picker.dart

```
  static Widget createAssetPicker(
    BuildContext context, {
    Key key,
    int maxAssets = 9,
    int pageSize = 320,
    int pathThumbSize = 200,
    int gridCount = 4,
    RequestType requestType = RequestType.image,
    List<AssetEntity> selectedAssets,
    Color themeColor,
    ThemeData pickerTheme,
    SortPathDelegate sortPathDelegate,
    TextDelegate textDelegate,
    Curve routeCurve = Curves.easeIn,
    Duration routeDuration = const Duration(milliseconds: 300),
    Function successCallback,
  }) {
    if (maxAssets == null || maxAssets < 1) {
      throw ArgumentError('maxAssets must be greater than 1.');
    }
    if (pageSize != null && pageSize % gridCount != 0) {
      throw ArgumentError('pageSize must be a multiple of gridCount.');
    }
    if (pickerTheme != null && themeColor != null) {
      throw ArgumentError(
          'Theme and theme color cannot be set at the same time.');
    }
    try {
      final AssetPickerProvider provider = AssetPickerProvider(
        maxAssets: maxAssets,
        pageSize: pageSize,
        pathThumbSize: pathThumbSize,
        selectedAssets: selectedAssets,
        requestType: requestType,
        sortPathDelegate: sortPathDelegate,
        routeDuration: routeDuration,
      );
      final Widget picker = AssetPicker(
        key: key,
        provider: provider,
        gridCount: gridCount,
        textDelegate: textDelegate,
        themeColor: themeColor,
        pickerTheme: pickerTheme,
        successCallback: successCallback,
      );

      return picker;
    } catch (e) {
      realDebugPrint('Error when calling assets picker: $e');
      return null;
    }
  }
```

When I use this method in my current flow, I get the following exception on the following page:

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building Selector<AssetPickerProvider, List<AssetEntity>>(dirty, dependencies: [_InheritedProviderScope<AssetPickerProvider>], state: _Selector0State<List<AssetEntity>>#042c8):
The getter 'length' was called on null.
Receiver: null
Tried calling: length

The relevant error-causing widget was: 
  *****
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      AssetPicker.assetsGrid.<anonymous closure> (package:wechat_assets_picker/src/widget/asset_picker.dart:838:40)
#2      _Selector0State.buildWithChild (package:provider/src/selector.dart:84:29)
#3      SingleChildState.build (package:nested/nested.dart:318:41)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by AlexVincent525** [comment]
I remember that this feature has already brought by #19 . Is there any difference between them?

**Comment by AlexVincent525** [comment]
Can you provide a GIF about what Instagram's behavior is?

**Comment by SchnMar** [comment]
Thank you for your fast reply!

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12902321/87098547-d88ff100-c247-11ea-85a2-773f93cf68e4.gif)

Here is a gif of the instagram application flow. The specific details are:

- Share Button pushes a full page view of their share page displaying pictures & videos on device. 
- Next Button displays image editing functionality (not needed)
- next button display posting mechanism where you can enter a post text
- back button is available and selected assets can be changed. 

Hope this helps to understand the functionality.

The difference to #19 is that I now want some follow up pages to asset picker on the same Navigator level, which is difficult at the moment as described. In #19 I just needed rootLevelNavigator.

Thank you!

**Comment by AlexVincent525** [comment]
I'll try to understand when I have more time. For now the error you've provided might related to the new constructor and the static methods while they have parameters change after `3.0.0-dev.1` . Please read the document for more information about them.

**Comment by AlexVincent525** [comment]
Also read the source code too. :)

**Comment by AlexV525** [comment]
I've checked the process you described, and the simplified result I got is:
`Page A => Picker <=> Publish Page`

Therefore there's no further implementation I should take, following below reasons:
* You can start the picker using the `SchedulerBinding.instance.addPostFrameCallback` to call a picker in the publish page, rather than create a page to integrate with the picker.
* When the picker is called from the publish page, judge the return value from the picker because it'll return `null` when you press back from the picker. (e.g. `if (result == null) pop` )
* When you pressed the back button in the publish page, override it's `onPressed` to call the picker.

Using these steps are enough for you requirement as I thought. If you have anything still makes you confusing, please feel free to ask.

Closing this because it can be implement from the user end.

**Comment by SchnMar** [comment]
Thank you for your help!

Unfortunately, this leads to the Publish Page being displayed for half a second and the Picker appears. Is there a trick?

**Comment by AlexV525** [comment]
Sure, you can make the publish page as an transparent route first, then control the state of it to make it visible.

**Comment by SchnMar** [comment]
Thank you for the advice. Now it's looking good!
