### ISSUE TITLE
[BUG] RequestType.video does not select only videos

### ISSUE THREAD

**Issue by MartinSchultz** [fluttercandies/flutter_wechat_assets_picker#404]
**Describe the bug**
Setting the parameter requestType in an AssetPickerConfig does not work correctly if set to RequestType.video. If set to video, it shows "recent" in the top drop down and one can select photos AND videos. It works fine on the simulator, but on a real device it selects by default all types and recent photos by default. 
The other way around works: If I set it to photos only, videos are not visible nor selectable.

**How to reproduce**
final List<AssetEntity>? result = await AssetPicker.pickAssets(
      context,
      pickerConfig: AssetPickerConfig(
        requestType: RequestType.video, // <---- will not limit to videos nor select videos by default. Also photos selectable
        maxAssets: 10,
      )
// NOTE: Works proper in iOS simulator 16.1.2, on 16.1.2 device it does NOT work. 

1. Add assetPickerConfig like above to your code
2. Deploy to device
3. Open asset picker dialog
4. Error occurred, shows "recent" and photos + videos

**Expected behavior**
If setting type to video, only videos should be shown and no photos categories can be selected.

**Screenshots (If contains)**
![IMG_FE2631265663-1-1](https://user-images.githubusercontent.com/1279889/211488406-f38d2e6e-9079-4741-9529-c3884d51533e.jpeg)
![IMG_FE2631265663-2-2](https://user-images.githubusercontent.com/1279889/211488418-32aa74d1-7988-4ab4-8977-bca84ee5c27e.jpeg)

**Version information**

- Device: iPhone 12
- OS: iOS 16.1.2
- Package Version: 8.3.0
- Flutter Version: Flutter 3.3.6 stable

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/5de0dd8de5d4cadc087d5e2bcde4e258bf44fc3e/README.md?plain=1#L296-L299
