### ISSUE TITLE
[QUESTION] Size of image picked

### ISSUE THREAD

**Issue by baptistesx** [fluttercandies/flutter_wechat_assets_picker#420]
Hi there!

i got a question:

When i pick a image from the gallery, I'm getting the File correctly.

then i print its sized with: print(file.lengthSync());

Getting: 8364495 which is  about 8Mo right?

The thing is when i check the image details in the gallery, i see 3.6Mo

![image](https://user-images.githubusercontent.com/9638281/221851440-621db7ec-86bb-4aca-ba00-18c8779b014e.png)

Any idea why? am i missing something?

Thanks in advance :)

**Comment by baptistesx** [comment]
sorry issue on the wrong repo => https://github.com/fluttercandies/flutter_wechat_camera_picker/issues/163

**Comment by llli0v0** [comment]
I have the same problem. how did you resolve this?
