### ISSUE TITLE
页面卡顿

### ISSUE THREAD

**Issue by shenglintang** [fluttercandies/flutter_wechat_assets_picker#423]
**弹出图片选择时页面卡顿**

代码片段：
![微信截图_20230307230110](https://user-images.githubusercontent.com/19514662/228208259-3acef6b6-65f6-44ad-a57f-5c09dc53d9b3.png)

卡顿视频：

https://user-images.githubusercontent.com/19514662/228208732-980a9a2a-210a-4874-9e64-425024c0c0ac.mp4

**Version information**

- Device: 华为P40Pro、红米11
- OS: 安卓11
- sdk version： 7.3.2
- Flutter Version:3.0.0

**Comment by AlexV525** [comment]
Degraded performance in DEBUG mode is not a valid metric.
