### ISSUE TITLE
Parameter selectedAssetsunworkable (参数selectedAssets 失效问题)

### ISSUE THREAD

**Issue by miaodongCoder** [fluttercandies/flutter_wechat_assets_picker#425]
**The latest version8.4.1 has a bug when i type selectedAssets , it is unworkable! 
The selectedAssets parameter in the latest version 8.4.1 is invalid. When I switched to version 8.4.0, it worked. The selectedAssets parameter is used to allow users to see previously selected data when they re-enter the image selection list. I have been troubled by this issue for a long time. Switching back to version 8.4.0 resolved the issue. In version 8.4.1, the _selectedAssets parameter I passed in was always an empty array in the onTap event callback. I can provide a screenshot.(最新版的8.4.1 中的 selectedAssets 参数无效了 , 当我换成8.4.0版本的收它就好了 ,  这个参数 selectedAssets 是为了让用户再次进入图片选择列表里的时候还能看到之前选择过的数据 , 我被这个问题困扰很久 , 换了之前的8.4.0版本就好了 , 8.4.1版本我传入的_selectedAssets 参数在onTap事件回调里一直是拿不到的空数组情形 , 我给你截图)**

**How to reproduce**
1.author could see my demo address is [地址为:]:https://github.com/miaodongCoder/flutter_wechat_post (作者可以看我的项目)
请您在我这个项目里的打开tag 其中的`08-完善微信了发布界面的样式;` 就是有问题的这个版本
您可以打开项目后在iOS模拟器中添加图片 , 此时没有任何问题 , 但是如果你把pubspec.yaml 中的 第 39行 从`  wechat_assets_picker: 8.4.0`改为 `wechat_assets_picker: 8.4.1` 或者 `  wechat_assets_picker: ^8.4.1`即使用最新版本时再次重复添加 , 就会发现  ,selectedAssets根本记不住之前添加的那些图片 , 这就是我遇到的问题;

Click `发布` -> `相册`  -> `图片`and then select some photos after that click `Confirm`  do it again you may see the bug 
the parameter `selectedAssets` is unworkable;

1.点击`发布` 底部弹出BottomSheet后再点击`相册`再点击`图片`
2.选择若干张图片后再点击`Confirm`确认按钮 , 回到朋友圈发布页 , 再重复点击图片后面的`大➕`按钮再选择`相册` -> `图片`
3.此时如果是 `wechat_assets_picker: 8.4.0` 没有任何问题 , 能看到之前选择的那若干张图片已经被默认选中 , 但是如果是`wechat_assets_picker: ^8.4.1`最新版本, 就会发现之前应该被选中的那若干张图片没有被选中 , 这就是我要描述的问题;

**Expected behavior**
same from the version 8.4.0;
期望修复到8.4.0 `selectedAssets:` 这个入参能够正确显示;

**Screenshots (If contains)**
`this is the gif of 8.4.1 the bug version`
`↓这是8.4.1版本失效的动图↓`
![8 4 1版本已选择图片失效动图](https://user-images.githubusercontent.com/25526248/230605876-bcef67a4-6414-4367-97f6-c4b993845fc8.gif)

`this is gif of 8.4.0 the correct version`
`↓这是8.4.0版本未失效的动图↓`

![8 4 0版本未失效动图](https://user-images.githubusercontent.com/25526248/230606156-c552db4b-4593-4e9c-8391-cf23ae09fc56.gif)

**Version information**

- Device: [ iPhone 14 Pro Max 模拟器]
- OS: [e.g. iOS 16.4]
- Package Version: [e.g. 2.4.1]
- Flutter Version: [ Flutter (Channel stable, 3.7.10, on macOS 13.2.1 22D68 darwin-x64, locale zh-Hans-CN) ]

**Additional context**
感谢你们对开源社区做的贡献 , 这个图片选择类库帮助了我很多 , 向你们致敬 
the best wish for you!
Salute!

**Comment by LiFuPeng** [comment]
我也遇到过同样的问题，现在甚至进去相册都是空的

**Comment by sufangyu** [comment]
您的邮件已经收到，谢谢！

**Comment by LiFuPeng** [comment]
8.4.0版本也是空的
