### ISSUE TITLE
[BUG] The returned assets should not be affected

### ISSUE THREAD

**Issue by hellohejinyu** [fluttercandies/flutter_wechat_assets_picker#427]
**Describe the bug**

At `8.4.1`, when the selection is complete, add a dispose method to destroy. At this time, the selected resource array will be destroyed, but this operation will synchronously affect the external return value.

https://github.com/fluttercandies/flutter_wechat_assets_picker/commit/d0c22396edbbf5edcbd3547f12804d90be3a3dc4#r108379761

<img width="640" alt="image" src="https://user-images.githubusercontent.com/8766034/231034425-aca95c9e-9363-4ef2-9231-e3a60055c96e.png">

**How to reproduce**

[You can see this simple example](https://github.com/fluttercandies/flutter_wechat_assets_picker/compare/main...hellohejinyu:flutter_wechat_assets_picker:main)

1. Pick Assets in Common picker;
2. See output in console;

**Expected behavior**

The length should same between before and after;

**Version information**

- Package Version: 8.4.1

**Comment by AlexV525** [comment]
Thanks for providing the detail!
