### ISSUE TITLE
[BUG] Permission issue on Android 13

### ISSUE THREAD

**Issue by aakhlestova** [fluttercandies/flutter_wechat_assets_picker#432]
**Describe the bug**
When using AssetPicker.pickAssets only to get images on Android 13, we receive a request for permission to access music and audio on the device

**How to reproduce**
Run AssetPicker.pickAssets method with following parameters:

```
final images = await AssetPicker.pickAssets(
    context,
    pickerConfig: AssetPickerConfig(
      maxAssets: 5,
      textDelegate: assetPickerTextDelegateFromLocale(const Locale('ru', 'RU')),
      requestType: RequestType.image,
    ),
);
```

AndroidManifest permissions:

```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
```

**Expected behavior**
The expected behavior is similar to the behavior on earlier versions of android
Getting only a request for access to photos and videos is expected, without getting a request for access to music and audio

**Screenshots (If contains)**
Got current request:
![Screenshot_1681815351](https://user-images.githubusercontent.com/85393288/232766033-89103f0d-64b2-4b3d-8dc5-955bca2d6151.png)

**Version information**

- OS: Android 13 (API level 33)
- Package Version:  v8.4.0
- Flutter Version: v3.7.6

**Additional context**
If acces for music and audio is necessary while getting only images, can you explain why, please?

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_wechat_assets_picker#permissions

**Comment by pilgrim1385** [comment]
Same issue.
"AssetPicker.pickAssets()" with "requestType: RequestType.image", need photos and audios permission on Android API 33, but only photos permission on Android API 32.
And "https://github.com/fluttercandies/flutter_wechat_assets_picker#permissions" does not explain why pick only images must have audio permission.

**Comment by BunnyBuddy** [comment]
I am getting permission denied issue on Android 13.
Is there no way to resolve this issue on older versions of wechat_assets?
