### ISSUE TITLE
[BUG] Error with something

### ISSUE THREAD

**Issue by brux88** [fluttercandies/flutter_wechat_assets_picker#442]
**Describe the bug**
, if I click on the image picker home page, after a while it goes wrong
**How to reproduce**
I downloaded your example,
 
I downloaded your example, if I click on the image picker home page, after a while it goes wrong, see screnncast
https://www.screencast.com/t/R9DZdLBgJNg9

**Expected behavior**
as if it fails to load images, but it should go ahead and not go into error because if , I continue debugging then it loads everything>

 

**Version information**

- Device: Samsung s22+
- OS:Android 13
- Package Version: wechat_assets_picker
- Flutter Version:3.7.12

**Comment by ps6067966** [comment]
[AlexV525](https://github.com/AlexV525)
extended image package is now updated as per 3.10.0

**Comment by AlexV525** [comment]
Track with #445.
