### ISSUE TITLE
Picker with Arbitrary Asset List, and more docs.

### ISSUE THREAD

**Issue by Gregliest** [fluttercandies/flutter_wechat_assets_picker#444]
I would like to use this library to allow a user to pick from an arbitrary list of assets, for instance, all the user's photos from 2023. I don't want to rely on the CustomFilter (listed as experimental) from the PhotoManager, but would like to do the filtering within my app code, and then feed the results to the picker. How do I go about doing that? 

The documentation is a little light on how everything works, and the example is built with a lot of indirection, which makes it pretty hard to understand. After wading through the code for a few hours, I'm still not entirely sure I know all the available options. It looks like maybe I can do something similar to the directory_file_asset_picker? 

Any help appreciated.

**Comment by AlexV525** [comment]
Use `FilterOptionGroup.createTimeCond` with `filterOptions` like this one:
https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/5c72bb729e5aa96b351d4c81c3e6f0a2dbe1185f/example/lib/constants/picker_method.dart#L232-L246

**Comment by Gregliest** [comment]
Thanks for the quick response, what if I want to do filtering that isn't available as a FilterOption?

**Comment by AlexV525** [comment]
> what if I want to do filtering that isn't available as a `FilterOption`?

You'll need to follow how the album mechanism works on supported platforms to do filtering, which means the `CustomFilter` would be the bottom option to filter assets from what we've provided. However, regarding other cases, they need to be more specific so we can provide some specific solutions. Abstractions are open for delegates and providers.

> Ideally, I'd like to just initialize the `AssetPicker` with a list of AssetEntity.

To do so, you need to write your own `AssetPickerProvider` to provide your customized assets.
