### ISSUE TITLE
[BUG] PlatformException: Thumbnail request error

### ISSUE THREAD

**Issue by contactjavas** [fluttercandies/flutter_wechat_assets_picker#445]
**Describe the bug**
When triggering the asset picker, PlatformException (Thumbnail request error) occurred as below:

```log
Exception has occurred.
PlatformException (PlatformException(Thumbnail request error, java.util.concurrent.ExecutionException: com.bumptech.glide.load.engine.GlideException: Failed to load resource
There were 3 root causes:
java.lang.RuntimeException(setDataSource failed: status = 0x80000000)
java.lang.RuntimeException(setDataSource failed: status = 0x80000000)
java.lang.RuntimeException(setDataSource failed: status = 0x80000000)
 call GlideException#logRootCauses(String) for more detail, null, null))
```

**How to reproduce**
Use this minimal code. Please use the same package's version, Flutter version, and device version (if possible).

```dart
  _pickPhoto() async {
    final List<AssetEntity>? entityList = await AssetPicker.pickAssets(
      context,
      pickerConfig: AssetPickerConfig(
        maxAssets: 1,
        specialPickerType: SpecialPickerType.noPreview,
        pageSize: 40,
        requestType: RequestType.image,
      ),
    );

    if (entityList == null) return;
    if (entityList.isEmpty) return;
    if (!mounted) return;

    final AssetEntity entity = entityList[0];
    final File? pickedFile = await entity.file;

    if (pickedFile == null) return;
    if (!mounted) return;

    setState(() {
      // This line is specific to my use-case
      // _selectedPhoto = pickedFile;
    });
  }
```

1. When the `_pickPhoto` method is called, it will open the assets picker.
2. In my device, the error occured immediately

**Expected behavior**
There should be no un-handled exception.

**Screenshots**
<img width="1336" alt="image" src="https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/25834188/e7f2d62c-a1a1-4e32-827c-ea5ab899c8eb">

<img width="1276" alt="image" src="https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/25834188/16099718-b64f-4061-a181-3d42bd5cd620">

<img width="846" alt="image" src="https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/25834188/2b2e4a3c-3b87-4f7d-8569-637427d936a4">

<img width="1313" alt="image" src="https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/25834188/dbae2370-05ea-4970-bbb0-2e2663532e2f">

**Version information**

- Device: Redmi Note 10 5G
- OS: Android 13
- MIUI: 14.0.3
- Package Version: 8.5.0
- Flutter Version: 3.10.0
- Dart SDK Version: Configuring either `sdk: ">=2.19.6 <3.0.0"` or `sdk: ">=3.0.0 <4.0.0"` both have the same error.

**Comment by hortigado** [comment]
Same error with me

**Comment by Wbqqqq** [comment]
+1

**Comment by lionnner** [comment]
+1

**Comment by lizaihao** [comment]
即使在dart:2.18.6,使用版本wechat_assets_picker: 8.3.2还是存在以上问题，有何解法

**Comment by AlexV525** [comment]
The exception thrown by the `AseetPickerProvider` has been slient by 092e244. If exceptions are thrown by the `AssetEntityImage` should submit issues to the photo_manager repo.
