### ISSUE TITLE
[BUG] Assets contain picture when type is video in ios.

### ISSUE THREAD

**Issue by ahyangnb** [fluttercandies/flutter_wechat_assets_picker#451]
**Describe the bug**

After enable live mode go to system camera take pictures and run `wechat_assets_picker: ^8.5.0` project to ios  then assets contain picture when type is video.

**How to reproduce**

No demo, because ios project but u can use wechat_assets_picker: ^8.5.0 run.

1. Use system camera and enable live mode.
2. take pictures.
3. Go to Home page in example of wechat_assets_picker: ^8.5.0.
4. Click the viodeo picker.
5. Contain picture inside.

**Expected behavior**

Don't show picture.

**Screenshots (If contains)**

![IMG_0295](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/41765610/e661ccfe-4c54-46f2-a134-f1bba6f798e4)

**Version information**

- Device: iphone 7p
- OS: iOS 13.6
- Package Version: wechat_assets_picker: ^8.5.0
- Flutter Version: 3.10.5

**Additional context**

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_wechat_assets_picker#simple-usage
