### ISSUE TITLE
Allow confirmation of zero assets

### ISSUE THREAD

**Issue by adamcastleman** [fluttercandies/flutter_wechat_assets_picker#455]
**Is your feature request related to a problem?**
Currently, you are allowed to pass in assets to load the picker with pre-selected media. You can then select and deselect at will, except when you deselect all media. When the assets are 0, the confirm button is disabled.

**Describe the solution you'd like**
You should be able to select 0/x media, essentially deselecting all entries. Currently, there is no way to confirm a zero selection from the picker itself. The confirm button should work for any number of media selections, including zero.

**Describe alternatives you've considered**
There are essentially no other workarounds to this problem. You must remove the final asset outside of the picker.

**Comment by AlexV525** [comment]
I think making 0 assets available if there are selected assets previously would be a proper solution.
