### ISSUE TITLE
[Feature]  confirm button position

### ISSUE THREAD

**Issue by lukkaempf** [fluttercandies/flutter_wechat_assets_picker#474]
**Version information**
 - Device: *iPhone 14 Pro Max Simulator*
 - OS: *e.g. iOS 16.1*
 - Package Version: *e.g. v8.3.2*
 - Flutter Version: *e.g. v3.3.10*

The confirm button is hidden behind my button navigation bar.
I don't can use useRootNavigator = true, because then when I want to use a Snackbox after the asset selection, an error occurred because Snackbar and WeChat Asset Picker uses the same Hero Tag.

It would be helpful if the confirmation button could be freely positioned. Or another idea is the padding at the bottom.

confirm button missing:

<img width="359" alt="image" src="https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/64331815/4a016bd5-327e-4a5a-a39a-979e6ec9faf8">

**Comment by AlexV525** [comment]
Provide your usage code?

**Comment by lukkaempf** [comment]
> Provide your usage code?



First, I had the following code. The problem was, the asset picker and the snackbar use the same hero tag

```
 ElevatedButton(
                      onPressed: (() async {
                        //get assets
                        final List<AssetEntity>? assets =
                            await AssetPicker.pickAssets(context,
                                useRootNavigator: true);

                        //snackbar config
                        final snackBar = SnackBar(
                          content: Column(
                            mainAxisSize: MainAxisSize.min,
                            children: const [
                              Text(
                                'test',
                                style: TextStyle(color: Colors.black),
                                textAlign: TextAlign.center,
                              ),
                              SizedBox(
                                height: 10,
                              ),
                              SizedBox(
                                height: 5,
                                child: LinearProgressIndicator(),
                              ),
                            ],
                          ),
                          backgroundColor: Colors.white.withOpacity(0.9),
                          behavior: SnackBarBehavior.floating,
                          margin: const EdgeInsets.only(
                              bottom: 120, left: 50, right: 50),
                          shape: const RoundedRectangleBorder(
                              borderRadius:
                                  BorderRadius.all(Radius.circular(10))),
                          elevation: 100,
                          duration: const Duration(seconds: 5),
                        );

                        //show snackbar
                        ScaffoldMessenger.of(context).showSnackBar(snackBar);
                      }),
                      child: const Text('test asset picker + snackbar')),
```
This is the error:

> he following assertion was thrown during a scheduler callback:
> There are multiple heroes that share the same tag within a subtree.
> 
> Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must have a unique non-null tag.
> In this case, multiple heroes had the following tag: <SnackBar Hero tag - Column(direction: vertical, mainAxisAlignment: start, mainAxisSize: min, crossAxisAlignment: center)>
> Here is the subtree for one of the offending heroes: Hero
>     tag: <SnackBar Hero tag - Column(direction: vertical, mainAxisAlignment: start, mainAxisSize: min, crossAxisAlignment: center)>
>     dependencies: [_ModalScopeStatus]
>     state: _HeroState#05b69



then I wanted to use  "useRootNavigator: false", but then the confirm button is hidden behind my nav bar.

```
   //get assets
   final List<AssetEntity>? assets =
   await AssetPicker.pickAssets(context,
   useRootNavigator: false);
```
here you finde the code for my bottom nav bar: https://gist.github.com/maheshmnj/894922ccb67f5fdc4ffb652e41916fa2

**Comment by AlexV525** [comment]
Can you provide a minimal example that includes:
- Your bottom bar
- The picking method
- The snack bar handling

**Comment by lukkaempf** [comment]
In the following main file is my code. Change the file extension to .dart

[main.txt](https://github.com/fluttercandies/flutter_wechat_assets_picker/files/12255145/main.txt)

I'm using the version: wechat_assets_picker: ^8.3.2


When I use "useRootNavigator: true" in line 451 then there is an error with the hero tag and when I use "useRootNavigator: false" then I don't see the confirm button.

**Comment by AlexV525** [comment]
Changing your layout from `Stack[IndexedStack, Positioned(AnimatedNavBar)]` to `Column[Expanded(IndexedStack), AnimatedNavBar]` should fix your problem. There is nothing related to the picker.

**Comment by lukkaempf** [comment]
works for me, thanks for your help!
