### ISSUE TITLE
Package score is corrupted

### ISSUE THREAD

**Issue by hellohejinyu** [fluttercandies/flutter_wechat_assets_picker#478]
**Describe the bug**

![WX20230818-104927](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/8766034/29691e17-6e47-4c41-9e01-df9e4a407275)

**How to reproduce**

4. Error occurred.

**Expected behavior**

**Screenshots (If contains)**

**Version information**

- Device: [e.g. iPhone X]
- OS: [e.g. iOS 14.7.1]
- Package Version: [e.g. 2.4.1]
- Flutter Version: [e.g. v2.5.0]

**Additional context**

**Comment by hellohejinyu** [comment]
![image](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/8766034/377e4182-d37c-4da2-8ac2-6815236d54a8)

`extended_image` also has this problem

**Comment by AlexV525** [comment]
Because pana is not using the latest stable. Once they upgraded the scores will be normal.
