### ISSUE TITLE
[Contributors] Add your contributions.

### ISSUE THREAD

**Issue by AlexV525** [fluttercandies/flutter_wechat_assets_picker#48]
Contributions are welcome for everyone who wants to improve this package. For who has already contribute to the package, you can add your contributions if you wish.

**Comment by AlexV525** [comment]
@all-contributors Add @SchnMar for bug, code, ideas.

**Comment by AlexV525** [comment]
@all-contributors Add @ganlanshu0211 for bug, ideas.

**Comment by SchnMar** [comment]
@AlexV525  
What's you idea with this? Creating an issue of this type and then sending pull requests?

**Comment by AlexV525** [comment]
> What's your idea with this issue type? Creating an issue of this type and then sending pull requests?

The main idea about this issue is to manage the contributions together, without opening useless issues/PRs. And pinned this with extra attention to encourage people contribute to the package. :)

**Comment by AlexV525** [comment]
@all-contributors Add @JasonHezz for bug, code.
