### ISSUE TITLE
[BUG] black screen when using camera and no photos listed

### ISSUE THREAD

**Issue by ejbdobp** [fluttercandies/flutter_wechat_assets_picker#480]
**Describe the bug**
Black screen when loading images, the folders can be accessed but the photos are not appearing. When camera picker is selected the app freezes

**How to reproduce**
Only iphone 13 displays this erratic behavior, when using the same app with android it works alright. Tested with iphone 7 and 11 and there is no issue 

The permissions are enabled

Any idea what could be the problem?

![Screenshot_2023-08-22-18-45-56-846_com miui videoplayer](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/124381760/6570e756-7653-4845-9661-53391c01c6d7)

![Screenshot_2023-08-22-18-46-15-352_com miui videoplayer](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/124381760/0588ac26-584d-4e0e-b0d6-11a08d63f800)

![Screenshot_2023-08-22-18-45-59-416_com miui videoplayer](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/124381760/0664f2f8-d9af-4437-9b63-3fb5a1b15fc9)

**Version information**

- Device: iPhone 13 pro max
- Package Version: 8.5.0
- Flutter Version: 3.10.6

**Comment by ejbdobp** [comment]
Here is the code i used:
`_uploadImage() async {
      final List<AssetEntity>? assets = await AssetPicker.pickAssets(context,
          pickerConfig: AssetPickerConfig(
            requestType: RequestType.image,
            specialItemPosition: SpecialItemPosition.prepend,
            specialItemBuilder: (
              BuildContext context,
              AssetPathEntity? path,
              int length,
            ) {
              if (path?.isAll != true) {
                return null;
              }
              return Semantics(
                label: 'Take a picture',
                button: true,
                onTapHint: 'Take a picture',
                child: GestureDetector(
                  behavior: HitTestBehavior.opaque,
                  onTap: () async {
                    Feedback.forTap(context);
                    final AssetEntity? result =
                        await CameraPicker.pickFromCamera(context,
                            pickerConfig:
                                CameraPickerConfig(
                                    textDelegate:
                                        EnglishCameraPickerTextDelegate()));
                    if (result == null) {
                      return;
                    }
                    final AssetPicker<AssetEntity, AssetPathEntity> picker =
                        context.findAncestorWidgetOfExactType()!;
                    final DefaultAssetPickerBuilderDelegate builder =
                        picker.builder as DefaultAssetPickerBuilderDelegate;
                    final DefaultAssetPickerProvider p = builder.provider;
                    await p.switchPath(p.currentPath!);
                    p.selectAsset(result);
                  },
                  child: const Center(
                    child: Icon(Icons.camera_enhance, size: 42.0),
                  ),
                ),
              );
            },
          ));
      if (assets != null) {`

**Comment by zhangshuqi** [comment]
Encountered the same problem, have you resolved it?

**Comment by AlexV525** [comment]
@ejbdobp Can you verify if the problem exist when you use the camera picker alone?

**Comment by ejbdobp** [comment]
the error was from our customer. we tested on the same iphone 13 device and it worked fine and we are not able to replicate the error. however the problem is still present on the customers phone.

Hi @zhangshuqi, could you give more information on your error?

**Comment by ejbdobp** [comment]
ill create a project with camera picker alone please wait

**Comment by ejbdobp** [comment]
Hi @AlexV525 i think the closest i can replicate the issue for the camera picker is using the example project on Nexus 5x API 30 simulator, repeatedly tapping "Taking photos" example and tapping close on the camera. what happens is it will get to a black screen with the close, flash and rotate controls gone (only the main take photo button is left and is untappable)

![Screenshot_1692948299](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/124381760/cccbe70c-0b37-40c6-bc53-4f61231ce934)
![Screenshot_1692948303](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/124381760/1865c277-9992-418d-aeb4-1f7db5288085)
![Screenshot_1692948306](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/124381760/e7a94081-34ec-43f7-bf36-cf3797590b31)

However on a real android device, it happened this morning, that the black screen appeared on first use of camera picker, it froze and there is nothing to do. the user has to tap back and restart the camera for it to work. here is the screenshot. this only happened on first use of the app.

![369822849_260655546914808_2662542769405944569_n](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/124381760/b1b9c96b-326b-450c-9dca-36248cfe8c63)

for the customer i mentioned above, the black screen always appear and the camera never works despite the permissions enabled.

**Comment by AlexV525** [comment]
So I guess it's a camera picker issue. Could you identify if https://github.com/fluttercandies/flutter_wechat_camera_picker/pull/191 can fix your case?
