### ISSUE TITLE
The parameter 'borderRadius' can't have a value of 'null' because of its type 'BorderRadius', but the implicit default value is 'null'.

### ISSUE THREAD

**Issue by venkateshavenki** [fluttercandies/flutter_wechat_assets_picker#481]
Hi, I am using the latest version of Flutter, but I am unable to run the project due to the error mentioned below.

Error:
Could not build the precompiled application for the device.
Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/extended_image-8.0.2/lib/src/extended_image.dart:39:10: Error: The parameter 'borderRadius' can't have a value of 'null' because of its type 'BorderRadius', but the implicit default value is 'null'.

**Comment by 1771893348** [comment]
咱们咋解决的，我这也出现这个问题了
