### ISSUE TITLE
[Feature] Image Editor For Multi Image Select

### ISSUE THREAD

**Issue by Fearripper** [fluttercandies/flutter_wechat_assets_picker#489]
**Version information**
 - Device: *iPhone,Android*
 - OS: *iOS,Android*
 - Package Version: *8.7.0*
 - Flutter Version: *3.13*

**Is your feature request related to a problem?**
I have a requirement where u can crop or edit multiple images like Whatsapp when using multi image select.

**Describe the solution you'd like**
It can be like a button on the preview view where upon tapping you can edit the image.

**Describe alternatives you've considered**
I have not considered any alternatives for this for now.

**Additional context**

**Comment by AlexV525** [comment]
Using custom delegates allows you to add whatever you want anywhere.
