### ISSUE TITLE
[Feature] Add camera option in example insta_asset_picker

### ISSUE THREAD

**Issue by membersubs** [fluttercandies/flutter_wechat_assets_picker#490]
**Version information**
 - Device: *iPhone Simulator*
 - OS: *e.g. iOS 16.4*
 - Package Version: *8.5.0*
 - Flutter Version: *v3.10.0*

**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Can you please add camera option in the grid view of insta_asset_picker in example?

**Describe alternatives you've considered**
Tried few things but just couldn't get it to work with Insta layout

**Comment by AlexV525** [comment]
cc @LeGoffMael
