### ISSUE TITLE
[BUG] iOS相册中有 33,450张照片、1,660个视频。 选择图片时，一直显示加载中。

### ISSUE THREAD

**Issue by Allenxuxu** [fluttercandies/flutter_wechat_assets_picker#496]
**Describe the bug**

相册中有 33,450张照片、1,660个视频。(有 icloud 照片)
选择图片时，一直显示加载中。

**How to reproduce**

```
    final List<AssetEntity>? result = await AssetPicker.pickAssets(context,
        pickerConfig: AssetPickerConfig(
          requestType: RequestType.image,
          filterOptions: FilterOptionGroup(containsLivePhotos: true),
          limitedPermissionOverlayPredicate: limitedPermissionOverlayPredicate,
        ));
```

直接点击，选择照片

**Expected behavior**

能正常加载并选择图片

**Screenshots (If contains)**

![image](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/20566897/596c0431-04c1-4e0d-bcfd-6d61d0bc2c11)

**Version information**

- Device: [e.g. iPhone X] iPhone 13
- OS: [e.g. iOS 14.7.1] iOS 16.6
- Package Version: wechat_assets_picker: ^8.6.3  photo_manager: ^2.7.1
- Flutter Version: [e.g. v2.5.0] v3.10.1

**Additional context**

**Comment by mero-jung** [comment]
same issue

**Comment by AlexV525** [comment]
如果可以的话，请使用 Xcode 对以下代码设置断点，尝试找到耗时请求。由于我们无法复现，所以我们的调试是无效的。

https://github.com/fluttercandies/flutter_photo_manager/blob/797175287f3ea53ffb324355c2acbb7b759d1d6a/ios/Classes/core/PMManager.m#L36-L88

**Comment by kangtian** [comment]
Error (Xcode): ../../.pub-cache/hosted/pub.dev/wechat_assets_picker-8.8.0/lib/src/widget/builder/asset_entity_grid_item_builder.dart:19:9: Error: Type 'AssetEntityImageProvider' not found.
为什么我会出现这种错误

**Comment by fupingren** [comment]
same issue

**Comment by tiangaopan** [comment]
same issue

**Comment by bladeofgod** [comment]
same here.

**Comment by OpenJarvisAI** [comment]
Same issue, I suggest don't use this lib.


TOOOOOO many fucking bugs!!!

**Comment by chuxideyanhuo** [comment]
same issue

**Comment by aleron08** [comment]
Same isuue here.

**Comment by tourdt** [comment]
我这边的客户也碰到了，苹果手机相册数量只有1000多张，但是打开相册一直处于加载中，应该和图片多少关系不大

**Comment by AlexV525** [comment]
> 我这边的客户也碰到了，苹果手机相册数量只有1000多张，但是打开相册一直处于加载中，应该和图片多少关系不大

如果有堆栈可以提供

**Comment by tourdt** [comment]
客户的手机，拿不到堆栈

**Comment by tourdt** [comment]
对苹果开发不太了解，弱弱的问一下，这个和iCloud有没有关系，刚才客户反馈，过一会又可以加载出来了

**Comment by AlexV525** [comment]
可以尝试 #596

**Comment by kirito0206** [comment]
I used 9.1.5 and found that there is still this problem
