### ISSUE TITLE
iOS Simulator and Real device have different results

### ISSUE THREAD

**Issue by brianp** [fluttercandies/flutter_wechat_assets_picker#505]
**Describe the bug**
When using `requestType` with `RequestType.video` I get different results in the iOS simulator than on a real device. In the iOS simulator, only video assets are returned. This is the correct behaviour. When the flutter app is built in release mode and used on a real iOS device (iPhone XR, OS: 16.6) all media is available to select. Filtering for video-only assets is not functioning. 

**How to reproduce**
```
AssetPicker.pickAssets(context,
  pickerConfig: const AssetPickerConfig(
    maxAssets: 1,
    requestType: RequestType.video,
))
```

On a real iOS device

1. Trigger the asset picker
2. See that all assets are available, not filtered by asset type.

**Expected behavior**
1. Trigger the asset picker
2. See only video assets

**Version information**
1. Device: iPhone XR
2. OS: iOS 16.6
---
1. Simulator iPhone XR
2. OS: iOS 16.4
---
- Package Version: 8.7.1
- Flutter Version: 3.13.6

**Additional context**
Behaviour in the simulator is not the same as behaviour on real device. Validating this incorrect behaviour is not possible on the simulator, as it will provide the expected result.

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_photo_manager?tab=readme-ov-file#filtering-only-live-photos

**Comment by brianp** [comment]
Cheers mate!

For anyone finding this later on. The link provided suggests the problem is that livephotos are included as "video" by default. This meant on my real device I had significantly more media displaying than expected. You need to pass an ios specific option to filter out livephotos as well.

I changed my code from the above example to the following, and got my expected result:

```
AssetPicker.pickAssets(context,
  pickerConfig: AssetPickerConfig(
    maxAssets: 1,
    requestType: RequestType.video,
    filterOptions: FilterOptionGroup(containsLivePhotos: false),
))
```

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/0015480e385a59a9188c6cba7f329a96a9245ff1/README.md?plain=1#L321-L324
