### ISSUE TITLE
[Feature] 希望扩展 SortPathDelegate，能够让用户传入

### ISSUE THREAD

**Issue by oliverchu** [fluttercandies/flutter_wechat_assets_picker#51]
希望能够提供这个扩展，因为项目中，iOS 测试人员觉得默认进去是“实况图片”或者叫“Live Photo” 很奇怪，而在Android 默认是Recent，这也很奇怪，为什么没有多语言？Download也不是中文的。希望提供入口，包括特定文件夹的多语言，还有排序的委托。谢谢您，祝您开发顺利

**Comment by AlexV525** [comment]
已经提供。https://github.com/fluttercandies/flutter_wechat_assets_picker#usage-
