### ISSUE TITLE
[BUG] Deselecting is not working

### ISSUE THREAD

**Issue by yeojin-yun** [fluttercandies/flutter_wechat_assets_picker#515]
**Describe the bug**

When you attempt to uncheck a previously selected picture in picker, it is not working.

**How to reproduce**

```Dart
import 'package:flutter/material.dart';
import 'package:photo_manager/photo_manager.dart';
import 'package:wechat_assets_picker/wechat_assets_picker.dart';

class PhotoView extends StatefulWidget {
  const PhotoView({super.key});

  @override
  State<PhotoView> createState() => _PhotoViewState();
}

class _PhotoViewState extends State<PhotoView> {
  List<AssetEntity> selectAsset = [];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: Text('wechat_asset_picker'),
      ),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          TextButton(
              onPressed: () async {
                final PermissionState ps =
                    await PhotoManager.requestPermissionExtend();

                if (ps.isAuth) {
                  // Granted
                  // You can to get assets here.
                  final List<AssetEntity>? result =
                      await AssetPicker.pickAssets(context,
                          pickerConfig: AssetPickerConfig(
                              selectedAssets: selectAsset,
                              requestType: RequestType.image));
                  if (result != null) {
                    selectAsset = result;
                    setState(() {});
                  }
                } 
              },
              child: Text('picker')),
          Expanded(
            child: GridView.builder(
              itemCount: 9,
              gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 3,
                mainAxisSpacing: 8,
                crossAxisSpacing: 8,
              ),
              itemBuilder: (BuildContext context, int index) {
                return (index >= 0 && index < selectAsset.length)
                    ? AssetEntityImage(
                        selectAsset[index],
                        fit: BoxFit.cover,
                        isOriginal: false,
                      )
                    : Container(
                        decoration: BoxDecoration(
                          border: Border.all(color: Colors.black, width: 1),
                        ),
                      );
              },
            ),
          )
        ],
      ),
    );
  }
}
```

1. Present `wechat_asset_picker` using AssetPicker.pickAsset() method for changing photos that is preselected
2. Press `preview` for deselecting previously selected photo.
3. Even if you select a previously selected photo in preview bottom, the same photo will continue. (can not change)
4. Main picture in preview is not changed so I can not deselected.

**Expected behavior**

Does the preview mean the photos that I preselected? When I touch picture at the bottom of preview screen, main picture have to be changed what i select and I should be deselect the picture.

![IMG_0130DFAAA4C6-1](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/85544383/a793c915-200e-4ef8-9e98-1340de5be2d4)

**Screenshots (If contains)**

![1](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/85544383/4a9c809c-57a4-4e59-ad9c-d2447c4a0cc7)

**Version information**
- Device: iPhone X, iPhone mini 13
- OS: iPhone X-iOS 16.7.2 / iPhone mini 13 - iOS 17.2
- Package Version: 8.7.1
- Flutter Version: v3.13.8

**Additional context**

This problem occurs more often, especially when an old photo is provided as a parameter value for preselect.

**Comment by AlexV525** [comment]
I didn't reproduce this on my iPhone 12 (iOS 17.1).

**Comment by AlexV525** [comment]
The select button will only disappear if the `selectedAssets` used in the config is `null`.
1. https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/bf5daf25163301ab6ff276e2a51f701ac550066f/lib/src/delegates/asset_picker_viewer_builder_delegate.dart#L747-L757
2. https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/bf5daf25163301ab6ff276e2a51f701ac550066f/lib/src/widget/asset_picker_viewer.dart#L50-L57

Based on the above code, there should be nothing wrong with the package. Closing as invalid usages.

**Comment by yeojin-yun** [comment]
in my case, This happens when you select a photo taken two to three weeks ago in the picker. I think there is no problem when choosing the photos that are currently loaded on the screen, but an error occurs when the older photo is selected as the pre-elect photo. would you check this again?

**Comment by AlexV525** [comment]
>I think there is no problem when choosing the photos that are currently loaded on the screen, but an error occurs when the older photo is selected as the pre-elect photo.

It only matters to the condition I've attached above. I've also checked by selecting assets out of the first 10 pages and starting the selecting again. No issues were found tho.
