### ISSUE TITLE
[BUG] audio permission issue

### ISSUE THREAD

**Issue by jihanga** [fluttercandies/flutter_wechat_assets_picker#516]
**Describe the bug**

First of all, this is a problem with Android.
(iOS is heavily restricted from importing audio.)

I'm allowing all the choices of images/video/audio using the wechat asset picker.
But if you only need audio
```
AssetPickerConfig(
requestType: RequestType.audio,
)
```
Only audio can be selected using the ,
In other cases, `RequestType.common` allows you to select images and videos.

The problem here is that even if I only allowed `RequestType.audio`, I only request permission to the media,
This means that permissions for audio are not requested.
So I had to do additional work to request audio permissions, and the library didn't run unless the library allowed permissions to the media, even though only audio permissions were required.

It seems strange that you need permission to take pictures and videos, even though only audio is available for selection.

**How to reproduce**

```
AssetPicker.pickAssets(
        context,
        pickerConfig: AssetPickerConfig(
          requestType: RequestType.aduio,
          limitedPermissionOverlayPredicate: (state) => false,
        ),
      );
```
When this code is enabled, it checks only permissions for photos and videos without asking permissions for audio.
Even if you allow permission for photos and videos, you don't have permission for audio, so you can't see anything in the actual item.

**Expected behavior**

There seems to be a need for an option that allows users to check authority directly without checking authority at all using `request.type`

**Screenshots (If contains)**

**Version information**

- OS: android only

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/main/README.md#permissions

**Comment by jihanga** [comment]
> https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/main/README.md#permissions

I'm aware of that.
However, I used wechat_asset_picker to implement the image selection part and audio selection part separately.
Therefore, if you choose audio, I hope you don't get image permission.

However, in the current case, you will be asked for image permission even if you only try to select audio.

**Comment by AlexV525** [comment]
Please verify if the linked PR resolves the problem.

**Comment by jihanga** [comment]
Your PR was the function I wanted.
I didn't think it would be revised so quickly. Thank you for your quick response.
