### ISSUE TITLE
引入最新的包不能运行

### ISSUE THREAD

**Issue by BryantKawhi** [fluttercandies/flutter_wechat_assets_picker#518]
我使用的flutter  sdk是3.16.2

引用您的库是：
  wechat_assets_picker: ^8.8.0
  wechat_camera_picker: ^4.1.1

pub get后不能允许，总是报如下错误
![image](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/29621842/eb1c45ae-cfbd-44b6-a9c4-421b002e0704)

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/main/README-ZH.md#%E7%89%88%E6%9C%AC%E5%85%BC%E5%AE%B9

**Comment by BryantKawhi** [comment]
意思是我的降低sdk的版本吗？还是使用8.9.0呢，可是这个是开发版啊？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fluttercandies/flutter_wechat_assets_picker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月3日(星期天) 凌晨1:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fluttercandies/flutter_wechat_assets_picker] 引入最新的包不能运行 (Issue #518)





 
https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/main/README-ZH.md#%E7%89%88%E6%9C%AC%E5%85%BC%E5%AE%B9
