### ISSUE TITLE
[Feature] Ability to pick from camera.

### ISSUE THREAD

**Issue by AlexV525** [fluttercandies/flutter_wechat_assets_picker#52]
Too many annoyance requests received...

Scheduled for a week's development.

Also it required the `photo_manager` update methods related to saving. /cc @CaiJingLong

**Comment by nhtlquan** [comment]
Device: IOS 13, All Iphone
flutter_wechat_assets_picker version: lastest version from Github
Description:
Case 1: When I take picture from camera ==> return **File** ==> upload **File** to server  (MultipartFile)==> Success
Case 2:
I use 
` customItemBuilder: (BuildContext context) {
                return GestureDetector(
                  behavior: HitTestBehavior.opaque,
                  onTap: () async {
                    final AssetEntity result =
                        await AssetPicker.pickFromCamera(context);
                    if (result != null) {
                      Navigator.of(context)
                          .pop(<AssetEntity>[...assets, result]);
                    }
                  },
                  child: const Center(
                    child: Icon(Icons.camera_enhance, size: 42.0),
                  ),
                );
              },`
When I take picture from camera ==> save with **PhotoManager.editor.saveImage** ==> upload file with **entity.file** or **entity.originBytes** (MultipartFile) ==> Fail

**Comment by CaiJingLong** [comment]
I will check code.

**Comment by AlexV525** [comment]
@nhtlquan Please provide more info about the 'Fail' you are talking about.

Also, the save process doesn't require yourself to integrate with saving, it will done itself. So please remove any code related with saving.

**Comment by nhtlquan** [comment]
> @nhtlquan Please provide more info about the 'Fail' you are talking about.
> 
> Also, the save process doesn't require yourself to integrate with saving, it will done itself. So please remove any code related with saving.

I don't saving anything, only get AssetEntity from result. And post entity.file to server!

**Comment by nhtlquan** [comment]
File take picture:
**takenFilePath**===/var/mobile/Containers/Data/Application/3C8EA204-BDF3-4813-BD88-F6C9162E60D2/Documents/picker_1594867922625.jpg
 **fileLength**===5021396

File from AssetEntity:
**path**===/private/var/mobile/Containers/Data/Application/3C8EA204-BDF3-4813-BD88-F6C9162E60D2/tmp/flutter-images/b351ced34d9913aa5b433d82aa2acee6_exif.jpg
**originBytes**===5030776

**Comment by AlexV525** [comment]
> I don't saving anything, only get AssetEntity from result. And post entity.file to server!

Use `entity.originFile` rather than `entity.file` .

**Comment by AlexV525** [comment]
Done in [wechat_camera_picker](https://github.com/fluttercandies/flutter_wechat_camera_picker) .
