### ISSUE TITLE
[BUG] Error with something

### ISSUE THREAD

**Issue by kangtian** [fluttercandies/flutter_wechat_assets_picker#522]
我更新了flutter 最新版本后就无法是这个组件了，不知道什么原因

Launching lib/main.dart on iPhone15 XS Max in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: UNF3HP5UVG
Xcode build done.                                           30.0s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): Error: Couldn't resolve the package 'wechat_assets_picker' in 'package:wechat_assets_picker/wechat_assets_picker.dart'.
Error: Type 'AssetEntityImageProvider' not found.

**Comment by kaciula** [comment]
@AlexV525  I am experiencing the same issue. I cannot build the app for Android or iOS on Flutter 3.16.0

`  wechat_assets_picker: ^8.8.1+1`

`/.pub-cache/hosted/pub.dev/wechat_assets_picker-8.8.1+1/lib/src/widget/builder/asset_entity_grid_item_builder.dart:19:9: Error: Type 'AssetEntityImageProvider' not found.`

I tried adding photo_manager and photo_manager_image_provider as dependencies but I still get the same error.
