### ISSUE TITLE
[BUG] Permission state error with PermissionState.denied on Android 13

### ISSUE THREAD

**Issue by BunnyBuddy** [fluttercandies/flutter_wechat_assets_picker#524]
**Describe the bug**

We have a Flutter app which is build on 2.10.4 version and previously we were using [multi_image_picker2](https://pub.dev/packages/multi_image_picker2) for picking multiple images. The package has been discontinued so far and after the android 13 launch user can't pick any image and is greeted with a permission denied error. We tried different plugins including flutter_wechat_assets_picker 6.3.1 still got the same issue. 
We can't use a newer version to resolve this issue due to dart version and other limitations.

**How to reproduce**

 ```
Future<void> loadAssets() async {
    List<Asset> resultList = <Asset>[];
    String error = 'No Error Detected';
    final ImagePicker picker = ImagePicker();

    try {
      PermissionState per = await AssetPicker.permissionCheck();
      log("permissions check -> ${per.toString()}");
      final List<AssetEntity>? images = await AssetPicker.pickAssets(
        context,
        maxAssets: productController.productMedias.isNotEmpty ? 15 - productController.productMedias.length : 15,
        selectedAssets: productController.mediaTest.value,
        requestType: RequestType.image,
        textDelegate: EnglishTextDelegate(),
      );
      AlertWidgets.showSnackBar(msg: "Images selected: ${images!.length}", tick: true);
} on Exception catch (e) {
      error = e.toString();
    }
```

The issue is only related to Android 13 and I've tried adding a bunch of permissions as well in the android manifest file that are related to android 13 
```
(
<uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_NOTIFICATION_POLICY" />
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
    <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />
    <uses-permission android:name="android.permission.MANAGE_DOCUMENTS" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
)
```

**Expected behavior**
The code should work as expected 

**Screenshots (If contains)**
Sorry can't attach a screenshot because nothing happens on the screen

**Version information**

- Device: [Infinix Note 12, Emulator (Pixel 4), every android 13 device]
- OS: Android 13
- Package Version: 6.3.1
- Flutter Version: 2.10.4

**Additional context**
Flutter doctor,

[✓] Flutter (Channel stable, 2.10.4, on macOS 12.7.1 21G920 darwin-x64, locale en-PK)
    • Flutter version 2.10.4 at /Users/macbookpro/src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (1 year, 9 months ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/macbookpro/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile)    • emulator-5554             • android-x64    • Android 13 (API 33) (emulator)
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 120.0.6099.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_wechat_assets_picker?tab=readme-ov-file#android

**Comment by BunnyBuddy** [comment]
> https://github.com/fluttercandies/flutter_wechat_assets_picker?tab=readme-ov-file#android

Thankyou for your response and yes I've implemented all these things still I get the same issue.

**Comment by AlexV525** [comment]
If the example works fine on your device then it means you project is still misconfigured.

**Comment by BunnyBuddy** [comment]
> If the example works fine on your device then it means you project is still misconfigured.

It doesn't work fine the problem is probably the version of this package I am using. Its pretty old

**Comment by AlexV525** [comment]
We generally don't support previous versions. Could you verify if the latest version works fine alone?

**Comment by petermusembi69** [comment]
I am facing a similar issue on the latest version `wechat_assets_picker: ^8.8.0`, on flutter 3.16, this worked perfectly prior the upgrading to the latest flutter version.

**Comment by AlexV525** [comment]
> I am facing a similar issue on the latest version `wechat_assets_picker: ^8.8.0`, on flutter 3.16, this worked perfectly prior the upgrading to the latest flutter version.

8.8.0 does not work on 3.16. :)

**Comment by petermusembi69** [comment]
Ahaaa I see.

However, applying this [fix](https://github.com/GetStream/stream-chat-flutter/issues/1780#issuecomment-1833318786) allows you to get over the build errors, but when selecting wechat image assest the above exception is thrown.

Bumping wechat to version v9.0.0-dev.2 does fix the above issue either

**Comment by Jinxishihenian** [comment]
I had the same problem

**Comment by AlexV525** [comment]
Testing on the API 33 emulator.

The example of `photo_manager` tells the correct state since it returns all assets.
![image](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/15884415/5d7495c3-9271-4bf3-8842-0d8de9bc385b)

The example of `wechat_assets_picker` also tells the correct state since it returns all assets.
![image](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/15884415/87380a5c-b636-495a-aedc-4481f7c0461c)
