### ISSUE TITLE
一加ACEP 16G运行内存，3万多张图片，加载了6-7秒出来网格

### ISSUE THREAD

**Issue by DavidChZh** [fluttercandies/flutter_wechat_assets_picker#526]
一加ACEP 16G运行内存，3万多张图片，加载了6-7秒出来

这种正常吗，我看21年的时候也有一个类似的问题
https://github.com/fluttercandies/flutter_wechat_assets_picker/issues/116

还有没有什么好的优化的方法，
demo里面的通过降低缩略图质量的方法，也只能提高不到1秒。快6秒加载出来。

**Comment by AlexV525** [comment]
如果可以的话，请使用 Android Studio 对代码设置断点，尝试找到耗时请求。由于我们无法复现，所以我们的调试是无效的。

**Comment by DavidChZh** [comment]
> 如果可以的话，请使用 Android Studio 对 Android 原生代码设置断点，尝试找到耗时请求。由于我们无法复现，所以我们的调试是无效的。

您好，今天试了下，最新版本是4秒多，比8.8版本的快2秒左右。
用photo_manager的示例项目，打开1秒多点。

**Comment by DavidChZh** [comment]
> > 如果可以的话，请使用 Android Studio 对 Android 原生代码设置断点，尝试找到耗时请求。由于我们无法复现，所以我们的调试是无效的。
> 
> 您好，今天试了下，最新版本9.0.3是4秒多，比8.8版本的快2秒左右。 用photo_manager的示例项目，打开时，只有1秒多。

如果不区分图片和视频，全部获取，只有1秒多。跟photo_manager直接获取没有太大出入。只获取图片的情况下，是4秒多。

**Comment by AlexV525** [comment]
理论上筛选项越多时间就有可能越久，可以继续确认下这里的耗时来源于原生的哪个部分

**Comment by DavidChZh** [comment]
> 理论上筛选项越多时间就有可能越久，可以继续确认下这里的耗时来源于原生的哪个部分

以目前这些图片和视频的量级，一秒这个加载时间还有优化空间吗

**Comment by AlexV525** [comment]
> 以目前这些图片和视频的量级，一秒这个加载时间还有优化空间吗

一秒是很正常的范围了

**Comment by DavidChZh** [comment]
> > 以目前这些图片和视频的量级，一秒这个加载时间还有优化空间吗
> 
> 一秒是很正常的范围了，四秒可以再研究下

上次跟您说的，我运行flutter_wechat_assets_picker项目的demo，把图片类型改为不筛选，和photo_manager的加载时间基本没有差别。

刚才又试了下，把photo_manager加载筛选条件加上图片过滤，发现还是很快，和不加过滤基本没差别。
然后又翻代码，
```
    final List<AssetEntity> entities = await _path!.getAssetListPaged(
      page: 0,
      size: 80,
    );
```
发现这段代码，同样的代码，_path也是一样，都是Recent，但是在flutter_wechat_assets_picker项目里面需要3秒，在photo_manager里面只有1秒，我对比了两个 项目的依赖，也是一样的。

**Comment by AlexV525** [comment]
example 默认开了 log，也可以把 log 关了试试

**Comment by DavidChZh** [comment]
> example 默认开了 log，也可以把 log 关了试试
  PhotoManager.setLog(false);
设置了false，好像影响不大，跟之前没什么区别。

**Comment by DavidChZh** [comment]
> example 默认开了 log，也可以把 log 关了试试

PhotoManager.setLog(false);
设置了false，好像影响不大，跟之前没什么区别。

**Comment by AlexV525** [comment]
还有这个方法里初始化了一些筛选条件，也可以去掉试试

https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/0eb0441d9f6e71384f02c8490d7901023659942b/lib/src/provider/asset_picker_provider.dart#L329

**Comment by DavidChZh** [comment]
我找到区别了，getAssetPathList的onlyAll属性。
PhotoManager默认设置了true，只获取Recent下的，而flutter_wechat_assets_picker是默认获取所有目录，所以多出来的将近三秒是在加载Recent以外的其他目录。
如果是获取所有目录的逻辑，有没有可能优化一下，获取到Recent就展示出页面，而顶部的目录有一个异步加载的loading条，等几秒其他目录加载出来以后允许切换。

**Comment by DavidChZh** [comment]
> 还有这个方法里初始化了一些筛选条件，也可以去掉试试
> 
> https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/0eb0441d9f6e71384f02c8490d7901023659942b/lib/src/provider/asset_picker_provider.dart#L329

我找到区别了，getAssetPathList的onlyAll属性。
PhotoManager默认设置了true，只获取Recent下的，而flutter_wechat_assets_picker是默认获取所有目录，所以多出来的将近三秒是在加载Recent以外的其他目录。
如果是获取所有目录的逻辑，有没有可能优化一下，获取到Recent就展示出页面，而顶部的目录有一个异步加载的loading条，等几秒其他目录加载出来以后允许切换。

**Comment by AlexV525** [comment]
> 我找到区别了，getAssetPathList的onlyAll属性。 PhotoManager默认设置了true，只获取Recent下的，而flutter_wechat_assets_picker是默认获取所有目录，所以多出来的将近三秒是在加载Recent以外的其他目录。 如果是获取所有目录的逻辑，有没有可能优化一下，获取到Recent就展示出页面，而顶部的目录有一个异步加载的loading条，等几秒其他目录加载出来以后允许切换。

是一个优化方向，但是边界情况相当多，例如用户可能自行就过滤掉了主相册。

**Comment by DavidChZh** [comment]
> > 我找到区别了，getAssetPathList的onlyAll属性。 PhotoManager默认设置了true，只获取Recent下的，而flutter_wechat_assets_picker是默认获取所有目录，所以多出来的将近三秒是在加载Recent以外的其他目录。 如果是获取所有目录的逻辑，有没有可能优化一下，获取到Recent就展示出页面，而顶部的目录有一个异步加载的loading条，等几秒其他目录加载出来以后允许切换。
> 
> 是一个优化方向，但是边界情况相当多，例如用户可能自行就过滤掉了主相册。

是的，具体看您这边时间安排。
我这个应该算是属于比较多的了，4秒左右还能接受。

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_wechat_assets_picker/pull/596 可以尝试看看有没有改善。

**Comment by DavidChZh** [comment]
> #596 可以尝试看看有没有改善。

只加载图片也是秒出，非常流畅！！！
Thank you very much！
