### ISSUE TITLE
[Error] Glide `FileNotFoundException`

### ISSUE THREAD

**Issue by maskletter** [fluttercandies/flutter_wechat_assets_picker#53]
**Describe the bug (描述)**
A clear and concise description of what the bug is. 请用精炼的语句准确描述你遇到的BUG。

**How to reproduce (如何复现)**
Please **provide a minimum demo** rather than **a full project or a incomplete pages**. Otherwise we have rights to reject your request.

请提供一个**最小化的demo**用于复现，而不要提供**整个项目或者不完整的页面**，否则我们有权拒绝你的请求。

Steps to reproduce the behavior (描述复现步骤):

**Expected behavior (期望行为)**

**Screenshots (If contains) (是否有截图可以提供)**

**Device information (设备信息)**
 - Device: 努比亚x
 - OS: Android 8.1.0
 - Package Version: 4.0.0
 - Flutter Version: [e.g. v1.17.1]

**Additional context (附加信息)**
Add any other context about the problem here. 在此提供更多的内容。

```
class HomePage extends StatelessWidget {
   selectImage(){
    final List<AssetEntity> assets = await AssetPicker.pickAssets(context);
   } 
}
```
错误的文件路径: `wechat_assets_picker-4.0.0/lib/src/provider/asset_entity_image_provider.dart`

![image](https://user-images.githubusercontent.com/15777183/87871028-b896c500-c9df-11ea-89e7-820c4b15f933.png)

**Comment by AlexV525** [comment]
Please provide extra info about which image decode fail? File type? More logs?

**Comment by maskletter** [comment]
![image](https://user-images.githubusercontent.com/15777183/87875458-ee4da500-ca03-11ea-8ac5-f81821af3a0b.png)
![image](https://user-images.githubusercontent.com/15777183/87875465-f7d70d00-ca03-11ea-914b-f473fbcd7da0.png)
抱歉太过细节的我无法提供，我是第一次使用flutter，不太熟悉，点击bug继续，页面是可以显示出来，但是我一拖动页面，就会报出路径问题

**Comment by AlexV525** [comment]
这张图片是否实际存在？

**Comment by maskletter** [comment]
这个应该是一张错误的图片，我用其他工具，显示不出来这个图片

**Comment by AlexV525** [comment]
那么这个错误应该和本组件无关。如果有异议请进一步提供信息。

Closing while it's not related.

**Comment by maskletter** [comment]
我认为应该是读取图片错误，然后直接就给我抛出异常了，而没有内部处理一下，我尝试使用其他组件，组件会给出输出错误日志出来，而这个组件在我通过await方式时候直接抛出了

**Comment by AlexV525** [comment]
抛出的错误来源于缩略图的读取，并不来源于 await，这不是从 Flutter 层上抛的，所以理论上来说是一个正常行为。

**Comment by maskletter** [comment]
我也看到了，是缩略图生成出错了，那这个算不算是这个组件的一个bug呢

**Comment by maskletter** [comment]
晓得了，我加个异常处理过滤掉了

**Comment by maskletter** [comment]
谢谢
