### ISSUE TITLE
[Feature] faster loading of large photo library on iOS

### ISSUE THREAD

**Issue by rbarzel** [fluttercandies/flutter_wechat_assets_picker#534]
**Version information**
 - Device: iPhone 14 Pro
 - OS: iOS 17.2.1
 - Package Version: 9.0.0-dev.2
 - Flutter Version: 3.16.8

**Is your feature request related to a problem?**
The issue is performance. My gallery contains about 6,000 photos. It takes 7 seconds after `AssetPicker.pickAssets(context)` is called before the picker displays photos — the user sees a blank screen until then.

**Describe the solution you'd like**
I'd love it if images would appear more quickly. If that's not feasible, I'd like AssetPicker.pickAssets to display a loading indicator.

**Describe alternatives you've considered**
I've considered trying to write my own picker, but I'd still be using AssetManger since I love that packages features, and I have no reason to think my implementation would be faster.

**Additional context**
Thanks!

**Comment by AlexV525** [comment]
Please submit issues with the `photo_manager`. Thanks.
