### ISSUE TITLE
在MIUI 14.0.28 调起AssetPicker.pickAssets 报错

### ISSUE THREAD

**Issue by Tate-zwt** [fluttercandies/flutter_wechat_assets_picker#535]
Q：在MIUI 14.0.28 调起AssetPicker.pickAssets 报错，不过不影响使用，还是能正常调用起相册
```
 final List<AssetEntity>? assets = await AssetPicker.pickAssets(
      context,
      pickerConfig: AssetPickerConfig(maxAssets: maxImages - _imageUrls.length, requestType: RequestType.image),
    );
```

报错信息：
![img_v3_027d_a65965a3-3cf7-41ed-b819-559f9a3bafeg](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/10485427/77ad9c27-a225-4453-8d32-383fe13677e6)

     

**Version information**

- Device: 红米K60
- OS:MIUI 14.0.28
- Package Version:8.6.3
- Flutter Version: 3.10.5

期待您们的回复，谢谢哈！

**Comment by AlexV525** [comment]
截图？
