### ISSUE TITLE
[BUG] 图片和视频的预览功能的请求

### ISSUE THREAD

**Issue by chenjiangmin126** [fluttercandies/flutter_wechat_assets_picker#536]
**Version information**
 - Device: 小米10 等其他的安卓机器
 - OS: android12
 - Package Version: ^8.9.0-dev.1
 - Flutter Version: 3.16.3

**Is your feature request related to a problem?**

预览图片：在预览图片的时候 例如我选中了3张图片。 点击底部的预览按钮。 是从整个相册中的第一张开始预览的。
预览视频：在预览视频的时候，安卓的视频如果是向右横屏拍摄的。 预览视频的时候视频是倒置的。

**Describe the solution you'd like**
预览图片： 希望能从选中的图片下标开始预览。
预览视频： 希望能旋转一下正确的方式显示。  

**Additional context**
https://jk-feige-app.feigeblog.com/1706003790029_1266.mp4
这个保存在相中中  在安卓上选择预览时候就会倒置播放

**Comment by AlexV525** [comment]
录屏？

**Comment by chenjiangmin126** [comment]
> 录屏？

https://jk-feige-app.feigeblog.com/1707012529408_3234.mp4

这是录屏。    选择视频的时候图片是正的。 预览播放是反的。 
然后选中的第4个。点击左下角的的按钮是从第一个开始预览， 希望能从选中的第一个预览

**Comment by AlexV525** [comment]
- 播放反向的问题你需要找一下 video_player 的相关 issue，这里没有做额外处理
- 选中的问题请把触摸点打开，我看不到你点击的是哪里。我的测试没有复现这种情况

**Comment by chenjiangmin126** [comment]
> * 播放反向的问题你需要找一下 video_player 的相关 issue，这里没有做额外处理
> * 选中的问题请把触摸点打开，我看不到你点击的是哪里。我的测试没有复现这种情况



https://jk-feige-app.feigeblog.com/1707013641991_5147.mp4 这个是开了触摸点的录屏

方向的问题可以在播放的时候增加一个旋转吗。VideoPlayerController 中有个 rotationCorrection值. 
video_player 的相关 issue 有类似的问题  一直未处理  [https://github.com/flutter/flutter/issues/60327](issues)

**Comment by AlexV525** [comment]
> 方向的问题可以在播放的时候增加一个旋转吗。VideoPlayerController 中有个 rotationCorrection值.

这个参数是 video_player 已经自己处理了。Issue 看已经修复了，可以把视频提交给他们再次找问题。

**Comment by chenjiangmin126** [comment]
好的。我去video_player那边提交一下。     预览的问题可以处理吗

**Comment by AlexV525** [comment]
你的调用代码发一下

**Comment by AlexV525** [comment]
可以测试一下 PR 是否修复了问题
