### ISSUE TITLE
[Feature] Pick Asset from Google Drive

### ISSUE THREAD

**Issue by Shreedhar73** [fluttercandies/flutter_wechat_assets_picker#537]
**Version information**
 - Device: *Android*
 - OS: *Android*
 - Package Version: *latest*
 - Flutter Version: *Latest*

**Is your feature request related to a problem?**

Most of the android have implemented the google drive within their filesystem . Such that user can directly pick file from google drive. (As in image_picker). 

**Describe the solution you'd like**

It would be beneficial if user were to be able to pick assets from drive .

**Describe alternatives you've considered**

**Comment by AlexV525** [comment]
That is not the scope of the package.
