### ISSUE TITLE
Error: Type 'DecoderCallback' not found.

### ISSUE THREAD

**Issue by krunalappdev** [fluttercandies/flutter_wechat_assets_picker#538]
I am getting below error while running flutter app please help not able to solve.

".pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:"

my flutter version = 3.16.3

and how am i suppose to change version of photo_manger because it is internal package.

please help.

**Comment by AmosHuKe** [comment]
https://github.com/fluttercandies/flutter_photo_manager/issues/1021#issuecomment-1817299912
