### ISSUE TITLE
[BUG] 手机相册为空时，无法进行拍照

### ISSUE THREAD

**Issue by shenchunping** [fluttercandies/flutter_wechat_assets_picker#542]
**Describe the bug**
手机相册为空时，无法进行拍照

**How to reproduce**
源码中的示例存在相同问题。

1，允许源码中的示例到手机
2，选择“从相机生成选择”，可以看到拍照单元格，功能正常。
3，删除手机相册所有图片，再次选择“从相机生成选择”，没有图片也没有拍照单元格

**Expected behavior**
手机相册没有图片时，选择“从相机生成选择”，有拍照单元格

**Screenshots (If contains)**
--
**Version information**
commit version : 9ed1a3db
project version: 8.8.1

**Additional context**

**Comment by AlexV525** [comment]
specialItemBuilder 提供了参数允许根据路径自定义。

**Comment by shenchunping** [comment]
> specialItemBuilder 提供了参数允许根据路径自定义。

没太理解，能详细解释一下吗

**Comment by shenchunping** [comment]
> specialItemBuilder 提供了参数允许根据路径自定义。
@AlexV525 没太理解，能详细解释一下吗
