### ISSUE TITLE
[BUG] 部分机型读取图片列表加载过慢，8600多个图片，加载总耗时30S

### ISSUE THREAD

**Issue by y409663780** [fluttercandies/flutter_wechat_assets_picker#547]
**Describe the bug**

 荣耀20PRO手机内总有8600多张图片，在读取图片列表时，一直在loading转圈，总耗时30秒左右，代码如下：
  ![assets_picker耗时](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/7691251/73cfaf71-415b-4254-a28a-20b922b64059)
而另一个手机mate60，内有369张图片，加载不到1秒，视频已发在群里，代码位置：
![image](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/7691251/d813656c-e603-42c5-b289-3cfea83ee9f4)

**How to reproduce**

1. 点击图片选择
2. 进入图片选择列表，一直在Loading加载图片

**Expected behavior**

能正常速度加载并选择图片
**Screenshots (If contains)**

![WechatIMG36](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/7691251/fc7c4be0-3e76-419e-954b-6fb0fed54498)

**Version information**

- Device: 荣耀20 PRO、Mate60
- OS: Harmony os 3和4
- Package Version:   wechat_assets_picker: ^8.9.0-dev.1    photo_manager: ^3.0.0-dev.1
- Flutter Version: 3.16.0

**Additional context**

**Comment by AlexV525** [comment]
可以尝试 #596
