### ISSUE TITLE
[BUG] Error with something : file:///Users/jintian/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-3.0.0-dev.5/android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManager.kt:14:52 Unresolved reference: AndroidQDBUtils e: file:///Users/jintian/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-3.0.0-dev.5/android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManager.kt:16:52 Unresolved reference: DBUtils e: file:///Users/jintian/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-3.0.0-dev.5/android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManager.kt:36:84 Unresolved reference: DBUtils e: file:///Users/jintian/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-3.0.0-dev.5/android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManager.kt:37:18 Unresolved reference: AndroidQDBUtils

### ISSUE THREAD

**Issue by OpenJarvisAI** [fluttercandies/flutter_wechat_assets_picker#553]
: file:///Users/jintian/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-3.0.0-dev.5/android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManager.kt:14:52 Unresolved reference: AndroidQDBUtils
e: file:///Users/jintian/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-3.0.0-dev.5/android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManager.kt:16:52 Unresolved reference: DBUtils
e: file:///Users/jintian/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-3.0.0-dev.5/android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManager.kt:36:84 Unresolved reference: DBUtils
e: file:///Users/jintian/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-3.0.0-dev.5/android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManager.kt:37:18 Unresolved reference: AndroidQDBUtils

**Comment by Ssiswent** [comment]
The same
