### ISSUE TITLE
[BUG] AssetPickerProvider dispose 被调用两次，导致异常

### ISSUE THREAD

**Issue by dujianjie** [fluttercandies/flutter_wechat_assets_picker#562]
**Describe the bug**

AssetPickerProvider dispose 被调用两次，导致异常

**How to reproduce**

1.选择相册页面直接返回，正常
2.选择相册，进入相册，返回，出现异常

**Expected behavior**

不出现异常

**Screenshots (If contains)**

<img width="1324" alt="企业微信截图_bb969cd3-f1c7-4850-a49a-d03b8500cedc" src="https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/122344276/36f6f983-8294-4c4c-adcb-a54401611659">

**Version information**

- Device: [e.g. iPhone X]
- OS: [e.g. iOS 14.7.1]
- Package Version: 9.0.1
- Flutter Version: 3.16.9

**Comment by AlexV525** [comment]
提供录屏
