### ISSUE TITLE
[BUG] 苹果iPhone12手机切换Recents只加载默认80张图片

### ISSUE THREAD

**Issue by YaKun-SH** [fluttercandies/flutter_wechat_assets_picker#566]
来回切花页签，再次切换到Recents后只加载默认80张图片

const AssetPickerTextDelegate textDelegate = AssetPickerTextDelegate();
            List<AssetEntity>? assets = await AssetPicker.pickAssets(context,
                pickerConfig: AssetPickerConfig(
                  shouldRevertGrid: false,
                  maxAssets: 1,
                  requestType: RequestType.image,
                  specialPickerType: SpecialPickerType.noPreview,
                  textDelegate: textDelegate,
                  specialItemPosition: SpecialItemPosition.prepend,
                  specialItemBuilder: (
                    BuildContext context,
                    AssetPathEntity? path,
                    int length,
                  ) {}));

1. 打开相册
2. 切换相册页签到Screenshots页签
3. 再切换到Recents页签，查看图片
4. Recents页签900多张图片只显示80张，其他的丢失了

希望切换页签数据正常，并且页签可中文化，比如Recents可显示为最近项目

- Device: iPhone 12
- OS: 15.5
- Flutter Version: 3.19.2

期待你们的回复！

**Comment by AlexV525** [comment]
1. 不会保存已加载数据；
2. 已提供接口。

**Comment by YaKun-SH** [comment]
> 1. 不会保存已加载数据；
> 2. 已提供接口。
![IMG_2570(20240402-135237)](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/12605207/2319f7ad-1d73-4705-b89e-7aad3d61f73c)

这不是你们提供的UI么，切换这几个页签图片就显示不全了，怎么是不保存已加载数据呢？难道切换页签还要调用接口，改源码么？

**Comment by AlexV525** [comment]
> 这不是你们提供的UI么，切换这几个页签图片就显示不全了，怎么是不保存已加载数据呢？难道切换页签还要调用接口，改源码么？

接口是你问显示为中文，文档就有写配置方法和参数接口。

数据可以自己调大分页数量，每次切换都要获取最新的，不会保持旧的。

**Comment by YaKun-SH** [comment]
> > 这不是你们提供的UI么，切换这几个页签图片就显示不全了，怎么是不保存已加载数据呢？顾切换页签还要调用接口，改源码么？
> 
> 接口是你问显示为中文的，文档中有写配置方法和参数接口。
> 
> 数据可以自己调大分页数量，每次切换都要获取最新的，不会保持旧的。

点击切换页签每页显示80没问题，但是切换后只显示了第一页，再下滑没数据了，第二页数据加载不出来了，你的意思是说点击切换页签要调用接口么？具体是什么呢？谢谢！
