### ISSUE TITLE
勾选选择 和点开大图选择效果不一样

### ISSUE THREAD

**Issue by chenjiangmin126** [fluttercandies/flutter_wechat_assets_picker#567]
**Describe the bug**
当我使用pickAssets的时候。点击小圆圈勾选和点开大图后选择效果不一样。 在点开大图选择的时候出现问题。

当我使用shouldRevertGrid的默认值是null 的时候 点开大图选择时候 顺序应该是有问题的  结果和我选择的图片不一样

**How to reproduce**
```
final List<AssetEntity>? result = await AssetPicker.pickAssets(
        Get.context!,
        pickerConfig: AssetPickerConfig(
          maxAssets: maxAssets,
          requestType: RequestType.image,
          themeColor: colorPrimary,
          textDelegate: const AssetPickerTextDelegate(),
          limitedPermissionOverlayPredicate: (permissionState) {
            if (permissionState == PermissionState.limited) return false;
            return true;
          },
        ),
      );
```

**Expected behavior**
希望选择的那个图就返回哪个结果

**Screenshots (If contains)**
录屏地址
https://jk-feige-app.oss-cn-beijing.aliyuncs.com/QQ20240401-143458-HD.mp4

**Version information**

- Device: [e.g. iPhone 15 pro]
- OS: [e.g. iOS 17.4.1]
- Package Version: [e.g. 9.0.0]
- Flutter Version: [e.g. v3.16.5]

**Comment by AlexV525** [comment]
升级到最新版
