### ISSUE TITLE
[BUG] logCollections函数和预览导致加载时间暴涨

### ISSUE THREAD

**Issue by zgr0629** [fluttercandies/flutter_wechat_assets_picker#571]
**Describe the bug**
默认配置下打开picker加载时间超久。

**How to reproduce**
使用本项目的example，编译实机运行。点开图片选择，加载时间在20秒左右。

**Version information**

- Device: iPhone14 pro
- OS: 17.4.1
- Package Version: 9.0.2
- Flutter Version: 3.19.5

**Additional context**

**logCollections函数**
https://github.com/fluttercandies/flutter_photo_manager/blob/797175287f3ea53ffb324355c2acbb7b759d1d6a/ios/Classes/core/PMManager.m#L105-L118
这段代码里看似只用来打log，但实际有类型转换，每个相册耗时10+ms
再配合这里的循环，使得用户每有一个相册，都多耗时10+ms
再再配合IOS自动按月份分相册逻辑，只要是长期用iPhone的用户，随随便便几百个相册。例如我这边有五百多个相册。因为多了这一句log，加载多了6秒多。`PhotoManager.setLog(false)`即可，但请作者考虑更好的处理方案，纯log函数不应该影响性能。

**预览配置**
example项目内，点击“禁用预览”那一项，比普通的加载图片，加载时间可以减少10秒以上。
但由于我是flutter和OC新手，没找到具体预览处理逻辑再哪，也想问下作者，`specialPickerType: SpecialPickerType.noPreview`这个配置，影响哪些地方的逻辑，导致加载时间差距会这么大？

**Comment by AlexV525** [comment]
> **预览配置** example项目内，点击“禁用预览”那一项，比普通的加载图片，加载时间可以减少10秒以上。 但由于我是flutter和OC新手，没找到具体预览处理逻辑再哪，也想问下作者，`specialPickerType: SpecialPickerType.noPreview`这个配置，影响哪些地方的逻辑，导致加载时间差距会这么大？

提供录屏？

**Comment by zgr0629** [comment]
> > **预览配置** example项目内，点击“禁用预览”那一项，比普通的加载图片，加载时间可以减少10秒以上。 但由于我是flutter和OC新手，没找到具体预览处理逻辑再哪，也想问下作者，`specialPickerType: SpecialPickerType.noPreview`这个配置，影响哪些地方的逻辑，导致加载时间差距会这么大？
> 
> 提供录屏？

您好，有点不明白您想从录屏里获取哪些信息？因为我提供录屏也是点开后loading转菊花的画面，没什么有效信息。
您还有什么思路可以解决这个问题吗？

**Comment by AlexV525** [comment]
> 您好，有点不明白您想从录屏里获取哪些信息？因为我提供录屏也是点开后loading转菊花的画面，没什么有效信息。 您还有什么思路可以解决这个问题吗？

禁用预览是单独在示例里有条目的，通过录屏可以确认两件事情：
1. 你说的问题确实有发生
2. 问题能稳定通过示例复现

**Comment by zgr0629** [comment]
> > 您好，有点不明白您想从录屏里获取哪些信息？因为我提供录屏也是点开后loading转菊花的画面，没什么有效信息。 您还有什么思路可以解决这个问题吗？
> 
> 禁用预览是单独在示例里有条目的，通过录屏可以确认两件事情：
> 
> 1. 你说的问题确实有发生
> 2. 问题能稳定通过示例复现

这两点都可确认，我的确是通过点demo里的禁用预览里发现运行很快的。
而logCollections耗时是我调试上述代码时发现的。然后禁用log发现可以再加快。

**Comment by AlexV525** [comment]
> 这两点都可确认，我的确是通过点demo里的禁用预览里发现运行很快的。 而logCollections耗时是我调试上述代码时发现的。然后禁用log发现可以再加快。

log 默认是关的，example 开了而已。
禁用预览应该对加载速度造成不了影响，会快的原因可能是图片的数据已经存在于 ImageCache 里。可以参考 DefaultAssetPickerBuilderDelegate 中 isPreviewEnabled 的使用位置。

https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/6a2cbbc04ea37304d93b3d78c3cea10d5a4ac1f6/lib/src/delegates/asset_picker_builder_delegate.dart#L762-L764

**Comment by AlexV525** [comment]
> 感谢，我刚才重新调试了一下，机器和代码都没有变的情况下，发现现在变快了，总体从20秒降到了5秒左右。 

除了机器和代码，最重要的因素还是真机上的相册。

> 具体表现为是否开启预览不影响速度了。 log还是影响，但也比以前快了（单相册从10+ms降低到1+ms）。因为首次提issue已过去一个多月中途好像升级过xcode版本，不知是否有关系。

对于一个 log 功能来说，增加时长是预期内的，因为它本身就承载了输出更多信息的功能。

如果有兴趣可以研究相关 issue 进一步找到耗时。由于我们手上的真机无法复现，所以我们没有办法进行调试以及给出更多的信息：https://github.com/fluttercandies/flutter_wechat_assets_picker/labels/e%3A%20performance

**Comment by zgr0629** [comment]
“机器和代码不变”，其中的“机器”是指的是真机，自用的手机 :)
我是在使用某app时发现加载慢，并向app作者咨询后得知，他使用的是这个组件，所以来这问。
后续有时间我会跟进，有新进展再来提。
谢谢！
