### ISSUE TITLE
[BUG] the top status bar displaying the count obstructs the image

### ISSUE THREAD

**Issue by Jally3** [fluttercandies/flutter_wechat_assets_picker#572]
**Describe the bug**
When opening the album and clicking to preview a single image, the top status bar displaying the count obstructs the image, and tapping does not dismiss it.
打开相册点击单个图片预览时，顶部显示数量的状栏遮挡图片，点击也无法收起
**How to reproduce**

必现
必现

**Expected behavior**
 tapping  dismiss it.
点击会自动收起

**Screenshots (If contains)**

**Version information**

- Device: [e.g. iPhone X]
- OS: [e.g. iOS 14.7.1]
- Package Version: [e.g. 9.0.3]
- Flutter Version: [e.g. v3.19.0]

**Additional context**

**Comment by AlexV525** [comment]
提供录屏
