### ISSUE TITLE
[BUG] 70多张图片的相册，加载刷新，性能检测卡顿严重

### ISSUE THREAD

**Issue by applebest** [fluttercandies/flutter_wechat_assets_picker#573]
_selectImages() async {
    final List<AssetEntity>? images = await AssetPicker.pickAssets(context,
        pickerConfig: AssetPickerConfig(
          maxAssets: 9,
          requestType: RequestType.image,
          selectedAssets: state.images,
          textDelegate: const AssetPickerTextDelegate(),
        ));
  }

  wechat_assets_picker: ^9.0.3

  photo_manager: ^3.0.0-dev.2

Flutter (Channel stable, 3.16.5,)

**Comment by AlexV525** [comment]
性能检测呢？
