### ISSUE TITLE
DefaultAssetPickerBuilderDelegate.viewAsset FlutterError - Null check operator used on a null value[BUG] Error with something

### ISSUE THREAD

**Issue by scottynoshotty** [fluttercandies/flutter_wechat_assets_picker#575]
I am seeing this error in my Firebase Crashlytics

DefaultAssetPickerBuilderDelegate.viewAsset
FlutterError - Null check operator used on a null value
package:wechat_assets_picker/src/delegates/asset_picker_builder_delegate.dart:932

I can't repro but it should be pretty easy to investigate

**Comment by AlexV525** [comment]
Investigation cannot be started until info followed by the issue template has been provided.
