### ISSUE TITLE
[BUG] New photos not shown after upgrading photo_manager

### ISSUE THREAD

**Issue by matthiasn** [fluttercandies/flutter_wechat_assets_picker#576]
**Describe the bug**

After running the `flutter pub upgrade`, `photo_manager` will be upgraded to `3.1.0` and this will break the asset picker. Specifically, no new photos will be shown, only photos that were already visible before the upgrade. 

Adding the dependency directly and pinning to the last version before fixes the issue for me:

```yaml
    photo_manager: 3.0.0
```

Also see this [photo_manager issue](https://github.com/fluttercandies/flutter_photo_manager/issues/1125) I raised, and this [PR](https://github.com/matthiasn/lotti/pull/1741) that fixed it for me for now. Of course not a good long-term solution, but good enough for right now.

**How to reproduce**

I don't have the time to create a minimum demo right now, sorry. Fixed it for myself for the time being anyway, and maybe this report will be helpful for others who run into the same issue.

**Expected behavior**

I expect new photos to be shown in the camera roll/image picker.

**Version information**

- Device: iPhone 14 Pro
- OS: iOS 17.4.1
- Package Version: 9.0.3
- Flutter Version: 3.19.6

**Additional context**

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_photo_manager/blob/main/MIGRATION_GUIDE.md#containslivephotos

**Comment by pokid** [comment]
> ```yaml
> photo_manager: 3.0.0
> ```

yes，but this plugin not exposure "containsLivePhotos"

**Comment by pokid** [comment]
> https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/466b9e0737e6fb64b359fdbeaedf591a14872a02/lib/src/constants/config.dart#L141-L146

oh,thanks,it works,simple just` final List<AssetEntity>? assets = await AssetPicker.pickAssets(
              context,
              pickerConfig: AssetPickerConfig(
                filterOptions: PMFilter.defaultValue(),
              ),
            );`

**Comment by rajivmegamind** [comment]
@AlexV525 @matthiasn 


Thanks this answer worked for me. ❤️
