### ISSUE TITLE
您好！苹果在2024年5月1日以后新规，涉及到隐私政策，请问这个插件需要适配苹果新规吗？

### ISSUE THREAD

**Issue by yaochangliang159** [fluttercandies/flutter_wechat_assets_picker#578]
[苹果新规官方链接：](https://developer.apple.com/cn/support/third-party-SDK-requirements/)
https://developer.apple.com/cn/support/third-party-SDK-requirements/
我看插件列表里面，没有你们这个库，所以 你们这个库应该不用适配苹果新规吧？
我提这个issus，只是为了确认一下！感谢！

**Comment by AlexV525** [comment]
已经适配了，确保 photo_manager 版本是 3.1.0 以上即可。

**Comment by wubaibin** [comment]
> 已经适配了，确保 photo_manager 版本是 3.1.0 以上即可。

<img width="316" alt="image" src="https://github.com/user-attachments/assets/0d936c74-a7c6-40d1-a917-2fe3c9c45c47">
<img width="1442" alt="image" src="https://github.com/user-attachments/assets/f1089d9b-c2ae-4046-a11b-19434b208a94">

这个是苹果审核提示不通过，这是为什么
