### ISSUE TITLE
当预览图片时，切换会有黑屏卡顿。请问是否可以优化。谢谢

### ISSUE THREAD

**Issue by libinwalan** [fluttercandies/flutter_wechat_assets_picker#58]
当前使用版本：  wechat_assets_picker: ^4.1.0+4
在图像选择预览或者选择后预览。在多图切换时，会有黑屏卡顿。请问是否有优化方案。今天升级了最新版本 依然会出现。
谢谢Alex

**Comment by AlexV525** [comment]
请根据 issue template 开新的issue，或者直接在群里提问。Ref #28
