### ISSUE TITLE
[BUG] The previews in the widget of pick image is black

### ISSUE THREAD

**Issue by vjHuang** [fluttercandies/flutter_wechat_assets_picker#59]
**Describe the bug (描述)**
The previews in the widget of pick image is black

**How to reproduce (如何复现)**
Normal use, no special.
```
final List<AssetEntity> result = await AssetPicker.pickAssets(
        context, selectedAssets: lstTmp,
        maxAssets: widget.maxCount,
        requestType: RequestType.image);
```

[![ios.jpg](https://i.postimg.cc/MHYBpbvB/ios.jpg)](https://postimg.cc/n9CrdmKV)
image url:
https://postimg.cc/n9CrdmKV

**Device information (设备信息)**
 - Device: iPhoneSE
 - OS: 13.6
 - Flutter Version: v1.17.0

**Comment by AlexV525** [comment]
Is your images came from iCloud?

**Comment by vjHuang** [comment]
> Is your images came from iCloud?

No, local images.
It was normal a few days ago. After I integrated Baidu map, I modified some things and it became like this.

**Comment by AlexV525** [comment]
Could you reproduce by revert your changes to find out which is causing this failure?

**Comment by vjHuang** [comment]
> Could you reproduce by revert your changes to find out which is causing this failure?

I'm trying, at the same time, I would like to ask if you have encountered this kind of problem

**Comment by AlexV525** [comment]
At first it seems like issues related to iCloud, but if it don't, no similar issues are related.

**Comment by vjHuang** [comment]
> At first it seems like issues related to iCloud, but if it don't, no similar issues are related.

OK，thank you very much!

**Comment by vjHuang** [comment]
I found the reason, because in order to solve a bug in Baidu Maps, several files were introduced. The sentence in it caused the title of the ios image to not be obtained, and finally the thumbnail could not be displayed.
NSDictionary+NilSafe.m
