### ISSUE TITLE
[BUG]iOS相册无法加载LivePhoto

### ISSUE THREAD

**Issue by kapibara91** [fluttercandies/flutter_wechat_assets_picker#590]
**Describe the bug**
iOS相册无法加载LivePhoto，所有的LivePhoto相册中没有显示。但是把LivePhoto关掉后，相册就可以获取到了。

**How to reproduce**
在测试中，我直接使用的官方demo。
```
factory PickMethod.common(BuildContext context, int maxAssetsCount) {
    return PickMethod(
      icon: '📹',
      name: context.l10n.pickMethodCommonName,
      description: context.l10n.pickMethodCommonDescription,
      method: (BuildContext context, List<AssetEntity> assets) {
        return AssetPicker.pickAssets(
          context,
          pickerConfig: AssetPickerConfig(
            maxAssets: maxAssetsCount,
            selectedAssets: assets,
          ),
        );
      },
    );
  }
```

通过上述代码调起相册后，LivePhoto的图片没有显示。

**Expected behavior**
希望LivePhoto正常显示。

**Screenshots (If contains)**

**Version information**

- Device: iPhone 12 Pro Max
- OS: iOS 17.5.1
- Package Version: 9.0.3
- Flutter Version: 3.22.1

**Additional context**
在iPhone 11（iOS 14.2）的机器上测试，同样的情况
在iPhone 14 Pro Max（iOS 17.5.1）机器上测试，同样的情况

**Comment by kapibara91** [comment]
这个原因应该是[photo_manager](https://pub.dev/packages/photo_manager)的containsLivePhotos属性的默认值，从true变成false了，所以无法加载LIVEPHOTO。
如果可以的话，希望可以在AssetPickerConfig中加入对应的字段，来控制LIVEPHOTO的显示。谢谢！

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_wechat_assets_picker/issues/576#issuecomment-2103932996

**Comment by kapibara91** [comment]
> [#576 (comment)](https://github.com/fluttercandies/flutter_wechat_assets_picker/issues/576#issuecomment-2103932996)

感谢，问题已经解决。
