### ISSUE TITLE
[BUG] Does not get live IOS photos.

### ISSUE THREAD

**Issue by rajivmegamind** [fluttercandies/flutter_wechat_assets_picker#592]
@AlexV525 

**When I use the asset picker on my iOS device, it only retrieves normal pictures and does not get live IOS photos. Please investigate this issue.**

1. Go to app
2. Click on Pic asset
4. Live image not getting in IOS .

**Version information**

- Device: All IOS devices
- OS: IOS
- Package Version: wechat_assets_picker: ^9.0.4
- Flutter Version: 3.19.5

**Additional context**
Please fix this issue because my entire project depends on it.

**Comment by AlexV525** [comment]
See #576
