### ISSUE TITLE
升级到9.1.0后，小屏设备（iPhone 8）

### ISSUE THREAD

**Issue by enanso** [fluttercandies/flutter_wechat_assets_picker#598]
问题1：小屏设备（iPhone 8）拍摄按钮移除屏幕底部，无法正常开始拍摄；
![1](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/15317067/5bb0ffa2-b76c-437a-b123-9b10dff4dad6)

问题2：大屏设备 拍摄键那个球形有一点点在黑条外面了
![2](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/15317067/ecf12756-1b3e-42ac-b5b6-62c71bac632b)

升级前的代码：（升级后没改） 

  /// 相机
  static Future<AssetEntity?> camera({
    required BuildContext context,
    bool enableRecording = true,
    bool onlyEnableRecording = false,
  }) async {
    var result = await CameraPicker.pickFromCamera(
      context,
      pickerConfig: CameraPickerConfig(
        enableRecording: enableRecording,
        enableAudio: enableRecording,
        onlyEnableRecording: onlyEnableRecording,
        maximumRecordingDuration: const Duration(seconds: 60),
        // textDelegate:
        //     enableRecording ? const EnglishCameraPickerTextDelegate() : null,
        resolutionPreset: ResolutionPreset.high, // 画质 默认用720p
      ),
    );
    return result;
  }

**Comment by enanso** [comment]
问题1：小屏设备（iPhone 8）拍摄按钮移除屏幕底部，无法正常开始拍摄；

问题2：大屏设备   拍摄键那个球形有一点点在黑条外面了

升级前的代码：（升级后没改）
  /// 相机
  static Future<AssetEntity?> camera({
    required BuildContext context,
    bool enableRecording = true,
    bool onlyEnableRecording = false,
  }) async {
    var result = await CameraPicker.pickFromCamera(
      context,
      pickerConfig: CameraPickerConfig(
        enableRecording: enableRecording,
        enableAudio: enableRecording,
        onlyEnableRecording: onlyEnableRecording,
        maximumRecordingDuration: const Duration(seconds: 60),
        // textDelegate:
        //     enableRecording ? const EnglishCameraPickerTextDelegate() : null,
        resolutionPreset: ResolutionPreset.high, // 画质 默认用720p
      ),
    );
    return result;
  }

**Comment by AlexV525** [comment]
拍摄与选择库无关，提到拍照库。
