### ISSUE TITLE
Error when clicking on back button after detail view of a picture is opened

### ISSUE THREAD

**Issue by SchnMar** [fluttercandies/flutter_wechat_assets_picker#6]
When I open a picture in detail view in the AssetPicker and press the back button the following error is thrown:

`[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'currentlySelectedAssets' was called on null.
Receiver: null
Tried calling: currentlySelectedAssets
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      AssetPickerViewerState.syncSelectedAssetsWhenPop 
(package:wechat_assets_picker/src/widget/asset_picker_viewer.dart:235:55)
#2      ModalRoute.willPop (package:flutter/src/widgets/routes.dart:1263:26)
#3      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:3536:67)
#4      Navigator.maybePop (package:flutter/src/widgets/navigator.dart:1960:34)
#5      BackButton.build.<anonymous closure> (package:flutter/src/material/back_button.dart:108:21)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
#7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
<…>
`

Please let me know, if you need additional information. I'm working with the current beta channel version of Flutter.

**Comment by SchnMar** [comment]
Just created a pull request for this issue.

**Comment by AlexVincent525** [comment]
Please read the comment for the PR for more info.
