### ISSUE TITLE
[BUG] Preview Feature is not working correctly in IOS

### ISSUE THREAD

**Issue by neody3** [fluttercandies/flutter_wechat_assets_picker#601]
**Describe the bug**

Preview Feature is not working correctly in IOS
**How to reproduce**

1. Go to Preview screen
2. Unselect all images
3. Confirm button still clickable when no images selected

**Expected behavior**

Confirm button is not clickable when no images selected

**Screenshots (If contains)**

<img src="https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/112931071/c83d9a56-046c-48bb-b1e1-e96018efded9" width="300"/>

**Version information**

- Device: Iphone 15 virtual
- OS: 17.0.0
- Package Version: 9.1.0
- Flutter Version: 3.22.0

**Additional context**

I found that compare two lists is not good here.
Should we use listEquals to compare two lists?
https://api.flutter.dev/flutter/foundation/listEquals.html
https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/f0a65eb770c54401324b44557676eee423eb26bf/lib/src/delegates/asset_picker_viewer_builder_delegate.dart#L131

**Comment by AlexV525** [comment]
> I found that compare two lists is not good here. Should we use listEquals to compare two lists? https://api.flutter.dev/flutter/foundation/listEquals.html
> 
> https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/f0a65eb770c54401324b44557676eee423eb26bf/lib/src/delegates/asset_picker_viewer_builder_delegate.dart#L131

Not related.

**Comment by AlexV525** [comment]
The behavior was aligned with the WeChat.
