### ISSUE TITLE
[BUG] Android apply for permission read image permission, clicked yes but actually no

### ISSUE THREAD

**Issue by SeakyLuo** [fluttercandies/flutter_wechat_assets_picker#603]
**Describe the bug**

On my android phone, when I open the asset picker, it requests image permission. I clicked yes, but actually the permission request is rejected. You can see from the snapshot below.

**How to reproduce**

AndroidManifest
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />
```
Dart
````
import 'package:flutter/material.dart';
import 'package:wechat_assets_picker/wechat_assets_picker.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Upload Button Demo'),
        ),
        body: Center(
          child: InkWell(
            onTap: () async {
              List<AssetEntity>? result = await AssetPicker.pickAssets(
                context,
                permissionRequestOption: const PermissionRequestOption(androidPermission: AndroidPermission(type: RequestType.all, mediaLocation: true)),
                pickerConfig : AssetPickerConfig(maxAssets: 1, requestType: RequestType.image),
              );
            },
            child: Container(
              width: 50,
              height: 50,
              decoration: BoxDecoration(
                color: Colors.red,
                borderRadius: BorderRadius.circular(8),
              ),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(Icons.add_a_photo_rounded, color: Colors.red, size: 26),
                  const SizedBox(height: 4),
                  Text("上传图片", style: const TextStyle(fontSize: 11, color: Colors.red)),
                  const SizedBox(height: 2),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

}
````

Whether adding `permissionRequestOption` doesn't affect the bug.

**Expected behavior**

When user gives the permission, it should be actually given not rejected.

**Screenshots (If contains)**
![6cd4c2edd7cfb2a0a9735a9d2b198f26](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/25042708/f2eda3fd-e1f9-4a83-b791-baa27704f304)
![bd362669139b1c7557aa208a06320c77](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/25042708/41773b94-ed07-4795-8074-dc0dfd013cc7)
![c6a6902b049d338dc180d2594bd88d25](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/25042708/fe4c0fd7-2afc-46f4-90e8-f8c91629a00d)

**Version information**

- Device: Vivo X60 Pro+(v2056A), Vivo X Fold 3 Pro(2337a)
- OS: Origin OS 4
- Package Version: 9.1.0, 9.0.3
- Flutter Version: 3.19.6

**Comment by AlexV525** [comment]
You are requesting a different `RequestType` in `permissionRequestOption` and `pickerConfig`.

**Comment by SeakyLuo** [comment]
> You are requesting a different `RequestType` in `permissionRequestOption` and `pickerConfig`.

@AlexV525 This is not the reason. I don't have the permissionRequestOption initially. I added permissionRequestOption just trying to fix this problem.

**Comment by wubaibin** [comment]
> **Describe the bug 描述错误**
> 
> On my android phone, when I open the asset picker, it requests image permission. I clicked yes, but actually the permission request is rejected. You can see from the snapshot below.在我的 Android 手机上，当我打开资产选择器时，它会请求图像权限。我点击了“是”，但实际上权限请求被拒绝了。您可以从下面的快照中看到。
> 
> **How to reproduce 如何重现**
> 
> AndroidManifest Android清单
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android">
>     <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
>     <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
>     <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
>     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
>     <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
>     <uses-permission android:name="android.permission.INTERNET" />
>     <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
>     <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />
> ```
> 
> Dart 镖
> 
> ```
> import 'package:flutter/material.dart';
> import 'package:wechat_assets_picker/wechat_assets_picker.dart';
> 
> void main() {
>   runApp(MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: Scaffold(
>         appBar: AppBar(
>           title: Text('Upload Button Demo'),
>         ),
>         body: Center(
>           child: InkWell(
>             onTap: () async {
>               List<AssetEntity>? result = await AssetPicker.pickAssets(
>                 context,
>                 permissionRequestOption: const PermissionRequestOption(androidPermission: AndroidPermission(type: RequestType.all, mediaLocation: true)),
>                 pickerConfig : AssetPickerConfig(maxAssets: 1, requestType: RequestType.image),
>               );
>             },
>             child: Container(
>               width: 50,
>               height: 50,
>               decoration: BoxDecoration(
>                 color: Colors.red,
>                 borderRadius: BorderRadius.circular(8),
>               ),
>               child: Column(
>                 mainAxisAlignment: MainAxisAlignment.center,
>                 children: [
>                   const Icon(Icons.add_a_photo_rounded, color: Colors.red, size: 26),
>                   const SizedBox(height: 4),
>                   Text("上传图片", style: const TextStyle(fontSize: 11, color: Colors.red)),
>                   const SizedBox(height: 2),
>                 ],
>               ),
>             ),
>           ),
>         ),
>       ),
>     );
>   }
> 
> }
> ```
> 
> Steps to reproduce the behavior:重现该行为的步骤：
> 
> Whether adding `permissionRequestOption` doesn't affect the bug.添加`permissionRequestOption`是否不会影响该bug。
> 
> **Expected behavior 预期行为**
> 
> When user gives the permission, it should be actually given not rejected.当用户给予许可时，应该实际给予而不是拒绝。
> 
> **Screenshots (If contains)屏幕截图（如果包含）** ![6cd4c2edd7cfb2a0a9735a9d2b198f26](https://private-user-images.githubusercontent.com/25042708/347245256-f2eda3fd-e1f9-4a83-b791-baa27704f304.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTM1MzgsIm5iZiI6MTcyNTQxMzIzOCwicGF0aCI6Ii8yNTA0MjcwOC8zNDcyNDUyNTYtZjJlZGEzZmQtZTFmOS00YTgzLWI3OTEtYmFhMjc3MDRmMzA0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDAxMjcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkMGJjOGU0OWJiZjc5YWM1NDNiNTBmYTExMWRlYzQzMzIzMzY3MWVjNDMwZmE3MTAzODI3NTMyMmQxZWFmNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B2-UpZz1_b5TA_Oblbu7eCbB6F9cEh57ikm6QxsGD5s) ![bd362669139b1c7557aa208a06320c77](https://private-user-images.githubusercontent.com/25042708/347243181-41773b94-ed07-4795-8074-dc0dfd013cc7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTM1MzgsIm5iZiI6MTcyNTQxMzIzOCwicGF0aCI6Ii8yNTA0MjcwOC8zNDcyNDMxODEtNDE3NzNiOTQtZWQwNy00Nzk1LTgwNzQtZGMwZGZkMDEzY2M3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDAxMjcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiN2YwYWJjZTFhZGJhY2ExZmM3M2EwZmNhY2M1YTlmOGNkZjQ5YmM2NGZmODkwNzk1MGY3MjdjMjE5YTUxYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CaXzr3ItC9ebEbvZuw_67fLo-jrDb4t2JKzI4VQRkZw) ![c6a6902b049d338dc180d2594bd88d25](https://private-user-images.githubusercontent.com/25042708/347245266-fe4c0fd7-2afc-46f4-90e8-f8c91629a00d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTM1MzgsIm5iZiI6MTcyNTQxMzIzOCwicGF0aCI6Ii8yNTA0MjcwOC8zNDcyNDUyNjYtZmU0YzBmZDctMmFmYy00NmY0LTkwZTgtZjhjOTE2MjlhMDBkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDAxMjcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMWM0YzZhY2RlNmM5MmJhOTBmNDMwMDIxN2RlYzE4YTBiZTk2OGJkZGE4MzliYTI3YjJmM2ZkMjU4OTU2N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GaudlLTPPfD036YU9Ie9TO_ab0UWvB0JmPtwEjL-Pa8)
> 
> **Version information 版本信息**
> 
> * Device: Vivo X60 Pro+(v2056A), Vivo X Fold 3 Pro(2337a)设备：Vivo X60 Pro+(v2056A)、Vivo X Fold 3 Pro(2337a)
> * OS: Origin OS 4 操作系统：起源操作系统4
> * Package Version: 9.1.0, 9.0.3软件包版本：9.1.0、9.0.3
> * Flutter Version: 3.19.6 颤动版本：3.19.6

您好，请问您是怎么解决的。我现在只有在vivo上有这个问题
