### ISSUE TITLE
[BUG] 在flutter_module中使用单独使用没问题，但是往Android原生里嵌入点击没反应，有错误日志

### ISSUE THREAD

**Issue by xiaoxing1992** [fluttercandies/flutter_wechat_assets_picker#604]
**Describe the bug**

日志：[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method requestPermissionExtend on channel com.fluttercandies/photo_manager)
                                                                                         #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
                                                                                         <asynchronous suspension>
                                                                                         #1      PhotoManagerPlugin.requestPermissionExtend (package:photo_manager/src/internal/plugin.dart:69:24)
                                                                                         <asynchronous suspension>
                                                                                         #2      AssetPickerDelegate.permissionCheck (package:wechat_assets_picker/src/delegates/asset_picker_delegate.dart:36:32)
                                                                                         <asynchronous suspension>
                                                                                         #3      AssetPickerDelegate.pickAssets (package:wechat_assets_picker/src/delegates/asset_picker_delegate.dart:79:32)
                                                                                         <asynchronous suspension>
                                                                                         #4      _NewsPublishPageState._buildAddView.<anonymous closure> (package:flutter_module/android/news_publish_page.dart:141:24)
                                                                                         <asynchronous suspension>

**Version information**

- Device: 华为mate30pro
- OS: 鸿蒙OS4.2
- Package Version: [e.g. 9.10]
- Flutter Version: [e.g. v 3.22.2]

**Additional context**

**Comment by AlexV525** [comment]
与库无关，自行搜索相关文档。

**Comment by xiaoxing1992** [comment]
> 与库无关，自行搜索相关文档。

好的 感谢  大佬咱们有交流群吗

**Comment by xiaoxing1992** [comment]
> 与库无关，自行搜索相关文档。

感谢指导

**Comment by yfming93** [comment]
> > 与库无关，自行搜索相关文档。
> 
> 感谢指导

怎么解决的呀。MissingPluginException(No implementation found for method requestPermissionExtend on channel com.fluttercandies/photo_manager)

**Comment by yfming93** [comment]
> > > 与库无关，自行搜索相关文档。
> > 
> > 
> > 感谢指导
> 
> 怎么解决的呀。MissingPluginException(No implementation found for method requestPermissionExtend on channel com.fluttercandies/photo_manager)

找到根本原因了！

看 GeneratedPluginRegistrant.m 这个文件，里面列的注册插件名单中完全没有 photo_manager！这就是 MissingPluginException 的直接原因。

GeneratedPluginRegistrant.m 这个文件是 Flutter 工具链在 flutter pub get + pod install 时自动生成的。由于你是通过独立 Flutter Module 运行，需要触发 Cocoapods 重新生成这份注册文件，才能让 photo_manager 参与进来。
使用如下重新生成GeneratedPluginRegistrant.m 
cd ios && pod install --clean-install && cd ..

**Comment by yfming93** [comment]
我已经帮你直接修改了 ios/Runner/GeneratedPluginRegistrant.m 文件，将缺失的 flutter_image_compress_common (即 ImageCompressPlugin) 的导入和注册项手动添加进去了。

这是 flutter_image_compress 新版（利用了 Flutter Federated Plugins 架构，拆分出了 _common、_web 等平台实现）在某些特定 Flutter Module 工程或者旧版模版下，因 Flutter CLI 构建工具的一个已知 Bug 导致的：生成工具未能正确识别被 implements 指向的子插件，从而在生成注册表时遗漏了它。

现在你可以直接在 Xcode 或 Android Studio / VSCode 中重新运行（Run）你的 iOS 工程了。

提示：由于 GeneratedPluginRegistrant.m 是自动生成的文件，未来如果你执行非常深度的清理或重建，这段代码可能会被覆盖。如果下次再次被意外覆盖，只需把相同的两段注册代码粘贴回去即可。
