### ISSUE TITLE
[BUG] ios after taking photo or video

### ISSUE THREAD

**Issue by yishangfei** [fluttercandies/flutter_wechat_assets_picker#606]
**Describe the bug**
After taking a photo or video, the specialItem moves to the first position
need to slide down manually

**Screenshots (If contains)**
<img src="https://github.com/user-attachments/assets/63161e0f-b70b-44dd-89c3-207edb55e4ac" alt="IMG_4046" width="200"/><img src="https://github.com/user-attachments/assets/2e03d0a5-a1ff-4459-819d-7f7b4257278d" alt="IMG_4048" width="200"/>

**Version information**

- Device: iPhone15 Pro
- OS: 17.5.1
- Package Version:  wechat_assets_picker: ^9.1.0
- Flutter Version: [e.g. v2.5.0]

**Comment by yishangfei** [comment]
https://github.com/user-attachments/assets/264de09c-15ae-4187-8eef-7cbfcd42cd90

**Comment by chinghoi** [comment]
同样的问题

**Comment by chinghoi** [comment]
I used 9.2.0 is working

**Comment by AlexV525** [comment]
Fixed in #600.
