### ISSUE TITLE
[BUG] ACCESS_MEDIA_LOCATION权限问题

### ISSUE THREAD

**Issue by dong199101** [fluttercandies/flutter_wechat_assets_picker#61]
请问如果拒绝ACCESS_MEDIA_LOCATION权限，图片预览不成功，这个权限是android10必须要申请的么？
因为混合编译后，在预览图片界面，点击图片后，申请权限弹框即使允许权限，图片也会预览失败。

**Comment by AlexV525** [comment]
请依照 issue 模板进行描述。Ref: #28 .
