### ISSUE TITLE
[BUG] Too many images in an album, the list can't be loaded.

### ISSUE THREAD

**Issue by unwmun-arooo** [fluttercandies/flutter_wechat_assets_picker#610]
**Describe the bug**
When attempting to load a photo album with approximately 89,000 photos using the library, the album list fails to load and the app becomes unresponsive if it manages to load the list.

**How to reproduce**
1. Open the my app and select the "Load Photos" button.
2. Grant the "Full Access" permission for photos.
3. The app fails to load the photo list and becomes unresponsive.

**Expected behavior**
The photo list should be loaded, and the album list should be selectable.

**Screenshots (If contains)**
![call image picker](https://github.com/user-attachments/assets/f3d953c3-d223-4fdb-b62b-ba0c69499dc2)
![ios app setting - photo](https://github.com/user-attachments/assets/ec095b77-f3ca-4518-9f2b-7f50f603bdd3)

**Version information**

- Device: iPhone14,5
- OS: iOS 17.5.1
- Package Version: 9.0.0-dev.2
- Flutter Version: 3.16.9

**Additional context**

**Comment by ssorrychoi** [comment]
I am experiencing a similar issue. When there are a large number of photos, the image loading speed is significantly slow. This makes the app almost unusable as it takes an extremely long time to load the photos.

**Comment by unwmun-arooo** [comment]
@AlexV525 
Thank you for your confirmation.
BTW, in which version did you improve this?
Is it flutter or flutter_wechat_assets_picker?

**Comment by hutnikau** [comment]
I experience the same issue with about 80K images in the library. I use 9.4.0 version. 
In which version it was fixed?

**Comment by u9646** [comment]
face the same issue, use latest version, not know how to fix

**Comment by Paveldub** [comment]
Faced with the same issue!

**Comment by CaoGiaHieu-dev** [comment]
it not fixed at all . i have 32k image and it take ~1m to fetch and show image @AlexV525

**Comment by AlexV525** [comment]
If anyone who is facing the issue are using `FilterOptionGroup`, migrate to `AdvancedCustomFilter` to see improvement. Otherwise, file new issues with the minimal reprodible example at https://github.com/fluttercandies/fluttet_photo_manager
