### ISSUE TITLE
select images from the resource library did not refresh.

### ISSUE THREAD

**Issue by redgreenn** [fluttercandies/flutter_wechat_assets_picker#611]
"Using your official demo, there is an issue where selecting images from the resource library does not refresh when permissions are restricted. Please check."

For example, in my video, I selected four images, but only two are displayed.

•	iOS Device: iPhone14.  iOS 17.2
•	Package Version: wechat_assets_picker: ^9.2.0

https://github.com/user-attachments/assets/3451c20a-0009-443d-887b-467bb15c3003

**Comment by AlexV525** [comment]
Fixed by #615
