### ISSUE TITLE
[BUG] SpecialItemPosition.prepend 在IOS设备上，表现为 在列表后放入，应该是在列表前。

### ISSUE THREAD

**Issue by tfn290181662** [fluttercandies/flutter_wechat_assets_picker#612]
**Describe the bug**
SpecialItemPosition.prepend 在IOS设备上的表现为 在列表后放入。应该是才列表前才对

**How to reproduce**

 final List<AssetEntity>? images = await AssetPicker.pickAssets(
              context,
              pickerConfig: AssetPickerConfig(
                specialItemPosition: SpecialItemPosition.prepend,
                specialItemBuilder: (BuildContext context, AssetPathEntity? path, int length) {
          .....

4. Error occurred.

**Expected behavior**

**Screenshots (If contains)**
Android
![Xnip2024-08-08_11-48-11](https://github.com/user-attachments/assets/92ef2604-d189-4e1e-ac3d-7b9d901bd37a)
IOS
![Xnip2024-08-08_11-45-54](https://github.com/user-attachments/assets/1b01c8f6-d5c0-47f8-a3d1-26fdbc6f1f74)

**Version information**

- Device: iphone15 pro
- OS: IOS 17.5
- Package Version: 9.2.0
- Flutter Version: v3.22.3

**Additional context**

**Comment by AlexV525** [comment]
设计如此，倒置列表的顺序
