### ISSUE TITLE
[BUG] Limited permission overlay does not show up when paired with ```maxAssets: maxAssetsCount: 1``` and ```specialPickerType: SpecialPickerType.noPreview```

### ISSUE THREAD

**Issue by Dimilkalathiya** [fluttercandies/flutter_wechat_assets_picker#618]
**Describe the bug**
Limited permission overlay does not show up when paired with ```maxAssets: maxAssetsCount: 1``` and ```specialPickerType: SpecialPickerType.noPreview```

**How to reproduce**
Execute below mentioned code: 
```dart
AssetPicker.pickAssets(
          context,
          pickerConfig: AssetPickerConfig(
            maxAssets: 1,
            requestType: RequestType.image,
            specialPickerType: SpecialPickerType.noPreview,
          ),
        );
```

1. Execute above mentioned code on IOS device
2. Provide limited permission and select few assets and continue
3. Limited access overlay is not visible

**Expected behavior**
- Limited access overlay should be visible depending on permission and should not be influenced by above mentioned parameters

**Screenshots**

1. with ```maxAssets: maxAssetsCount: 1``` and ```specialPickerType: SpecialPickerType.noPreview```:

<img width="310" alt="Screenshot 2024-08-21 at 7 51 21 PM" src="https://github.com/user-attachments/assets/453a4580-1ae1-4e1b-bd33-2073aa7c7330">

2. if either of value is changed (eg: changing ```maxAssets: maxAssetsCount: 2``` OR removing optional property ```specialPickerType: SpecialPickerType.noPreview```):

<img width="305" alt="Screenshot 2024-08-21 at 7 52 08 PM" src="https://github.com/user-attachments/assets/e7782745-3d40-4d34-a44d-2cd63c2eff65">

**Version information**

- Device: iPhone 15 pro (simulator) 
- OS: iOS 17.5
- Package Version: 9.2.1
- Flutter Version: 3.24.0

**Additional context**

Culprit:

For android:
https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/f15336e9b77740b33918f159bb700e051e92e5e4/lib/src/delegates/asset_picker_builder_delegate.dart#L1089-L1090

For IOS:
https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/f15336e9b77740b33918f159bb700e051e92e5e4/lib/src/delegates/asset_picker_builder_delegate.dart#L1116-L1117

Solution:
Updating condition would probably fix issue:
```dart
if (isPreviewEnabled || !isSingleAssetMode || permissionNotifier.value == PermissionState.limited)
```

Questions:
1. Is above mentioned code there for specific reason or to avoid any issue?
2. If this is not expected behaviour please ping me i can generate PR :)

**Comment by AlexV525** [comment]
Hi @Dimilkalathiya. Thank you for your report and the PR. I've setup another change request to cover more details and cases, could you review it?
