### ISSUE TITLE
[BUG] Video preview orientation.

### ISSUE THREAD

**Issue by nareshfl99** [fluttercandies/flutter_wechat_assets_picker#622]
**Describe the bug**

Either from gallery or from camera,
If the user selected a video for preview, the orientation of video is fixed to landscape and fill screen.
Tried changing the settings for orientation in config and all. None of them worked.

**How to reproduce**

Once the package opens,
select a video for preview.

**Expected behavior**

Video in proper orientation or not fill the entire screen.

**Screenshots (If contains)**

![Screenshot_20240830-132402](https://github.com/user-attachments/assets/a4e6d53d-ad7b-4358-a2ad-c4656df0061f)

**Version information**

- Device: Android Emulator, Google Pixel 5, Google Pixel 10
- OS: Android 14
- Package Version: 9.2.1
- Flutter Version: 3.24.1

**Additional context**

None.

**Comment by AlexV525** [comment]
Please verify if this is a `video_player` issue.

**Comment by zxk-design** [comment]
> **Describe the bug**
> 
> Either from gallery or from camera, If the user selected a video for preview, the orientation of video is fixed to landscape and fill screen. Tried changing the settings for orientation in config and all. None of them worked.
> 
> **How to reproduce**
> 
> Steps to reproduce the behavior:
> 
> Once the package opens, select a video for preview.
> 
> **Expected behavior**
> 
> Video in proper orientation or not fill the entire screen.
> 
> **Screenshots (If contains)**
> 
> ![Screenshot_20240830-132402](https://private-user-images.githubusercontent.com/131775583/363092814-a4e6d53d-ad7b-4358-a2ad-c4656df0061f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MTQ0NDYsIm5iZiI6MTcyNTUxNDE0NiwicGF0aCI6Ii8xMzE3NzU1ODMvMzYzMDkyODE0LWE0ZTZkNTNkLWFkN2ItNDM1OC1hMmFkLWM0NjU2ZGYwMDYxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQwNTI5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmZlNTgyZTQ4NGQyZjFmOTRjYTI1NzA3MDA4NGM2MzY5NWMzNGI4NjVmMjI2MzYyZTMyNGQwYWVlNjA5MmQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c_wurTwO8XMrLMxbepihE1uV0XJKsHg9xYg1knJhwlE)
> 
> **Version information**
> 
> * Device: Android Emulator, Google Pixel 5, Google Pixel 10
> * OS: Android 14
> * Package Version: 9.2.1
> * Flutter Version: 3.24.1
> 
> **Additional context**
> 
> None.
请问你解决了吗
我使用 
`wechat_assets_picker: ^9.2.1
wechat_camera_picker: 4.3.1
  final AssetEntity? entity = await CameraPicker.pickFromCamera(
      Get.context!,
      locale: Get.locale,
      pickerConfig: CameraPickerConfig(
          enableAudio: true,
          enableRecording: true,
          enableScaledPreview: false,
          resolutionPreset: ResolutionPreset.medium,
          maximumRecordingDuration: 60.seconds),
    );`
出现了同样的问题，在拍摄视频预览的时候出现视频翻转， 并在 wechat_assets_picker: ^9.2.1或者在wechat_camera_picker: 4.3.1的demo中出现一样的情况， 并验证官方flutter video_play demo 并无出现异常问题，确定是wechat_camera_picker: 4.3.1有问题 

﻿

**Comment by AlexV525** [comment]
> 确定是wechat_camera_picker: 4.3.1有问题

﻿开到对应仓库，按照模板提供完整信息。

**Comment by gxhjsnt** [comment]
降级到video_player_android 2.6.0就正常了
应该是2.6.0之后Re-adds support for Impeller造成的orientation显示错误
https://docs.flutter.dev/release/breaking-changes/android-surface-plugins#note-on-camera-previews
是否需要适配最新的video_player?

**Comment by AlexV525** [comment]
> 降级到video_player_android 2.6.0就正常了 应该是2.6.0之后Re-adds support for Impeller造成的orientation显示错误

2.7.1 也可以正常显示。

> https://docs.flutter.dev/release/breaking-changes/android-surface-plugins#note-on-camera-previews 是否需要适配最新的video_player?

不需要，与本插件无关。

**Comment by gxhjsnt** [comment]
你把项目clone下来，修改video_player从^2.7.0到2.9.1，然后手机录一段视频，example运行起来从本地打开那个视频预览就能重现这个问题了。
因为wechat_asset_picker默认依赖video_player 2.7.x,对应的video_player_android版本是<=2.6.0的，如果我自己的项目也用了video_player，并且直接flutter pub add video_player,就会安装^2.9.1,会覆盖wechat_asset_picker默认的2.7.x，就会出现这个问题了。
![image](https://github.com/user-attachments/assets/c3c859c1-eb4f-4a2b-876c-de13d8396206)
![441725724098_ pic](https://github.com/user-attachments/assets/a6e623cf-4f67-4515-a664-8e07e9a0ff28)
