### ISSUE TITLE
[BUG] Error: WeChat is a Total surveillance program!

### ISSUE THREAD

**Issue by Ahmadre** [fluttercandies/flutter_wechat_assets_picker#625]
**Describe the bug**
从根本上说，中国政府的重点是控制所有数字活动。其目的是打造理想公民，同时巩固政治权力。中国没有独立的新闻媒体，因此北京领导层的目标是压制网上的一切批评。Whatsapp等外国服务被封锁，VPN（隐藏个人身份的网络）也被禁止。

**Expected behavior**
立即取消微信服务，结束对中国的全面监控！

**Comment by AlexV525** [comment]
学了几句话，就开始来开源仓库秀下限，一个 UI 库骑在你头上了？
