### ISSUE TITLE
[Feature] Add "Select All" button

### ISSUE THREAD

**Issue by grishatop1** [fluttercandies/flutter_wechat_assets_picker#637]
**Version information**
 - Device: *iPhone X*
 - Package Version: *v9.3.1*

**Is your feature request related to a problem?**

The main problem is that you can't drag and select multiple photos, so it makes selecting many photos really hard.
Also when you need to backup the whole gallery using another app that uses this picker, it's impossible if you have many photos.

**Describe the solution you'd like**

I think a great idea would be adding "Select All" button. Just select them all at once.

**Comment by AlexV525** [comment]
- Using the API that the `photo_manager` provides can manually obtain all assets without the picker.
- Using a custom builder delegate can add whatever widgets you need.

**Comment by vlavorini** [comment]
Maybe this "select all" feature can be added in the Example?
