### ISSUE TITLE
能否添加相机功能呢？

### ISSUE THREAD

**Issue by momtboy** [fluttercandies/flutter_wechat_assets_picker#64]
**Version information (版本信息)**
 - Device: *安卓 华为 meta20*
 - OS: **
 - Package Version: *v4.2.1*
 - Flutter Version: *v1.20.0*

期望在格子的第一个将拍照功能加入，目前微信APP的照片选择器第一个是拍照功能.

**Comment by AlexV525** [comment]
请认真尝试demo，谢谢。
