### ISSUE TITLE
[BUG] 部分手机出现无法加载相册图片

### ISSUE THREAD

**Issue by tourdt** [fluttercandies/flutter_wechat_assets_picker#641]
flutter_wechat_assets_picker版本：9.3.0
IOS系统版本：17.6.1
以前都可以正常使用，但是用着用着，就出现下面的情况：
<img width="466" alt="image" src="https://github.com/user-attachments/assets/d915565a-5e66-4702-828e-9cd9d463f4d4">

**Comment by u9646** [comment]
has same issue, not know how to reproduce

**Comment by lockingroad** [comment]
has same issue, not know how to reproduce
