### ISSUE TITLE
[BUG] Android设备取消选择照片，点击确认依然选中

### ISSUE THREAD

**Issue by FanYuanBo888** [fluttercandies/flutter_wechat_assets_picker#646]
**Describe the bug**
Android 设备上，预览模式下取消勾选，点击确定依然可以选择照片

1. 直接运行git的官方demo，点击选择照片
2. 勾选一张照片
3. 点击左下角的预览
4. 在预览模式下点击右上角的勾选按钮，取消勾选，此时没有一张照片是选中状态
5. 此时右下角的确认按钮依然可以点击，并成功选择到照片

**Expected behavior**
应该和iOS一样，取消勾选后，如果没有照片选中，右下角的确认按钮无法点击。

**Screenshots (If contains)**
![IMG_4831](https://github.com/user-attachments/assets/ff728421-2e0c-4550-8fcc-86c339d749e3)
![IMG_4832](https://github.com/user-attachments/assets/8b2270df-779c-4e48-85af-6858bc070738)

**Version information**

- Device: HUAWEI P20
- OS: HarmonyOS 3.0.0
- Package Version: v9.3.3
- Flutter Version: 3.22.3

**Comment by AlexV525** [comment]
该行为与微信一致

**Comment by yishangfei** [comment]
https://github.com/user-attachments/assets/e3d68500-22c9-44b6-8942-161004d9d823

@AlexV525

**Comment by AlexV525** [comment]
> Record_2024-10-29-14-36-03.-.Compressed.with.FlexClip.mp4 

issue 描述的场景与视频不一致，如果有其他问题请单独开 issue 和 PR。
