### ISSUE TITLE
[Feature] Deprecate Android READ_MEDIA... permissions

### ISSUE THREAD

**Issue by NorbertCsorgoEF** [fluttercandies/flutter_wechat_assets_picker#649]
Greetings!

The official README guideline mentions that the package needs **READ_MEDIA_IMAGES** & **READ_MEDIA_VIDEO** permissions. The problem is that it makes the package non-compliant with the latest Play Store policies, with [this](https://support.google.com/googleplay/android-developer/answer/14115180?hl=en) to be more specific.

Will this be solved as part of the package or do we have to use another one? Apps cannot use these permissions if they are needed only infrequently and not as a core functionality. They suggest using Android Photo Picker.

**Comment by AlexV525** [comment]
> Will this be solved as part of the package

No.

**Comment by vanyasem** [comment]
@AlexV525 that's a shame, because it basically means `wechat_assets_picker` is now incompatible with Google Play, as apps that integrate `wechat_assets_picker` as a dependency will now get automatically rejected from Google Play.

**Comment by AlexV525** [comment]
> @AlexV525 that's a shame, because it basically means `wechat_assets_picker` is now incompatible with Google Play, as apps that integrate `wechat_assets_picker` as a dependency will now get automatically rejected from Google Play.

Yes, shame on Google Play as always. Deprecation is a business choice. The library only provides the ability as-is, the picker will not work without these permissions.

**Comment by vanyasem** [comment]
@AlexV525 This library does support iOS "limited" gallery access, I don't see why it couldn't support "limited' gallery access on Android via the new Photo Picker, which is almost a direct copy of its iOS counterpart: https://android-developers.googleblog.com/2023/04/photo-picker-everywhere.html

**Comment by AlexV525** [comment]
> I don't see why it couldn't support "limited' gallery access on Android via the new Photo Picker, which is almost a direct copy of its iOS counterpart: https://android-developers.googleblog.com/2023/04/photo-picker-everywhere.html

Are you using the library? It already supports the limited assets on Android. The [policy](https://support.google.com/googleplay/android-developer/answer/14115180) says you need to use a native picker, which does not equal limited access.
