### ISSUE TITLE
I would be glad if i can change the language in the picker UI 

### ISSUE THREAD

**Issue by Gbogboade1** [fluttercandies/flutter_wechat_assets_picker#65]
**Version information (版本信息)**
 - Device: *e.g. iPhone6*
 - OS: *e.g. iOS 13.4*
 - Package Version: *e.g. v2.1.0*
 - Flutter Version: *e.g. v1.17.1*

**Is your feature request related to a problem?  (功能是否与已有问题关联)**
A clear and concise description it it's related to a exist problem. (如果与已有问题有关，请准确描述)

**Describe the solution you'd like (描述你期望的解决方案)**

**Describe alternatives you've considered (其他解决方案或疑虑)**

**Additional context (附加内容)**

**Comment by AlexV525** [comment]
Closing, due to the feature has already described in the readme.
