### ISSUE TITLE
是否可以拍照的时候，仅拍照，不用长按录制视频功能？

### ISSUE THREAD

**Issue by zbyJade** [fluttercandies/flutter_wechat_assets_picker#66]
**Version information (版本信息)**
 - Device: *e.g. iPhone6*
 - OS: *e.g. iOS 13.4*
 - Package Version: *e.g. v2.1.0*
 - Flutter Version: *e.g. v1.17.1*

**Is your feature request related to a problem?  (功能是否与已有问题关联)**
是否可以拍照的时候，仅拍照，不支持长按录制视频？

**Describe the solution you'd like (描述你期望的解决方案)**

**Describe alternatives you've considered (其他解决方案或疑虑)**

**Additional context (附加内容)**

**Comment by AlexV525** [comment]
请认真看 wechat_camera_picker 的文档。
