### ISSUE TITLE
[Feature] Windows平台支持

### ISSUE THREAD

**Issue by ddxl123** [fluttercandies/flutter_wechat_assets_picker#670]
**Version information**
 - OS: windows

**Is your feature request related to a problem?**
[[](url)](https://github.com/fluttercandies/flutter_wechat_assets_picker/issues/10#issuecomment-628345130)

**Describe the solution you'd like**
希望能够增加windows平台支持（还有鸿蒙os？），不然就得导入其他包了

**Comment by AlexV525** [comment]
无法支持。
