### ISSUE TITLE
PhotoManager.editor.deleteWithIds not working on android api 29 and above

### ISSUE THREAD

**Issue by ibragunduz** [fluttercandies/flutter_wechat_assets_picker#69]
PhotoManager.editor.deleteWithIds working properly on ios and up to android api 28. But not working on android 29.

**Comment by AlexV525** [comment]
Please update your description according to #28 .

**Comment by joshua750** [comment]
i am facing same issue please tell me solution deleting in android 29 here is my code

  late List <AssetEntity?> selectedAssets;

  Future<void> pickImageAndDelete() async {
    List<AssetEntity>? result = await AssetPicker.pickAssets(
      context,
      pickerConfig: const AssetPickerConfig(
        requestType: RequestType.image,
        maxAssets: 20,
      ),
    );

    if (result != null && result.isNotEmpty) {
      setState(() {
        selectedAssets = result; // Store selected assets in a list
      });
      deleteSelectedImages(); // Call the method to delete selected images
    }
  }

  Future<void> deleteSelectedImages() async {
    if (selectedAssets != null && selectedAssets.isNotEmpty) {
      List<String> ids = selectedAssets.map((asset) => asset!.id).toList();

      await PhotoManager.editor.deleteWithIds(ids);

      setState(() {
        print('delete photos');
        selectedAssets =[];
      });
    }
  }
