### ISSUE TITLE
PhotoManager.editor.deleteWithIds not working on android api 29 and above

### ISSUE THREAD

**Issue by ibragunduz** [fluttercandies/flutter_wechat_assets_picker#70]
PhotoManager.editor.deleteWithIds working properly on ios and up to android api 28. But not working on android 29.

1. Clone the example flutter_wechat_assets_picker project.
2. Go to single_assets_page.dart file.
3. Add this (PhotoManager.editor.deleteWithIds([assets.first.id]);) line in _selectedAssetDeleteButton method's gesture detector onTap callback to delete media.
4. Run app on emulator have api 29 and pick one photo from "Single" tab and see the selected assets panel.
5. Touch the selected photo the delete(X) button will be available.
6. Touch to delete button and you will continue to see your selected photo on gallery.
7. If you run app on emulator with api 28 or below the selected photos will be deleted.

[Test on api 27]
We want to delete selected image from the gallery. And it works fine on api 28 or below.
[https://streamable.com/iof195](url)

[Test on api 29]
Please notice! After deleting the image it is not showing on gallery so its works fine on api 28 or below.
But on api 29 the deleted images showing again on gallery. Probably its not deleting anytime.
[https://streamable.com/tg429z](url)

**Comment by AlexV525** [comment]
cc @CaiJingLong

**Comment by muhammedEmir06** [comment]
same issue

**Comment by AlexV525** [comment]
@ibragunduz @muhammedEmir06 Could you try override the `photo_manager` to `0.6.0-dev.5`?

```yaml
dependency_overrides:
  photo_manager: ^0.6.0-dev.5
```

**Comment by ibragunduz** [comment]
@AlexV525 Unfortunately not solved.

**Comment by AlexV525** [comment]
Thanks for the feedback. Currently reaching @CaiJingLong and debugging.

**Comment by CaiJingLong** [comment]
I published a new version: 0.6.0-dev.6.
You can try to test it.

**Comment by ibragunduz** [comment]
Thank you so much @CaiJingLong . Its working properly when i try to delete only one item. But for the multiple delete it is seems have some problems. When i add more than items into the list, its asking me for every items on a new dialog. If i remember correctly, android let us to delete multiple items on one dialog screen.

**Comment by CaiJingLong** [comment]
@ibragunduz 
API 29 not support delete multiple asset in one dialog.

**Comment by CaiJingLong** [comment]
The interesting thing is that both 30 and 28 are supported.

**Comment by CaiJingLong** [comment]
I personally recommend following the approach in the documentation: [Api 29](https://github.com/CaiJingLong/flutter_photo_manager#android-q-android10--api-29).

**Comment by AlexV525** [comment]
photo_manager 0.6.0 has been published.
