### ISSUE TITLE
[BUG] Error with something

### ISSUE THREAD

**Issue by zhanchi88** [fluttercandies/flutter_wechat_assets_picker#71]
Running "flutter pub get" in ieg_dirsir...
Launching lib\main.dart on HWI TL00 in debug mode...
Running Gradle task 'assembleDebug'...
ע: D:\hj\flutter_sdk\.pub-cache\hosted\pub.flutter-io.cn\flutter_sound-5.1.1\android\src\main\java\com\dooboolab\fluttersound\Session.javaʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: D:\hj\flutter_sdk\.pub-cache\hosted\pub.flutter-io.cn\rongcloud_im_plugin-4.0.3\android\src\main\java\io\rong\flutter\imlib\RCIMFlutterWrapper.javaʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: ĳЩ�����ļ�ʹ����δ�����򲻰�ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
D:\hj\flutter_sdk\.pub-cache\hosted\pub.flutter-io.cn\video_player-1.0.0\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java:11: ����: �Ҳ�������
import io.flutter.FlutterInjector;
                 ^
  ����:   �� FlutterInjector
  λ��: ����� io.flutter
D:\hj\flutter_sdk\.pub-cache\hosted\pub.flutter-io.cn\video_player-1.0.0\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java:77: ����: �Ҳ�������
    final FlutterInjector injector = FlutterInjector.instance();
          ^
  ����:   �� FlutterInjector
  λ��: �� VideoPlayerPlugin
D:\hj\flutter_sdk\.pub-cache\hosted\pub.flutter-io.cn\video_player-1.0.0\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java:77: ����: �Ҳ�������
    final FlutterInjector injector = FlutterInjector.instance();
                                     ^
  ����:   ���� FlutterInjector
  λ��: �� VideoPlayerPlugin
3 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':video_player:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
Exception: Gradle task assembleDebug failed with exit code 1[](url)

**Comment by AlexV525** [comment]
请按照issue模板提交。Ref: #28
