### ISSUE TITLE
[BUG] Error with something

### ISSUE THREAD

**Issue by zhanchi88** [fluttercandies/flutter_wechat_assets_picker#72]
本人使用两个插件分别是 

  wechat_camera_picker: 1.1.0+1
  wechat_assets_picker: 4.1.0+4
这两个均依赖 VideoPlayerPlugin，使用以上版本是没有问题的，wechat_assets_picker 4.2.2，wechat_camera_picker 1.3.0就会报错。

[log.txt](https://github.com/fluttercandies/flutter_wechat_assets_picker/files/5500736/log.txt)
![$B1S4M_B2(1{OG~ 5QO58I](https://user-images.githubusercontent.com/33199875/98356715-fedf6500-205e-11eb-9bd3-f3e9d4a75d87.png)

**Comment by AlexV525** [comment]
Demo使用了4.2.2以上的picker，1.3.0的camera picker，均未报错，你提供的不是错误信息。

**Comment by AlexV525** [comment]
并且，请按照issue模板开issue。

**Comment by zhanchi88** [comment]
在flutter 1.20.4呢？

**Comment by AlexV525** [comment]
![image](https://user-images.githubusercontent.com/15884415/98368735-c6e21d00-2072-11eb-84da-a1704a02c113.png)
