### ISSUE TITLE
[BUG] iOS preview shows previous image if the picture has been edited

### ISSUE THREAD

**Issue by Hynsen** [fluttercandies/flutter_wechat_assets_picker#74]
**Describe the bug (描述)**
iOS大图预览涂抹后的图片显示的是原图

**How to reproduce (如何复现)**
iPhone截屏一张图片，涂抹后保存至相册，打开预览时图片涂抹消失，显示的依然是涂抹前的原图

**Comment by CaiJingLong** [comment]
Try use photo_manager the newest dev version.
```yaml
  photo_manager: ^0.6.0-dev.7
```
