### ISSUE TITLE
[Feature] After clicking the picture, enter the preview, the picture cannot be selected

### ISSUE THREAD

**Issue by Evsio0n** [fluttercandies/flutter_wechat_assets_picker#75]
**Version information (版本信息)**
 - Device: *All devices.*
 - OS: *iOS*
 - Package Version: *Til newest*
 - Flutter Version: *Til newest*

**Is your feature request related to a problem?  (功能是否与已有问题关联)**
No
**Describe the solution you'd like (描述你期望的解决方案)**
After clicking the picture, enter the preview view, the picture cannot be selected

**Describe alternatives you've considered (其他解决方案或疑虑)**
After clicking the picture, enter the preview view, the picture cannot be selected

**Additional context (附加内容)**
nil,I will figure it out,and make pull request later.

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_wechat_assets_picker/issues/28
