### ISSUE TITLE
[BUG]  loading feedback lacks during iCloud synchronization image loading

### ISSUE THREAD

**Issue by Evsio0n** [fluttercandies/flutter_wechat_assets_picker#76]
**Version information (版本信息)**
 - Device: *All devices.*
 - OS: *iOS*
 - Package Version: *Til newest*
 - Flutter Version: *Til newest*

**Is your feature request related to a problem?  (功能是否与已有问题关联)**
No
**Describe the solution you'd like (描述你期望的解决方案)**
loading feedback lacks during iCloud synchronization image loading
**Describe alternatives you've considered (其他解决方案或疑虑)**
loading feedback lacks during iCloud synchronization image loading
**Additional context (附加内容)**
nil,I will figure it out,and make pull request later.

**Comment by AlexV525** [comment]
内容与模板不符，请按照 #28 提出issue。
