### ISSUE TITLE
[BUG] Get HEIC file with iOS when the image has been cropped by System

### ISSUE THREAD

**Issue by xlyasdasd** [fluttercandies/flutter_wechat_assets_picker#79]
**Describe the bug (描述)**
Get HEIC file with iOS when the image has been cropped by System.
选择被iOS系统裁剪的图片，会得到HEIC文件，未被裁剪的则不会.

**How to reproduce (如何复现)**
第一步，在iOS手机，裁剪一张图片,
第二部，使用flutter_wechat_assets_picker选择图片，打印asset对象，得到HEIC文件
Steps to reproduce the behavior (描述复现步骤):
1. Go to Picture in iOS OS.
2. Crop an image.
3. Select the image with flutter_wechat_assets_picker in App.
4. Get HEIC

**Expected behavior (期望行为)**
A JPG file.

**Screenshots (If contains) (是否有截图可以提供)**

![image](https://user-images.githubusercontent.com/6210545/102742954-41e86400-4391-11eb-9f26-d7387c071a9c.png)

**Device information (设备信息)**
 - Device: iphone SE
 - OS: iOS 14.3
 - Package Version:  5.0.0-dev.3
 - Flutter Version: 1.22

**Additional context (附加信息)**
Add any other context about the problem here. 在此提供更多的内容。

**Comment by CaiJingLong** [comment]
iOS系统提供什么格式，我也管不了
