### ISSUE TITLE
[Feature] Getting path from selected asset

### ISSUE THREAD

**Issue by muhammedEmir06** [fluttercandies/flutter_wechat_assets_picker#80]
Hi;
I want to reach the path of media which i selected from gallery by weChat asset picker. when i take the path, it only returns cache path. This isn't what i want. For Android devices for example: /storage/emulated/0/MyFolder/Image.jpg

**Comment by AlexV525** [comment]
Please file the issue with issue templates. Ref #28 .

**Comment by muhammedEmir06** [comment]
> Please file the issue with issue templates. Ref #28 .
@AlexV525 Can you check again please, this feature is important for me :)

**Comment by AlexV525** [comment]
File a new issue with *Bug report* template, provide all information that the template required. Otherwise there are nothing I can do.
