### ISSUE TITLE
[Feature] Need Folder Path Of Picked Asset 

### ISSUE THREAD

**Issue by ibragunduz** [fluttercandies/flutter_wechat_assets_picker#81]
**Version information (版本信息)**
 - Device: Xiaomi Note 8 Pro
 - OS: Android 10
 - Package Version: v4.2.2
 - Flutter Version: v1.22.3

**Is your feature request related to a problem?  (功能是否与已有问题关联)**
No it's not a problem. But we should use our requested feature to continue use the WechatAssetsPicker library.

**Describe the solution you'd like (描述你期望的解决方案)**
1- I choosing a asset.
2- I got some information about the my selected asset but I cant get the real folder path of the asset.
3- Folder paths similar to this "/storage/emulated/0/Screenshots/2020_12_20_3938293283.png".

**Describe alternatives you've considered (其他解决方案或疑虑)**
We should take the folder path of the picked asset after the pick screens returned data.

**Additional context (附加内容)**
![thread-138537-4018708289466783266](https://user-images.githubusercontent.com/24707258/103346486-28d46700-4aa5-11eb-87ac-3470fd4dd933.jpeg)

**Comment by AlexV525** [comment]
Why this is not fit for your case? And please provide your usage code. https://github.com/fluttercandies/flutter_wechat_assets_picker#how-can-i-get-path-from-the-assetentity-to-integrate-with-file-object-upload-or-edit

**Comment by muhammedEmir06** [comment]
<img width="2010" alt="Ekran Resmi 2020-12-31 11 01 57" src="https://user-images.githubusercontent.com/73937320/103400920-ea4bb480-4b57-11eb-876e-99abc6b402a2.png">

It returns cache path like this /data/user/0/com.fluttercandies.wechatAssetsPickerExample/cache/4526_origin_1609400892908.jpg, but it isn't what i want.
I need the path of media before i pick. Example Path: /storage/emulated/0/MyFolder/4526_origin_1609400892908.jpg

**Comment by AlexV525** [comment]
Can you try with an Android 9 (28) device and see if the path is in `/storage` ?

**Comment by AlexV525** [comment]
But there are something I'm curious, why the path is important in your case? Is there any details can be shared?

**Comment by CaiJingLong** [comment]
Without the concept of folder, the album is provided by the system.

The file/originFile is provided just for convenience in the flutter.

iOS applications are sandboxed, so getting originFile or file will always trigger IO, and the corresponding files will be cached in the application sandbox.
