### ISSUE TITLE
记录：android10 ，HUAWEI  P30、X10，打开资源选择，会存在两次以上的请求存储权限弹框 （Permission）

### ISSUE THREAD

**Issue by ismanong** [fluttercandies/flutter_wechat_assets_picker#82]
本问题，只记录，不太需要追踪接解决，给遇到问题的人留个言。

现象是：
1. 选择图片选择器之前，会请求第一次存储权限弹框，选择允许，
2. 点击图片列表任意一个图片，进入预览，都会存在重新请求存储权限弹框，
3. 此时点了禁止后，图片预览还可以正常展示，所有功能都正常，
4. 但是图片列表点击或者预览界面切换另一张图片，就会在再次提示请求存储权限弹框，
5. 直到用户点了允许后，便不会再提示。

此问题，再oppo手机上没有复现，也是Android10。

看过安卓官方的文档，存储机制有更新。具体还不太明白，
故此推断：不是此包问题，而是安卓有了新的变化.....

如果有人发现此问题，并可以找到答案，可以再这里发表一些看法。

**Comment by AlexV525** [comment]
![image](https://user-images.githubusercontent.com/15884415/104038536-352c9280-5210-11eb-9c19-471e21b852ed.png)

**Comment by AlexV525** [comment]
猜测是系统集成了云相册，导致除了普通存储以外还需要另外的存储权限。该问题与 Android 10 (29) 无关，在其他机型上暂未发现问题。

**Comment by AlexV525** [comment]
cc @CaiJingLong

**Comment by L-X-J** [comment]
在 Oppo(Android1 8.1) 和小米12pro（Android13）复现出此问题，出现权限申请弹窗后点击拒绝，会再出一次弹窗，再次点击拒绝才会进入 onError
代码示例：
```dart
AssetPicker.pickAssets(context,
          pickerConfig: const AssetPickerConfig(
              maxAssets: 1,
              requestType: RequestType.common))
          .then((result)  async {
        // 其他逻辑.... 
      }).onError(permissionDeniedToProcessImageSelector);
```

https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/31652110/0184b6f4-ca18-4296-b96d-7c98ae9e9ec9
