### ISSUE TITLE
/Users/xxx/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-1.0.1/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java:10: 错误: 找不到符号 import io.flutter.FlutterInjector;

### ISSUE THREAD

**Issue by a943999733** [fluttercandies/flutter_wechat_assets_picker#85]
**安装完编译就报错**
/Users/xxx/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-1.0.1/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java:10: 错误: 找不到符号
import io.flutter.FlutterInjector;
安装完编译就报错

**How to reproduce (如何复现)**
environment:
  sdk: ">=2.7.0"

  wechat_assets_picker: ^4.2.2

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.provide.flutter_app"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

请提供一个**最小化的demo**用于复现，而不要提供**整个项目或者不完整的页面**，否则我们有权拒绝你的请求。

Steps to reproduce the behavior (描述复现步骤):
集成进来编译就报错

hannel stable, 1.20.2, on Mac OS X 10.15.7 19H114, locale
    zh-Hans-CN)

**Comment by AlexV525** [comment]
References: #73 , #28 .
