### ISSUE TITLE
[BUG] Performance regression when call picker

### ISSUE THREAD

**Issue by AlexV525** [fluttercandies/flutter_wechat_assets_picker#87]
We received a report about the performance issue when the picker is called. More precisely, a noticeable stuck is appeared when running assets list fetching.

Below screenshot shows the dropping frame rates when loading list. Even if it's under *debug mode*, it's still worth investigate.

## How to reproduce
Simply call the picker. The more assets can be listed in the device, the more obvious this issue exist.

## Screenshots (If contains)
![image](https://user-images.githubusercontent.com/15884415/110087310-71bed980-7dce-11eb-8193-a48a3ac5479e.png)

## Additional context
* `getFirstThumbFromPathEntity` method is not affecting this issue.

**Comment by AlexV525** [comment]
Currently not repo in profile mode... 👀

**Comment by AlexV525** [comment]
No reproducible condition achieved yet.

**Comment by yuhaya** [comment]
你好，我也有相同的问题，运行在debug模式下，当手机上视频文件比较多的时候，调用资源选择器出现明显的卡顿掉帧现象，但是我把手机中视频文件删除后明显好一些了，我仔细和wechat对比了一下，发现wechat里面视频文件时长是异步一个个更新的，而我们的这个是是在第一次打开的时候全部都计算好了，所以我想是否能实现异步更新资源详细信息来缓解掉帧卡顿问题（ Hello, I also have the same problem, running in debug mode, when there are more video files on the phone, the call resource selector appears to be obviously Caton dropped frame phenomenon, but I deleted the video file in the phone after the obvious better, I carefully compared with wechat, found that the length of the video file in wechat is asynchronous one by one update, and our one is all calculated when it is opened for the first time, So I wonder if I can implement asynchronous update of resource details to alleviate the problem of dropped frame stuttering）
