### ISSUE TITLE
[BUG] After apple device Settings specialPickerType: specialPickerType wechatMoment video display is not complete and cannot be selected

### ISSUE THREAD

**Issue by ihongwu** [fluttercandies/flutter_wechat_assets_picker#88]
**Describe the bug**
After apple device Settings specialPickerType: specialPickerType.wechatMoment video display is not complete and cannot be selected，The incomplete display persisted on the iOS device under test

**How to reproduce **
```
final List<AssetEntity> assets = (await AssetPicker.pickAssets(
      context,
      selectedAssets: [],
      themeColor:defaultColor,
      maxAssets:9,
      pageSize: 20,
      specialPickerType:SpecialPickerType.wechatMoment,
))!;
```

**Steps to reproduce the behavior:**
1. Click the Select Photo button
2. See error

**Expected behavior**
Can display and select video normally

**Screenshots (If contains)**
![image](https://user-images.githubusercontent.com/21274377/110731574-8df2c880-825d-11eb-871a-c168b17d0016.png)
![image](https://user-images.githubusercontent.com/21274377/110731717-d5795480-825d-11eb-9ec8-e882b98801fa.png)

**Device information**
 - Device: iPhone6s plus and Iphone11 pro max 
 - OS:  iOS14.0.1 and IOS14.0.0
 - Package Version: 5.0.0
 - Flutter Version: 2.0.0

**Comment by AlexV525** [comment]
Confirmed with the layout affect slightly. There will be another enhancement to the special wechat moment mode at the same time.
