### ISSUE TITLE
[REQUEST] The new null safety code design has a serious issue regarding AssetEntity

### ISSUE THREAD

**Issue by Letalus** [fluttercandies/flutter_wechat_assets_picker#89]
When I just recently updated the package to 5.0.1 it hit me pretty hard.
According to the own documentation the f.e. duration of an AssetEntity should have a default value of 0.
Yet within null safety it is declared as required.

Furthermore the property isFavorite or orientation is also set as required even if they are platform specific properties --> then those kind of properties should not really be set to required.

I'm using the AssetEntity object pretty often within my app.

Therefore I suggest, that we change the declaration of the AssetEntity constructor the following way, so it will become more readable and understandable:

  AssetEntity({
    required this.id,
    required this.typeInt,
    this.duration = 0,
    this.width = 0,
    this.height = 0,
    this.orientation = 0,
    this.isFavorite = false,
    this.title,
    this.createDtSecond,
    this.modifiedDateSecond,
    this.relativePath,
  });

I really hope we can improve the code, because many values really don't need to be required

**Comment by AlexV525** [comment]
Could you move the issue to the `photo_manager`'s repo? This is not really a good place to start the improvement. Anyway thanks for the advice. Let's continue with the correct repo.

**Comment by Letalus** [comment]
oh sure sorry for the mistake

**Comment by AlexV525** [comment]
Let me know if you filed a new issue. :)
