### ISSUE TITLE
[BUG] high memory and CPU consumption

### ISSUE THREAD

**Issue by fzyzcjy** [fluttercandies/flutter_wechat_assets_picker#96]
**Describe the bug (描述)**
Thanks for the lib! Since this is a pure-Flutter solution, it seems that the memory and CPU consumption will be high on low-end devices, compared with native solutions?

**How to reproduce (如何复现)**
just use the sample app and run on low end device

Steps to reproduce the behavior (描述复现步骤):
1. download sample project
2. run it on lowend device

**Expected behavior (期望行为)**
low cpu / memory consumption

**Screenshots (If contains) (是否有截图可以提供)**
n/a

**Device information (设备信息)**
 - Device: lowend iphone or android
 - OS: n/a
 - Package Version: latest
 - Flutter Version: 2.0

**Additional context (附加信息)**
n/a

**Comment by AlexV525** [comment]
Images, event thumbnails, consumes a lot in Flutter, as everybody might acknowledged before. Currently the memory consumption by Flutter itself or images look good to me. And the CPU consumption? Hmm, I would say it's kinda out of support, as you can see in the source code, there are no magic to improve the performance but only make the scope of those changing widgets smaller and smaller.

If you have any comparison between native plugins/projects, or WeChat itself, with this project, please paste them here. It's better to have a overview and some pictures to indicates the consumption currently.

**Comment by fzyzcjy** [comment]
@AlexV525 Currently I do not have much comparisons. But just by a thought experiment (as we know the limitations of Flutter), I am afraid many potential users of this library leave because of this problem. Indeed, if the performance is shown to be acceptable and put in README, then IMHO more people may want to use it.

**Comment by AlexV525** [comment]
Please run the example in release mode. Performance shouldn't be list in README as a selling point, since a normal package has a normal performance, it's worth listing only if there are some performance issues.

**Comment by fzyzcjy** [comment]
@AlexV525 Sure, it is not a selling point. I am just worried whether it is a *shortcoming* that people may think about when looking at the README. So if you do not mention it, people may thought about the poor performance and leave.

Anyway this is just a suggestion to improve the library.

**Comment by AlexV525** [comment]
😄 If you're saying that I should add a notice about the memory and any other performance regression, I will say no, since it has none, as I can tell you in confidence.

In the meantime, I want to say you might regret it if you don't stay with this package since many people have already shipped it into their products.

I am just kidding. Thanks for the suggestion.

**Comment by fzyzcjy** [comment]
😄 You are welcome. 

> should add a notice about the memory and any other performance regression

No, I mean add a notice about there is *no* memory and any other performance regression
