### ISSUE TITLE
[BUG] iOS This application is not allowed to access Photo data.

### ISSUE THREAD

**Issue by Lcccocoa** [fluttercandies/flutter_wechat_assets_picker#99]
**Describe the bug (描述)**

Carsh log:
This application is not allowed to access Photo data.

0 CoreFoundation | ___exceptionPreprocess + 228
1 libobjc.A.dylib | objc_exception_throw + 56
2 PhotoLibraryServices | 0x0000000210022000 + 179160
3 Photos | 0x0000000210f3f000 + 809144
4 Photos | 0x0000000210f3f000 + 602268
5 Photos | 0x0000000210f3f000 + 687268
6 AssetsLibraryServices | 0x000000020fd47000 + 38072
7 libdispatch.dylib | __dispatch_client_callout + 16
8 libdispatch.dylib | __dispatch_continuation_pop$VARIANT$armv81 + 404
9 libdispatch.dylib | __dispatch_source_invoke$VARIANT$armv81 + 1232
10 libdispatch.dylib | __dispatch_root_queue_drain + 340
11 libdispatch.dylib | __dispatch_worker_thread2 + 116
12 libsystem_pthread.dylib | _pthread_wqthread + 464
13 libsystem_pthread.dylib | start_wqthread + 4

**Device information (设备信息)**
 - Device: iphone8
 - OS: 12.3.1
 - Package Version: 4.2.2
 - Flutter Version: 1.22.6

**Comment by AlexV525** [comment]
4.x is no longer supported.
